CREATE TABLE `trips` (
  `id` int AUTO_INCREMENT NOT NULL,
  `tripNumber` varchar(50) NOT NULL,
  `jobId` int,
  `unitId` int,
  `operatorId` int,
  `manifestId` int,
  `originLocationId` int,
  `destinationFacilityId` int,
  `tripType` enum('round_trip','one_way','shuttle') NOT NULL DEFAULT 'round_trip',
  `status` enum('planned','loading','in_transit','unloading','complete','cancelled') NOT NULL DEFAULT 'planned',
  `startedAt` timestamp,
  `completedAt` timestamp,
  `odometerStartKm` double,
  `odometerEndKm` double,
  `distanceKm` double,
  `notes` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `trips_id` PRIMARY KEY(`id`),
  CONSTRAINT `trips_tripNumber_unique` UNIQUE(`tripNumber`)
);
CREATE TABLE `tripStops` (
  `id` int AUTO_INCREMENT NOT NULL,
  `tripId` int NOT NULL,
  `stopType` enum('load','unload','fuel','checkpoint') NOT NULL,
  `locationId` int,
  `facilityId` int,
  `sequence` int NOT NULL DEFAULT 1,
  `arrivedAt` timestamp,
  `setupStartedAt` timestamp,
  `operationStartedAt` timestamp,
  `operationCompletedAt` timestamp,
  `departedAt` timestamp,
  `durationMinutes` double,
  `setupMinutes` double,
  `waitMinutes` double,
  `quantity` double,
  `quantityUnit` varchar(30),
  `ticketNumber` varchar(100),
  `notes` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `tripStops_id` PRIMARY KEY(`id`)
);
CREATE TABLE `operatingZones` (
  `id` int AUTO_INCREMENT NOT NULL,
  `name` varchar(180) NOT NULL,
  `zoneType` enum('loading','unloading','both') NOT NULL,
  `locationId` int,
  `facilityId` int,
  `latitude` double NOT NULL,
  `longitude` double NOT NULL,
  `radiusMetres` double NOT NULL DEFAULT 75,
  `active` int NOT NULL DEFAULT 1,
  `verifiedAt` timestamp,
  `source` varchar(220),
  `notes` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `operatingZones_id` PRIMARY KEY(`id`)
);
CREATE TABLE `dutyRecords` (
  `id` int AUTO_INCREMENT NOT NULL,
  `operatorId` int NOT NULL,
  `tripId` int,
  `dutyStatus` enum('driving','on_duty','sleeper_berth','off_duty') NOT NULL,
  `startedAt` timestamp NOT NULL,
  `endedAt` timestamp,
  `durationMinutes` double,
  `latitude` double,
  `longitude` double,
  `locationLabel` varchar(220),
  `jurisdiction` varchar(100),
  `source` varchar(80) NOT NULL DEFAULT 'driver_entry',
  `notes` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `dutyRecords_id` PRIMARY KEY(`id`)
);
CREATE TABLE `workOrders` (
  `id` int AUTO_INCREMENT NOT NULL,
  `workOrderNumber` varchar(80) NOT NULL,
  `unitId` int NOT NULL,
  `inspectionId` int,
  `defectId` int,
  `status` enum('draft','open','in_progress','waiting_parts','ready_for_service','closed') NOT NULL DEFAULT 'open',
  `priority` enum('routine','urgent','critical') NOT NULL DEFAULT 'routine',
  `openedAt` timestamp NOT NULL,
  `startedAt` timestamp,
  `completedAt` timestamp,
  `odometerKm` double,
  `engineHours` double,
  `technician` varchar(180),
  `laborMinutes` double,
  `parts` text,
  `findings` text,
  `correctiveAction` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `workOrders_id` PRIMARY KEY(`id`),
  CONSTRAINT `workOrders_workOrderNumber_unique` UNIQUE(`workOrderNumber`)
);
