/** 0174 — shared fixtures for the Compliance Operations panels (DOM and accessibility tests). */
import type { RenewalRow, SourceRow, SweepRun, VerificationItem } from "./ComplianceOperationsView";

export const renewalRows: RenewalRow[] = [
  { userId: 1, employeeName: "Sam Driver", holdingRef: "WQ-1", code: "H2S_ALIVE", displayName: "H2S Alive", source: "wallet", targetDate: "2026-10-10", daysRemaining: 12, targetKind: "legal_expiry", readinessImpact: ["H2S Alive for sour sites"], handoff: { handoffRef: "HO-1", status: "REQUESTED" }, lastReminder: { at: "2026-09-20", title: "URGENT: H2S Alive expires in 14 days" }, nextEscalation: { threshold: 7, inDays: 5, recipients: ["employee", "supervisor", "safety", "hr"] } },
  { userId: 2, employeeName: null, holdingRef: "WQ-2", code: "WHMIS_EMPLOYER", displayName: "WHMIS", source: "wallet", targetDate: "2026-09-01", daysRemaining: -3, targetKind: "company_review", readinessImpact: [], handoff: null, lastReminder: null, nextEscalation: null },
];
export const verificationItems: VerificationItem[] = [
  { holdingRef: "WQ-9", employee: { userId: 1, name: "Sam Driver" }, code: "FIRST_AID", displayName: "First Aid", issuer: "Red Cross", issuingJurisdiction: "CA-AB", certificateNumber: "FA-9", issuedAt: "2026-09-01", expiresAt: "2029-09-01", documentRef: "DOC-1", backDocumentRef: null, restrictions: [], recordedAt: "2026-09-02", correctsHoldingRef: null, correction: null, previousVerified: { holdingRef: "WQ-3", expiresAt: "2026-09-20" }, implications: { heldNow: true, heldIfVerified: true, requirements: ["First aid on crew"], note: "" }, handoff: { handoffRef: "HO-2", status: "DOCUMENT_UPLOADED_UNVERIFIED" }, callerMayAct: true, callerBlockedBecause: null },
  { holdingRef: "WQ-10", employee: { userId: 5, name: "Me" }, code: "H2S_ALIVE", displayName: "H2S Alive", issuer: null, issuingJurisdiction: null, certificateNumber: null, issuedAt: null, expiresAt: "2029-01-01", documentRef: "DOC-2", backDocumentRef: null, restrictions: [], recordedAt: "2026-09-02", correctsHoldingRef: null, correction: null, previousVerified: null, implications: { heldNow: false, heldIfVerified: true, requirements: [], note: "" }, handoff: null, callerMayAct: false, callerBlockedBecause: "This is your own credential" },
];
export const sourceRows: SourceRow[] = [
  { sourceRef: "SRC-TDG", authority: "Transport Canada", title: "TDG Regulations", jurisdiction: "CA", edition: "2024", url: "https://tc.canada.ca/tdg", tier: "authority", retrievedAt: "2026-01-01", fingerprint: "-7ec38a5a", fingerprintKind: "legacy-stableHash", reviewStatus: "reviewed", impactStatus: "SOURCE_CURRENT", proposedByUserId: null, firstReviewedByUserId: 3, lastReviewedByUserId: 4, lastReviewedAt: "2026-02-01", supersededBySourceRef: null, supersedesSourceRef: null, rejectionReason: null, affected: { courseVersions: 1, modules: 6, questions: 40, policies: 1, regulatoryProfiles: 1 } },
  { sourceRef: "SRC-TDG@v2", authority: "Transport Canada", title: "TDG Regulations", jurisdiction: "CA", edition: "2026", url: "https://tc.canada.ca/tdg-2026", tier: "authority", retrievedAt: "2026-09-01", fingerprint: "a".repeat(64), fingerprintKind: "sha256", reviewStatus: "unreviewed", impactStatus: "SOURCE_UNREVIEWED", proposedByUserId: 3, firstReviewedByUserId: null, lastReviewedByUserId: null, lastReviewedAt: null, supersededBySourceRef: null, supersedesSourceRef: "SRC-TDG", rejectionReason: null, affected: { courseVersions: 0, modules: 0, questions: 0, policies: 0, regulatoryProfiles: 0 } },
];
export const sweepRuns: SweepRun[] = [
  { runRef: "RUN-1", slotKey: "credential-renewal-sweep:2026-09-23T14:00", status: "partial", startedAt: "2026-09-23T14:00:00Z", completedAt: "2026-09-23T14:00:03Z", inspected: 40, actionable: 6, notificationsCreated: 11, suppressed: 3, failureCount: 1, errorSummary: "NOTIFICATION_WRITE_FAILED" },
];
