/**
 * 0187 — the canonical form, pinned against vectors this code did not produce.
 *
 * `shared/eld/vectors/eld-h1.vectors.json` was generated by `eld_h1_reference.py`, an independent
 * implementation on Python's standard json module. Every expected canonical text and every SHA-256
 * below is a hard-coded value from that file; nothing here recomputes an expectation with the
 * function under test. A Kotlin or Swift producer that reproduces this file has proven itself.
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { canonicalEncode, canonicalEldEventJson, type CanonicalValue, type EldEventInput } from "../../shared/eld/eldEvent";
import { hashEldEvent, prepareEldBatch, sha256Hex } from "./eld/ledger";

type EventVector = { name: string; description: string; deviceRef: string; input: EldEventInput; canonical: string; canonicalUtf8Length: number; payloadHash: string; eventHash: string };
type ValueVector = { name: string; description: string; value: CanonicalValue; canonical: string; canonicalUtf8Length: number; sha256: string };
const vectors = JSON.parse(readFileSync("shared/eld/vectors/eld-h1.vectors.json", "utf8")) as { hashVersion: string; eventVectors: EventVector[]; valueVectors: ValueVector[] };

describe("golden vectors — the file itself", () => {
  it("is the eld-h1 set and carries the cases the protocol promises", () => {
    expect(vectors.hashVersion).toBe("eld-h1");
    const names = vectors.eventVectors.map(v => v.name);
    for (const required of ["minimal event", "complete event", "explicit nulls equal absence", "empty string annotation", "unicode", "quotation mark", "backslash", "control characters", "negative coordinate", "positive coordinate", "timestamp", "predecessor hash", "correction"]) {
      expect(names, required).toContain(required);
    }
    expect(vectors.valueVectors.map(v => v.name)).toEqual(expect.arrayContaining(["nested object, unsorted input", "array order preserved"]));
    expect(vectors.eventVectors.length + vectors.valueVectors.length).toBeGreaterThanOrEqual(15);
  });

  it("carries hashes that are literal values, not something derived here", () => {
    expect(vectors.eventVectors[0]!.payloadHash).toBe("d9ad5daf022ba7cf2fef87e5525501e7391863c7181162e9593a1a51d3aa430e");
    expect(vectors.eventVectors[0]!.eventHash).toBe("29d330b623d54e9e90c032f53586072d01bb0309ec3a20668607ad43e2de57e3");
  });
});

describe("golden vectors — events", () => {
  for (const v of vectors.eventVectors) {
    it(`${v.name}: ${v.description}`, () => {
      const canonical = canonicalEldEventJson(v.deviceRef, v.input);
      expect(canonical).toBe(v.canonical);
      expect(Buffer.byteLength(canonical, "utf8")).toBe(v.canonicalUtf8Length);
      const h = hashEldEvent(v.deviceRef, v.input);
      expect(h.payloadHash).toBe(v.payloadHash);
      expect(h.eventHash).toBe(v.eventHash);
      // The production entry point agrees with the vector too: the batch path hashes the same bytes.
      const p = prepareEldBatch(v.deviceRef, [v.input]);
      expect(p.ok, JSON.stringify(!p.ok && p.problems)).toBe(true);
      expect(p.ok && p.events[0]!.eventHash).toBe(v.eventHash);
    });
  }

  it("explicit nulls and the minimal event are the same bytes", () => {
    const minimal = vectors.eventVectors.find(v => v.name === "minimal event")!;
    const nulls = vectors.eventVectors.find(v => v.name === "explicit nulls equal absence")!;
    expect(nulls.canonical).toBe(minimal.canonical);
    expect(nulls.payloadHash).toBe(minimal.payloadHash);
  });

  it("the predecessor changes only the event hash", () => {
    const minimal = vectors.eventVectors.find(v => v.name === "minimal event")!;
    const chained = vectors.eventVectors.find(v => v.name === "predecessor hash")!;
    expect(chained.payloadHash).toBe(minimal.payloadHash);
    expect(chained.eventHash).not.toBe(minimal.eventHash);
  });
});

describe("golden vectors — values", () => {
  for (const v of vectors.valueVectors) {
    it(`${v.name}: ${v.description}`, () => {
      const canonical = canonicalEncode(v.value);
      expect(canonical).toBe(v.canonical);
      expect(Buffer.byteLength(canonical, "utf8")).toBe(v.canonicalUtf8Length);
      expect(sha256Hex(canonical)).toBe(v.sha256);
    });
  }
});
