/**
 * 0172 — Commercial Driver Study Centre, Study Library and company field training.
 *
 * Everything here is PREPARATION. LeaseOS practice and study do not issue a
 * provincial driver's licence, a road-test result, a Q endorsement, an H2S
 * Alive or First Aid certificate. Every course below carries that notice and
 * the external-track boundary, so `certificateDecision` refuses to issue from
 * it no matter who asks.
 *
 * The questions are ORIGINAL LeaseOS practice questions written against the
 * cited official publication. They are not government knowledge-test
 * questions and must never be presented as such. Each one names the source
 * and chapter it was written from, and the bank is version-locked to the
 * source edition: a new guide edition means a new course version, and old
 * attempts stay on the version they were taken against.
 *
 * Jurisdiction-aware: courses carry a jurisdiction and the sources carry
 * theirs. Saskatchewan, BC and others are added as new source records and new
 * course codes, not by editing Alberta's.
 */
import type { AcademyContentBlockSeed, AcademyCourseSeed, AcademyModuleSeed, AcademySourceSeed } from "./trainingAcademyCatalog";
import type { AcademyQuestion } from "./trainingAcademy";

/* ------------------------------------------------------------------ */
/* Study Library — authoritative sources and provider directories       */
/* ------------------------------------------------------------------ */

const RETRIEVED = "2026-09-23";

/**
 * Seeded UNREVIEWED. `licenceStatus` records what the publisher states, which
 * is not the same as LeaseOS having confirmed it: an offline copy is retained
 * only after a reviewer confirms redistribution rights (see
 * `offlineCopyDecision`). Until then the learner is sent to the official URL.
 */
export const STUDY_LIBRARY_SOURCES: AcademySourceSeed[] = [
  { sourceRef: "SRC-AB-DRIVERS-GUIDE", authority: "Government of Alberta — Transportation and Economic Corridors", sourceTier: "authority", title: "Driver's Guide: Cars and Light Trucks", sourceUrl: "https://open.alberta.ca/publications/drivers-guide", jurisdiction: "CA-AB", edition: "2026 (published May 2026)", sourceKind: "study_source", licenceStatus: "open_licence_stated", licenceNote: "Publisher catalogue states Open Government Licence – Alberta. Not yet confirmed by a LeaseOS reviewer.", retrievedOn: RETRIEVED, contentHash: null, notes: "Base knowledge for every class; the Class 2/3/4 knowledge test draws on this guide and the Commercial Driver's Guide." },
  { sourceRef: "SRC-AB-COMMERCIAL-GUIDE", authority: "Government of Alberta — Transportation and Economic Corridors", sourceTier: "authority", title: "Commercial Driver's Guide — trucks, buses, emergency responders and taxis", sourceUrl: "https://open.alberta.ca/publications/commercial-drivers-guide", jurisdiction: "CA-AB", edition: "Spring 2025 (catalogue updated 2025-07-09)", sourceKind: "study_source", licenceStatus: "open_licence_stated", licenceNote: "The PDF states it is made available under the Open Government Licence – Alberta. Retrieved PDF sha256 recorded; reviewer confirmation still required before an offline copy is served.", retrievedOn: RETRIEVED, contentHash: "9bc07d7038bd9e339b2ecaf141890d302deececc6dc94e4daf1d2c591f392926", notes: "The guide states it has no legal authority; the Traffic Safety Act and regulations govern. For Class 1, the C1LP curriculum takes precedence over this guide." },
  { sourceRef: "SRC-AB-C1LP", authority: "Government of Alberta — Transportation and Economic Corridors", sourceTier: "authority", title: "Class 1 Learning Pathway", sourceUrl: "https://www.alberta.ca/class-1-learning-pathway", jurisdiction: "CA-AB", edition: "page reviewed 2026-09 (training hours changed 2026-09-01)", sourceKind: "regulatory_reference", licenceStatus: "link_only", retrievedOn: RETRIEVED, contentHash: null, capabilityCodes: ["CLASS1"], notes: "Entry (40 h) → Core Learning (67 h from 2026-09-01; 60 h under contracts signed on/before 2026-08-31) → provincially restricted Class 1 → Competence Building (10–18 h from 2026-09-01) removes the restriction → Advanced training. An 8-hour air-brake course is required if Q is not already held." },
  { sourceRef: "SRC-AB-C1LP-LMS", authority: "Government of Alberta — Transportation and Economic Corridors", sourceTier: "authority", title: "Class 1 Learning Pathway online learning system", sourceUrl: "https://www.alberta.ca/class-1-learning-pathway-online-learning-system", jurisdiction: "CA-AB", edition: "page reviewed 2026-09", sourceKind: "regulatory_reference", licenceStatus: "link_only", retrievedOn: RETRIEVED, contentHash: null, capabilityCodes: ["CLASS1"], notes: "Official self-led Entry Program. LeaseOS links to it and records reported progress; it does not replace it." },
  { sourceRef: "SRC-AB-AIR-BRAKE", authority: "Government of Alberta — Transportation and Economic Corridors", sourceTier: "authority", title: "Air Brake Program (Q endorsement)", sourceUrl: "https://www.alberta.ca/air-brake-program", jurisdiction: "CA-AB", edition: "page reviewed 2026-09", sourceKind: "provider_directory", licenceStatus: "link_only", retrievedOn: RETRIEVED, contentHash: null, capabilityCodes: ["AIR_BRAKE_Q"], notes: "Q is placed on a licence after an approved Alberta air brake course through an authorized organization. No recurring renewal requirement for Q itself." },
  { sourceRef: "SRC-AB-COMMERCIAL-UPGRADE", authority: "Government of Alberta — Transportation and Economic Corridors", sourceTier: "authority", title: "Upgrade to a commercial driver's licence", sourceUrl: "https://www.alberta.ca/upgrade-commercial-licence", jurisdiction: "CA-AB", edition: "page reviewed 2026-09", sourceKind: "regulatory_reference", licenceStatus: "link_only", retrievedOn: RETRIEVED, contentHash: null, capabilityCodes: ["CLASS1", "CLASS2", "CLASS3", "CLASS4"], notes: "Knowledge test, vision, medical and road-test requirements by class." },
  { sourceRef: "SRC-AB-DRIVER-TRAINING-SCHOOLS", authority: "Government of Alberta — Transportation and Economic Corridors", sourceTier: "authority", title: "Licensed driver training schools", sourceUrl: "https://www.alberta.ca/licensed-driver-training-schools", jurisdiction: "CA-AB", edition: "page reviewed 2026-09", sourceKind: "provider_directory", licenceStatus: "link_only", retrievedOn: RETRIEVED, contentHash: null, capabilityCodes: ["CLASS1", "CLASS2", "CLASS3", "CLASS4", "AIR_BRAKE_Q"], notes: "Authoritative directory. A company's preferred school is recorded separately as a company provider." },
  { sourceRef: "SRC-AB-DRIVER-MEDICAL", authority: "Government of Alberta — Transportation and Economic Corridors", sourceTier: "authority", title: "Driver medical fitness", sourceUrl: "https://www.alberta.ca/driver-medical-fitness", jurisdiction: "CA-AB", edition: "page reviewed 2026-09", sourceKind: "regulatory_reference", licenceStatus: "link_only", retrievedOn: RETRIEVED, contentHash: null, notes: "LeaseOS records only the compliance fact (met / verified by / valid until). No diagnosis or medical detail." },
  { sourceRef: "SRC-AB-FIRST-AID-AGENCIES", authority: "Government of Alberta — Occupational Health and Safety", sourceTier: "authority", title: "First aid training — approved training agencies and certificate verification", sourceUrl: "https://www.alberta.ca/first-aid-training", jurisdiction: "CA-AB", edition: "page reviewed 2026-09 (agency list updated quarterly)", sourceKind: "provider_directory", licenceStatus: "link_only", retrievedOn: RETRIEVED, contentHash: null, capabilityCodes: ["FIRST_AID_BASIC", "FIRST_AID_INTERMEDIATE", "FIRST_AID_ADVANCED"], notes: "Find an approved Alberta workplace First Aid agency. Distinct from any provider the company normally uses." },
  { sourceRef: "SRC-ESC-H2S-ALIVE", authority: "Energy Safety Canada", sourceTier: "industry_association", title: "H2S Alive® and H2S Alive® Blended Renewal — authorized training providers", sourceUrl: "https://www.energysafetycanada.com/course/10490", jurisdiction: "CA", edition: "reference 2026-09 (automated retrieval refused by the site; verify manually)", sourceKind: "provider_directory", licenceStatus: "link_only", retrievedOn: RETRIEVED, contentHash: null, capabilityCodes: ["H2S_ALIVE"], notes: "Certificate valid three years. Blended Renewal requires a valid (not expired) H2S Alive certificate; the provider applies its own current conditions. The ESC site could not be fetched automatically from this environment, so these facts must be confirmed by a reviewer." },
  { sourceRef: "SRC-TC-TDG-TRAINING", authority: "Transport Canada", sourceTier: "authority", title: "TDG training — Part 6", sourceUrl: "https://tc.canada.ca/en/dangerous-goods/training", jurisdiction: "CA", edition: "page reviewed 2026-09", sourceKind: "regulatory_reference", licenceStatus: "link_only", retrievedOn: RETRIEVED, contentHash: null, notes: "Employer-issued training certificate; LeaseOS models the road scope through REG-TDG-ROAD-V1." },
  { sourceRef: "SRC-CCOHS-WHMIS-TRAINING", authority: "Canadian Centre for Occupational Health and Safety", sourceTier: "authority", title: "WHMIS — education and training", sourceUrl: "https://www.ccohs.ca/oshanswers/chemicals/whmis_ghs/education_training.html", jurisdiction: "CA", edition: "page reviewed 2026-09", sourceKind: "regulatory_reference", licenceStatus: "link_only", retrievedOn: RETRIEVED, contentHash: null, notes: "Generic education plus workplace-specific training. No government certificate expiry is created by LeaseOS." },
  { sourceRef: "SRC-COMPANY-FIELD-TEMPLATE", authority: "Employer", sourceTier: "authority", title: "Company field procedures template (lease roads, radio, spotters, equipment)", sourceUrl: "internal://leaseos/academy/company-field-template", jurisdiction: "COMPANY", edition: "template-1", sourceKind: "study_source", licenceStatus: "link_only", retrievedOn: RETRIEVED, contentHash: null, notes: "Company-specific training, identified as company procedure — not regulation. Cannot govern a certificate until the employer reviews its own version." },
];

/* ------------------------------------------------------------------ */
/* Builders                                                             */
/* ------------------------------------------------------------------ */

const CDG = "SRC-AB-COMMERCIAL-GUIDE";
const block = (code: string, kind: AcademyContentBlockSeed["kind"], title: string, ...body: string[]): AcademyContentBlockSeed => ({ code, kind, title, body });
const mod = (code: string, title: string, domain: string, minutes: number, sourceRef: string, sourceSection: string, blocks: AcademyContentBlockSeed[], extra: Partial<AcademyModuleSeed> = {}): AcademyModuleSeed =>
  ({ code, title, domain, minutes, blocks, sourceRef, sourceSection, ...extra });

type Q = [domain: string, section: string, prompt: string, correct: string, wrong: [string, string, string], explanation: string, critical?: boolean];
function bank(prefix: string, sourceRef: string, qs: Q[]): AcademyQuestion[] {
  return qs.map(([domain, section, prompt, correct, wrong, explanation, critical], i) => ({
    code: `${prefix}-P${String(i + 1).padStart(2, "0")}`, domain, prompt, options: [correct, ...wrong], correctIndex: 0, explanation, critical: !!critical, sourceRef, sourceSection: section,
  }));
}

const BOUNDARY = "Preparation only. LeaseOS study and practice do not issue a provincial driver's licence, a road-test result or a Q endorsement. The official publication governs; these questions are original LeaseOS practice questions, not government test questions.";
const studyCentre = (jurisdiction: string, notice = BOUNDARY) => ({ track: "commercial_driver" as const, jurisdiction, boundaryNotice: notice });
const boundaryBlock = (code: string) => block(code, "callout", "What this study can and cannot do", BOUNDARY);

/* ------------------------------------------------------------------ */
/* Alberta Commercial Driver Foundation                                 */
/* ------------------------------------------------------------------ */

const FOUNDATION_Q = bank("ABF", CDG, [
  ["licensing", "Ch. 1 — Commercial driver's licences", "Which Alberta licence class covers a single motor vehicle with three or more axles?", "Class 3", ["Class 4", "Class 5", "Class 6"], "The Commercial Driver's Guide lists a single motor vehicle with three or more axles under Class 3."],
  ["licensing", "Ch. 1 — Commercial driver's licences", "A Class 4 licence permits a bus with a seating capacity of up to how many, excluding the operator?", "24", ["11", "15", "40"], "Class 4 covers a bus with seating capacity of not more than 24 excluding the operator, plus ambulances and taxis. A school bus also needs an S endorsement."],
  ["licensing", "Ch. 1 — Commercial driver's licences", "A Class 3 holder is transporting people other than the driver. What vehicle limit applies?", "No vehicle with a seating capacity of more than 15", ["No vehicle over 11,794 kg", "No vehicle with air brakes", "No vehicle with more than two axles"], "The guide states a Class 3 holder shall not operate a vehicle with seating capacity over 15 while transporting anyone other than the driver, nor transport passengers for hire."],
  ["licensing", "Ch. 1 — Upgrading your licence", "What is the minimum age to learn or be licensed for Classes 1–4 in Alberta?", "18 years", ["16 years", "17 years", "21 years"], "The minimum learning or licensing age for each commercial class is 18."],
  ["licensing", "Ch. 1 — Medical fitness", "Which upgrades require a medical report?", "Class 1, 2 or 4", ["Class 3 only", "All classes including 5", "None — medicals are only for buses"], "A medical report is required to upgrade to Class 1, 2 or 4, and at regular intervals to keep those classes."],
  ["licensing", "Ch. 1 — Medical fitness", "Under 45, how often must a Class 1, 2 or 4 holder provide a medical report to keep the licence?", "Every five years", ["Every year", "Every three years", "Only when the licence is renewed"], "Every five years until 45, every three years from 45 to 65, and every year after 65."],
  ["licensing", "Ch. 1 — Definitions", "What does a Q endorsement mean on an Alberta licence?", "The driver completed an approved Alberta air brake course through an authorized organization", ["The driver passed a LeaseOS air brake quiz", "The driver may carry passengers for hire", "The driver may haul dangerous goods"], "Q is placed on the licence after an approved Alberta air brake course. LeaseOS practice never adds it.", true],
  ["licensing", "Ch. 1 — Definitions", "Is an air brake Q endorsement required for an air-actuated hydraulic braking system (air assisted, all foundation brakes hydraulic)?", "No", ["Yes, always", "Only for Class 3", "Only in winter"], "The guide distinguishes air-over-hydraulic (Q or Class 1 required) from air-actuated hydraulic (Q not required)."],
  ["licensing", "Ch. 1 — Knowledge test", "How is the Alberta commercial knowledge test described in the guide?", "30 multiple-choice questions; at least 25 correct to pass", ["20 questions; 15 to pass", "50 questions; 40 to pass", "There is no written test"], "The guide describes 30 questions with a minimum of 25 correct. LeaseOS mock exams use a similar length but are not the government test."],
  ["inspection", "Ch. 3 — Trip inspections", "How long is a completed trip inspection and report valid?", "24 hours", ["12 hours", "One shift regardless of length", "Until the next defect"], "The guide states the inspection and report are valid for a maximum of 24 hours.", true],
  ["inspection", "Ch. 3 — Driving with defects", "You find a MAJOR defect listed on the inspection schedule. What is required?", "Do not drive the vehicle on a highway until it is repaired; report it without delay", ["Record it and drive to the next town", "Report it at the next daily inspection", "Drive if a supervisor agrees verbally"], "No person shall drive a commercial vehicle on a highway with a scheduled major defect present.", true],
  ["inspection", "Ch. 3 — Driving with defects", "When may a driver continue with a MINOR defect listed on the schedule?", "After entering it on the report and reporting it to the carrier", ["Never", "Only after a mechanic's repair", "Only in daylight"], "A minor defect may be driven on once recorded on the daily report and reported to the carrier."],
  ["inspection", "Ch. 3 — Vehicles that require inspections", "Which provincially regulated trucks require trip inspection reports?", "Trucks registered for 11,794 kg and greater", ["All pickup trucks", "Only tractor-trailers", "Trucks over 4,500 kg only when leaving Alberta"], "Provincial carriers: trucks registered for 11,794 kg or more and passenger vehicles seating 11 or more including the driver."],
  ["stopping", "Ch. 4 — How long does it take to stop", "Total stopping distance is the sum of which distances?", "Perception, reaction, lag (air brake) and braking distance", ["Reaction and braking only", "Braking distance only", "Speed times weight"], "The guide lists perception, reaction, lag time and braking distance."],
  ["stopping", "Ch. 4 — How long does it take to stop", "Why does an air-braked vehicle have 'lag time'?", "Compressed air takes time to flow through the system and apply the brakes", ["The driver waits for the ABS light", "Air brakes are only applied by the trailer", "Lag is caused by cold tires"], "Air brakes do not respond immediately; the guide gives about 4/10 of a second."],
  ["stopping", "Ch. 4 — How long does it take to stop", "Compared with level ground, stopping distance going downhill at the same speed is…", "Longer", ["Shorter", "The same", "Only different when loaded"], "Gravity increases stopping distance downhill and shortens it uphill."],
  ["space", "Ch. 4 — Following distance", "What minimum following distance does the guide recommend for large vehicles in good conditions?", "Four seconds", ["Two seconds", "One vehicle length per 10 km/h", "Ten seconds"], "Use the four-second rule for large vehicles; double it when weather, road or traffic conditions are poor."],
  ["space", "Ch. 4 — Following distance", "Road conditions are poor. What should you do with your following distance?", "Double it", ["Keep four seconds", "Reduce it to stay with traffic", "Match the vehicle ahead"], "The guide says to double your following distance in poor conditions."],
  ["mirrors", "Ch. 4 — Adjust seat and mirrors", "When correctly adjusted, where is the horizon line seen in a flat side mirror?", "About three-quarters of the way up the mirror", ["At the very top", "In the middle", "At the bottom edge"], "The guide's mirror adjustment places the horizon about three-quarters up and the vehicle side along the inside edge."],
  ["mirrors", "Ch. 4 — Blind spots", "Behind a large vehicle without a rear window, the blind spot can extend roughly how far?", "15 to 45 metres", ["1 to 2 metres", "Only the bumper width", "100 metres or more"], "The guide describes a rear blind spot extending 15 to 45 metres."],
  ["turning", "Ch. 5 — Off-tracking", "In a low-speed turn, which way do the rear tires of a long vehicle track?", "Inward of the steering tires' path", ["Outward of the steering path", "Exactly in the steering path", "It depends only on tire pressure"], "Low-speed off-tracking pulls the rear tires inward; a longer wheelbase or tighter turn increases it."],
  ["turning", "Ch. 5 — Off-tracking", "What causes high-speed off-tracking?", "Centrifugal (outward) force when entering a curve too fast", ["Under-inflated steer tires", "Using the engine retarder", "A short wheelbase"], "At speed the rear tires pull outward from the steering path. Enter curves at moderate speed."],
  ["backing", "Ch. 6 — Before unloading (dump vehicles)", "Backing into an unfamiliar area, what should you do first?", "Get out, look around and walk the route you will follow", ["Rely on the backup alarm", "Back quickly to limit exposure", "Use only the convex mirror"], "The guide: move slowly; before backing in an unfamiliar area, get out, look around and walk the route."],
  ["backing", "Ch. 6 — Before unloading (dump vehicles)", "You lose sight of your guide (spotter) while backing. What do you do?", "Stop until you can see the guide again", ["Continue slowly", "Sound the horn and continue", "Switch to the other mirror and continue"], "The driver should always be able to see the guide — stop if you cannot.", true],
  ["backing", "Ch. 6 — Before unloading", "Which side should you back toward when possible for better visibility?", "The driver's side (left)", ["The passenger side (right)", "Straight back only", "Whichever is shorter"], "Backing to the driver's side gives better visibility; blind-side reversing is the most difficult and should be avoided."],
  ["cargo", "Ch. 6 — Loading dump vehicles", "Before moving a loaded dump vehicle, which condition must be met?", "Material evenly distributed and the load secured so it cannot blow or fall off", ["The tailgate is open for balance", "The load is heaped at the rear", "The tarp is off to check the load"], "The guide lists even distribution and a secured load among the conditions before moving."],
  ["fatigue", "Ch. 4 — Preventing fatigue", "Which is a warning sign of driver fatigue?", "Driving the past few kilometres without remembering them", ["Feeling hungry", "Needing to adjust the mirrors", "Seeing a weigh scale sign"], "Missing the last few kilometres is a classic fatigue warning sign listed in the guide."],
  ["rail", "Ch. 5 — Railway crossings", "Your vehicle stalls on a crossing and a train is coming. Which way do you move after getting out?", "Away from the track, toward the oncoming train", ["Along the track away from the train", "Stay in the cab and restart", "Across to the far side, same direction as the train"], "Moving toward the train's direction (away from the track) reduces the chance of being struck by debris.", true],
]);

const foundationModules: AcademyModuleSeed[] = [
  mod("ABF-01", "Licence classes and what each allows", "licensing", 30, CDG, "Ch. 1 — Commercial driver's licences", [boundaryBlock("ABF-01-0"), block("ABF-01-A", "lesson", "Classes 1–4", "Class 1: any vehicle or combination except a motorcycle. Class 2: buses (S endorsement for school buses) plus Class 3/4/5 vehicles. Class 3: single vehicles with three or more axles, with limits on passengers. Class 4: taxis, ambulances and buses seating up to 24 excluding the operator.", "Check the current guide — class privileges are set by regulation and can change."), block("ABF-01-B", "lesson", "Endorsements are separate", "Q (air brakes) and S (school bus) are endorsements added by the issuing authority. A LeaseOS course never adds one.")]),
  mod("ABF-02", "Upgrading, knowledge test, vision and medical", "licensing", 20, CDG, "Ch. 1 — Upgrading your licence", [block("ABF-02-A", "lesson", "The official route", "Knowledge tests are taken at registry agent offices; road tests are conducted by Government of Alberta driver examiners.", "A medical report is required for Class 1, 2 and 4, and at intervals to keep them. LeaseOS records only whether that requirement is met — never medical detail.")]),
  mod("ABF-03", "Trip inspections and defects", "inspection", 35, CDG, "Ch. 3 — Trip inspections", [block("ABF-03-A", "procedure", "Inspect, record, report", "The trip inspection follows a schedule, is signed, and is valid for up to 24 hours.", "Major defects: do not drive on a highway, report without delay. Minor defects: record and report, then you may continue."), block("ABF-03-B", "callout", "Company practice", "Your company's written maintenance program decides who receives defect reports. Use the LeaseOS defect workflow so nothing is lost.")], { practical: true }),
  mod("ABF-04", "Stopping distance, space and mirrors", "stopping", 30, CDG, "Ch. 4 — Having a safe trip", [block("ABF-04-A", "lesson", "Four parts of stopping", "Perception, reaction, air-brake lag and braking distance add up. Weight, speed and grade change the total dramatically."), block("ABF-04-B", "lesson", "Space and mirrors", "Four seconds minimum behind for large vehicles; double it in poor conditions. Set mirrors before you drive; know the large blind spots.")]),
  mod("ABF-05", "Turning, off-tracking and backing", "turning", 30, CDG, "Ch. 5 — Basic commercial vehicle operations", [block("ABF-05-A", "lesson", "Off-tracking", "Low speed: rear wheels cut inside. High speed: rear wheels pull outside. Plan turns and curves for both."), block("ABF-05-B", "procedure", "Backing", "Avoid backing when you can. If you must: walk the route, back to the driver's side, use a guide and stop if you cannot see them.")], { practical: true }),
  mod("ABF-06", "Loads, dump vehicles and railway crossings", "cargo", 25, CDG, "Ch. 5–6 — Railway crossings; dump vehicles", [block("ABF-06-A", "lesson", "Load before you move", "Even distribution, secured load, tailgate and equipment secured, within axle and dimension limits for the jurisdiction."), block("ABF-06-B", "callout", "Stuck on the tracks", "Get out immediately. Move away from the track toward the oncoming train.")]),
  mod("ABF-07", "Lease, gravel and resource roads (company training)", "company_roads", 20, "SRC-COMPANY-FIELD-TEMPLATE", "Company field procedures — lease roads", [block("ABF-07-A", "callout", "Company content", "This module is company training, identified as such. It is not regulation and it is not from the Alberta guides."), block("ABF-07-B", "procedure", "On lease and resource roads", "Follow the posted radio protocol and kilometre call-outs. Adjust speed to surface, dust and visibility. Watch soft shoulders, especially loaded. Yield according to site rules.")], { companySpecific: true }),
];

/* ------------------------------------------------------------------ */
/* Air Brake Q preparation                                              */
/* ------------------------------------------------------------------ */

const AB_SECTION = "Ch. 3 — Trip air brake inspection";
const AIRBRAKE_Q = bank("AIRQ", CDG, [
  ["supply", AB_SECTION, "What does the governor do in an air brake system?", "Controls when the compressor pumps air and when it stops (cut-in and cut-out)", ["Releases the spring brakes", "Warns the driver of low air", "Meters air to the brake chambers"], "The governor sets the cut-out and cut-in points of the compressor."],
  ["supply", AB_SECTION, "During the trip air brake inspection, what governor cut-out range does the guide give?", "120–135 psi (828–931 kPa)", ["60–80 psi", "90–100 psi", "150–175 psi"], "Build to system maximum to confirm governor cut-out at 120–135 psi."],
  ["supply", AB_SECTION, "How much lower than cut-out should the governor cut-in be?", "20–25 psi lower", ["5 psi lower", "50 psi lower", "It should be the same"], "Pump the service brakes until the governor cuts in; confirm cut-in is 20–25 psi below cut-out."],
  ["supply", AB_SECTION, "What does the compressor build-up test in the guide expect?", "50 to 90 psi within three minutes at fast idle", ["0 to 120 psi in one minute", "90 to 120 psi in ten minutes", "Any build-up is acceptable"], "Run at fast idle (around 1200 RPM); build from 50 to 90 psi within three minutes."],
  ["supply", "Ch. 1 — Definitions; air system components", "What stores compressed air for braking?", "The reservoirs (air tanks)", ["The slack adjusters", "The treadle valve", "The brake chambers"], "Reservoirs hold the compressed air the system draws on."],
  ["supply", "Air system maintenance (company training)", "Why are reservoirs drained?", "To remove water and oil that collect and can damage or freeze the system", ["To test the low-air warning", "To release the parking brakes", "To reset the governor"], "Moisture and oil accumulate in reservoirs; draining (or an air dryer) keeps them out of valves and lines."],
  ["warning", AB_SECTION, "By what pressure should the low air pressure warning light go out during build-up?", "By 60 psi (414 kPa)", ["By 20 psi", "By 100 psi", "Only at cut-out"], "Low air pressure warning light should go out by 60 psi during build-up and come on by 60 psi when pressure is reduced."],
  ["warning", AB_SECTION, "The low air warning activates while you are driving. What should you do?", "Stop safely as soon as possible and find the cause — do not continue", ["Keep driving to the shop", "Pump the brakes to raise pressure", "Pull the trailer hand valve and continue"], "Low air warns that braking capacity is compromised; spring brakes may apply as pressure falls.", true],
  ["spring", "Air brake components (company training)", "How are spring (parking/emergency) brakes applied and released?", "Applied by spring force; held released by air pressure", ["Applied by air; released by springs", "Applied by the treadle only", "Applied electrically"], "Loss of air lets the springs apply the brakes — which is why they act as emergency brakes."],
  ["spring", AB_SECTION, "In the park control valve check, at what pressure range should the yellow park control valve pop out?", "20–45 psi (138–311 kPa)", ["60–90 psi", "100–120 psi", "It should never pop out"], "Push the park control valve, pump the foot valve; it should pop out at 20–45 psi."],
  ["tractor_protection", AB_SECTION, "With the trailer air lines disconnected, at what pressure should the red trailer air supply valve pop out?", "40–60 psi (276–414 kPa) or higher", ["5–10 psi", "90–100 psi", "It should stay in"], "The tractor protection check expects the trailer supply valve to pop out at 40–60 psi or higher."],
  ["tractor_protection", "Class 1 combination air systems", "What is the purpose of the tractor protection system?", "To protect the tractor's air supply if the trailer lines break or separate", ["To apply the tractor's spring brakes when parked", "To increase trailer brake force", "To warn of overheating brakes"], "It isolates and protects the tractor's air if trailer air is lost."],
  ["tractor_protection", AB_SECTION, "With trailer lines disconnected, you apply the foot valve. What should you observe at the open trailer service line?", "No air leaking from it", ["A steady flow of air", "Air from the supply line only", "The low air light going out"], "Apply and hold; no air should leak from the open trailer service line."],
  ["leakage", AB_SECTION, "In the applied leakage test, how long do you hold a full service application?", "2 minutes", ["10 seconds", "30 seconds", "10 minutes"], "Engine off, apply and firmly hold a full service application for 2 minutes."],
  ["leakage", AB_SECTION, "What maximum loss does the guide allow in the applied leak test for a power unit alone?", "4 psi (28 kPa), plus 2 psi per trailer", ["10 psi plus 5 per trailer", "1 psi total", "20 psi total"], "Maximum 4 psi for power units, plus 2 psi per trailer, after the system stabilizes.", true],
  ["service", "Ch. 4 — How long does it take to stop", "About how long is air brake lag according to the guide?", "About 4/10 of a second", ["About 4 seconds", "About 1/100 of a second", "There is no lag with air brakes"], "Compressed air takes time to reach the chambers — about 0.4 seconds."],
  ["service", "Air brake components (company training)", "What does the foot (treadle) valve do?", "Meters air to the service brake chambers in proportion to pedal pressure", ["Releases the spring brakes", "Controls compressor cut-out", "Drains the reservoirs"], "The treadle controls the service application."],
  ["adjustment", "Ch. 3 — Daily walk-around: brakes", "What does excessive pushrod travel indicate?", "The brake is out of adjustment", ["The compressor is failing", "The reservoir is full", "The brakes are properly set"], "The walk-around checks slack adjuster angle and push rod travel; excessive travel means the brake needs adjustment.", true],
  ["adjustment", "Ch. 4 — Class 1 braking", "What can result from brakes that are not adjusted evenly?", "Some brakes work harder than others, which can cause a skid", ["Better fuel economy", "Shorter stopping distance", "Nothing — ABS corrects it"], "The guide warns that poorly adjusted brakes make others work harder and can cause a skid."],
  ["service", "Ch. 4 — Class 1 braking", "Why should you not use the trailer hand valve as your regular brake?", "It wears trailer brakes more than tractor brakes and unbalances braking, risking a jackknife", ["It uses more air", "It is illegal in Alberta", "It disables ABS"], "The guide describes unbalanced braking and jackknife risk."],
  ["grades", "Ch. 5 — Driving on grades", "Descending a long, steep grade, what is the safer technique?", "Downshift before the descent and use engine/transmission retarders where permitted", ["Coast in neutral", "Ride the brakes continuously", "Descend in top gear to save time"], "Select a lower gear before going down; continuous braking overheats brakes and causes fade."],
  ["inspection", AB_SECTION, "What is the first step of the trip air brake inspection in the guide?", "Chock the wheels on level ground and visually inspect the air brake components", ["Start the engine at full throttle", "Drain every reservoir", "Release the spring brakes"], "Step 1: chock wheels on level ground; visual inspection of components."],
  ["inspection", AB_SECTION, "What is the final part of the guide's trip air brake inspection?", "Service brake response tests with the foot valve and the trailer hand valve", ["Measuring tire tread", "Checking the fifth wheel", "Draining the wet tank"], "Step 6: remove chocks, release park brakes and perform brake response tests."],
  ["licensing", "Ch. 1 — Definitions", "How is a Q endorsement obtained in Alberta?", "By completing an approved Alberta air brake course through an authorized organization", ["By passing this LeaseOS course", "Automatically with a Class 3", "By a supervisor's sign-off"], "Completion of this LeaseOS preparation never creates Q.", true],
  ["licensing", "Air Brake Program", "Once Q is on an Alberta licence, is there a recurring renewal requirement for Q itself?", "No — but the licence it sits on must stay valid", ["Yes, every three years", "Yes, every five years", "Yes, annually with the medical"], "Alberta currently has no renewal requirement for Q; LeaseOS creates no Q expiry reminders."],
]);

const airBrakeModules: AcademyModuleSeed[] = [
  mod("AIRQ-01", "Compressor, governor and reservoirs", "supply", 30, CDG, AB_SECTION, [boundaryBlock("AIRQ-01-0"), block("AIRQ-01-A", "lesson", "Air supply", "An engine-driven compressor fills the reservoirs. The governor stops the compressor at cut-out and restarts it at cut-in. Reservoirs store air and collect moisture and oil that must be drained.")]),
  mod("AIRQ-02", "Service brakes, lag and adjustment", "service", 30, CDG, "Ch. 3–4 — Walk-around; stopping distance", [block("AIRQ-02-A", "lesson", "Service application", "The foot valve meters air to the brake chambers; pushrods and slack adjusters apply the foundation brakes. Air brakes lag about 0.4 s. Excess pushrod travel means out of adjustment.")]),
  mod("AIRQ-03", "Spring brakes, park control and emergency circuits", "spring", 25, CDG, AB_SECTION, [block("AIRQ-03-A", "lesson", "Springs apply, air releases", "Spring brakes are held off by air. When air is lost they apply. The yellow park control valve and red trailer supply valve pop out as pressure falls to their thresholds.")]),
  mod("AIRQ-04", "Low-air warning and tractor protection", "warning", 20, CDG, AB_SECTION, [block("AIRQ-04-A", "lesson", "Warnings", "The low air warning must come on by 60 psi. Low air while driving means stop safely and find the cause."), block("AIRQ-04-B", "lesson", "Tractor protection", "Protects the tractor's air if the trailer lines break; checked with the lines disconnected.")]),
  mod("AIRQ-05", "Trip air brake inspection sequence (practical)", "inspection", 40, CDG, AB_SECTION, [block("AIRQ-05-A", "procedure", "Six steps", "1 Chock and visual. 2 Tractor protection. 3 Park control valve. 4 Supply circuit: build-up, warning, cut-out, cut-in. 5 Applied leakage. 6 Brake response.", "Values come from the current guide; verify against the current edition before relying on them."), block("AIRQ-05-B", "callout", "Practical is separate", "Demonstrating this sequence to a company evaluator is a company competency. The Q endorsement comes only from an approved Alberta air brake course.")], { practical: true }),
];

/* ------------------------------------------------------------------ */
/* Class 3                                                              */
/* ------------------------------------------------------------------ */

const CLASS3_Q = bank("C3", CDG, [
  ["licensing", "Ch. 1 — Class 3", "What must a Class 3 road-test vehicle be?", "A single motor vehicle with three or more axles (not a three-axle RV)", ["Any pickup truck", "A tractor-trailer", "A bus seating 24"], "The guide requires a single motor vehicle with 3+ axles; three-axle recreational vehicles may not be used."],
  ["licensing", "Ch. 1 — Class 3 Road Test", "Your Class 3 road-test truck has air brakes. What must you have?", "A Q endorsement or a course completion certificate from an approved air brake organization", ["Nothing extra", "A LeaseOS air brake practice score", "A Class 1 learner's permit"], "Air-braked road-test vehicles require Q or an approved course completion certificate."],
  ["licensing", "Ch. 1 — Class 3", "May a Class 3 holder transport passengers for hire?", "No", ["Yes, up to 15", "Yes, with a medical", "Yes, on lease roads only"], "The guide lists transporting passengers for hire as prohibited for Class 3 holders."],
  ["inspection", "Ch. 3 — Additional items for Class 1 and Class 3", "Which is part of the additional Class 3 inspection items?", "Air lines secured with no leaks, kinks or cuts; slack adjusters checked", ["Checking the passenger door alarm", "Checking the school-bus stop arm", "Checking the taxi meter"], "Class 1 and 3 additional items include brake components and air lines."],
  ["cargo", "Ch. 6 — Loading dump vehicles", "When leaving the cab during loading, what procedure does the guide describe?", "Three-point contact — never jump from the vehicle", ["Jump clear of the steps", "Use the mirror bracket as a handle", "Face away from the cab"], "Two hands and one foot, or two feet and one hand, stay on the vehicle."],
  ["cargo", "Ch. 6 — Loading dump vehicles", "The loaded truck's axle weights exceed the limits where you will operate. What do you do?", "Do not move it until it is within limits (or permitted)", ["Drive slowly", "Drive at night", "Let air out of the tires"], "Loads must be within dimension and axle-weight limits for the jurisdiction."],
  ["backing", "Ch. 6 — Before unloading", "If the truck has a backing alarm near workers on foot, what must be true?", "It works, and it is automatic without a shutoff switch where the OHS Code requires", ["It can be switched off at night", "It is optional on sites", "It replaces the need for a guide"], "The guide notes OHS requirements for automatic backing alarms without a shutoff."],
  ["backing", "Ch. 5 — Reversing a Class 1 or Class 3 vehicle", "Blind-side reversing is described in the guide as…", "The most difficult and potentially most dangerous — avoid it if you can", ["The preferred method", "Only for Class 4", "Safe with a camera alone"], "Stop often and get out to check your position."],
  ["turning", "Ch. 5 — Making turns (Class 1 and 3)", "Why do long trucks need a wider path for right turns?", "Low-speed off-tracking pulls the rear wheels inside the steering path", ["The steering is slower", "The mirrors are larger", "The engine is heavier"], "Plan right turns so the rear wheels clear the curb and pedestrians."],
  ["vocational", "Company equipment orientation", "Driving authorization and equipment-operation authorization are…", "Separate — a licence to drive does not authorize operating the vac/PTO equipment", ["The same thing", "Both issued by the Class 3 road test", "Both implied by a Q endorsement"], "Equipment competency is a separate practical sign-off.", true],
  ["vocational", "Company equipment orientation", "A liquid tank (vac/water) is partly full. What handling effect should you expect?", "Surge — liquid moves forward and back when braking and accelerating", ["No effect on handling", "Better braking", "Lower stopping distance"], "Partially filled tanks surge; brake and accelerate smoothly and allow more space."],
  ["vocational", "Ch. 6 — Dump vehicles; company procedure", "Before raising a dump box, what hazard do you check overhead?", "Power lines and other overhead obstructions", ["Weather radar", "Tire tread", "The trip inspection report date"], "Overhead clearance and power lines are a primary raised-box hazard."],
  ["space", "Ch. 4 — Following distance", "You are driving a loaded tandem truck on a wet highway. Minimum following distance?", "At least eight seconds (four doubled for poor conditions)", ["Two seconds", "Four seconds", "As close as traffic allows"], "Four seconds minimum for large vehicles, doubled in poor conditions."],
  ["company_roads", "Company field procedures — lease roads", "On a radio-controlled lease road, what is the purpose of kilometre call-outs?", "To tell other traffic where you are and which way you are travelling", ["To log hours of service", "To replace headlights", "To request a spotter"], "Company procedure — call-outs prevent head-on meetings on narrow roads."],
  ["company_roads", "Company field procedures — lease roads", "The shoulder of a lease road is soft after rain. Your truck is loaded. What should you do?", "Stay off the soft shoulder, slow down and follow site rules for meeting traffic", ["Use the shoulder to pass", "Speed up to avoid sinking", "Unload onto the shoulder"], "Company procedure — soft shoulders can give way under a loaded axle."],
]);

const class3Modules: AcademyModuleSeed[] = [
  mod("C3-01", "Class 3 privileges and road test", "licensing", 20, CDG, "Ch. 1 — Class 3", [boundaryBlock("C3-01-0"), block("C3-01-A", "lesson", "What Class 3 covers", "Single vehicles with three or more axles, with limits on carrying people. The road test uses a 3+ axle vehicle; air brakes require Q or an approved course completion certificate.")]),
  mod("C3-02", "Class 3 inspection and braking", "inspection", 30, CDG, "Ch. 3 — Additional items for Class 1 and Class 3", [block("C3-02-A", "procedure", "Additional items", "Brake components, slack adjusters, air lines and suspension on top of the general walk-around.")], { practical: true }),
  mod("C3-03", "Weights, loads and dump/vocational trucks", "cargo", 30, CDG, "Ch. 6 — Loading and unloading dump vehicles", [block("C3-03-A", "lesson", "Before moving", "Even load, secured, equipment secured, within axle and dimension limits. Three-point contact getting in and out.")]),
  mod("C3-04", "Backing, spotters and site work", "backing", 25, CDG, "Ch. 5–6 — Reversing; before unloading", [block("C3-04-A", "procedure", "Guide and signals", "Agree hand signals with the guide. The guide stays outside, to the rear, where you can see them. Stop if you cannot.")], { practical: true }),
  mod("C3-05", "Vac, water and hydrovac equipment (company competency)", "vocational", 30, "SRC-COMPANY-FIELD-TEMPLATE", "Company equipment orientation", [block("C3-05-A", "callout", "Company content", "Equipment operation is company training and a separate practical competency. A licence does not authorize it."), block("C3-05-B", "lesson", "Liquid surge and PTO", "Partly-full tanks surge. Follow the unit's PTO/interlock procedure. Check overhead before raising a box or boom.")], { practical: true, companySpecific: true }),
  mod("C3-06", "Lease, gravel and forestry roads (company training)", "company_roads", 20, "SRC-COMPANY-FIELD-TEMPLATE", "Company field procedures — lease roads", [block("C3-06-A", "procedure", "Radio roads", "Call kilometre markers, stay off soft shoulders when loaded, adjust to dust and grade.")], { companySpecific: true }),
];

/* ------------------------------------------------------------------ */
/* Class 2 (bus)                                                        */
/* ------------------------------------------------------------------ */

const CLASS2_Q = bank("C2", CDG, [
  ["licensing", "Ch. 1 — Class 2", "What does a Class 2 holder need to operate a school bus?", "An S endorsement", ["A Q endorsement only", "Nothing more", "A Class 1 licence"], "Class 2 covers buses; a school bus also requires S."],
  ["licensing", "Ch. 1 — Class 2 Road Test", "The Class 2 road test requires a bus with seating capacity…", "Exceeding 24 passengers, excluding the driver", ["Of any size", "Of exactly 11", "Under 15"], "The guide sets the Class 2 road-test bus above 24 seats excluding the driver."],
  ["licensing", "Ch. 1 — Definitions", "How does the guide define a bus?", "A commercial vehicle designed to carry 11 or more persons including the driver, used to transport persons", ["Any vehicle with more than 4 seats", "A vehicle with air brakes", "A vehicle registered over 4,500 kg"], "Bus: designed for 11 or more persons including the driver."],
  ["reversing", "Ch. 5 — Reversing a bus", "When may a school bus be reversed on or next to school grounds?", "Only with a responsible person outside at the rear giving direction", ["Never under any circumstances", "Whenever the camera works", "Only when empty"], "The guide states it is illegal otherwise.", true],
  ["reversing", "Ch. 5 — Country turnaround", "When should a bus turnaround ever be done on a two-lane highway?", "Only if it cannot be done on private property — and never back onto or across a highway", ["Whenever the road is quiet", "At any intersection", "Only at night"], "Turnarounds back into a road on the right; never back onto or across a highway."],
  ["rail", "Ch. 5 — Special railway crossing information for buses", "At an uncontrolled railway crossing, which lights should a school bus use?", "Hazard lights — never the alternating amber/red lights", ["The alternating red lights", "High beams", "No lights"], "Hazard lights warn others; alternating lights must not be used for railway crossings."],
  ["rail", "Ch. 5 — Special railway crossing information for buses", "What does the school bus driver open at an uncontrolled crossing to listen for trains?", "The front door and, if practical, the window to the driver's left", ["The emergency exit", "The roof hatch", "Nothing — use mirrors"], "Reduce noise, stop in the right lane, neutral, park brake, service brake pressure, open door and left window."],
  ["passengers", "Ch. 6 — Passenger loading and unloading", "Why is a loaded bus's stopping distance much longer than a car's?", "Passenger weight adds substantially to vehicle mass", ["Buses have smaller brakes by law", "Air brakes work only when empty", "Buses are geared higher"], "The guide's example: a 66-passenger bus adds about 3000 kg of passenger weight."],
  ["passengers", "Ch. 7 — Transporting people", "What is the driver's first responsibility in passenger management?", "Passenger safety — control boarding, seating and conduct before moving", ["Keeping to schedule", "Collecting fares", "Minimizing idle time"], "Transporting people chapter — safety before schedule."],
  ["inspection", "Ch. 3 — Additional items for Class 2 and 4", "Which item belongs on a bus inspection?", "Emergency exits open and close properly (with alarms working on a school bus)", ["Fifth-wheel jaws closed", "Dump box hinge pins", "Kingpin wear"], "Bus inspection includes emergency exits, first aid kit and fire extinguisher."],
  ["mirrors", "Ch. 4 — Mirrors", "What is the convex mirror set to show?", "Objects near the vehicle", ["The horizon", "Traffic far behind only", "The driver's face"], "Set the convex mirror to identify objects near the vehicle."],
  ["emergency", "Ch. 9 — Emergency situations", "A bus has a fire. What is the priority?", "Evacuate passengers to a safe distance, then call for help", ["Fight the fire before anyone leaves", "Drive to the nearest station", "Wait for dispatch instructions"], "Life safety first — evacuation, then emergency services."],
]);

const class2Modules: AcademyModuleSeed[] = [
  mod("C2-01", "Class 2 privileges, S and Q", "licensing", 20, CDG, "Ch. 1 — Class 2", [boundaryBlock("C2-01-0"), block("C2-01-A", "lesson", "Buses", "Class 2 covers buses. School buses need S. Air-braked buses need Q.")]),
  mod("C2-02", "Bus inspection", "inspection", 30, CDG, "Ch. 3 — Special information for buses", [block("C2-02-A", "procedure", "Passenger systems", "Emergency exits and alarms, first aid kit, fire extinguisher, strobe lights, post-trip child check for school buses.")], { practical: true }),
  mod("C2-03", "Passenger management and loading", "passengers", 30, CDG, "Ch. 6–7 — Passenger loading; transporting people", [block("C2-03-A", "lesson", "People first", "Board, seat and settle before moving. Vulnerable passengers, children and language barriers need planning.")]),
  mod("C2-04", "Railway crossings, reversing and turnarounds", "rail", 25, CDG, "Ch. 5 — Railway crossings; reversing a bus", [block("C2-04-A", "procedure", "Crossings", "School bus at an uncontrolled crossing: quiet, hazards, right lane, stop, neutral, brakes, door and left window open, listen and look.")]),
];

/* ------------------------------------------------------------------ */
/* Class 1                                                              */
/* ------------------------------------------------------------------ */

const C1LP = "SRC-AB-C1LP";
const CLASS1_Q = [
  ...bank("C1", C1LP, [
    ["pathway", "Class 1 Learning Pathway — overview", "Since April 1, 2025, what must anyone seeking an Alberta Class 1 licence complete?", "The Class 1 Learning Pathway (C1LP)", ["Only the LeaseOS Class 1 course", "Class 1 MELT", "A company road test"], "C1LP replaced MELT for new Class 1 trainees. LeaseOS study supplements it and does not replace it.", true],
    ["pathway", "Class 1 Learning Pathway — tiers", "Which tiers must a new driver complete to obtain a provincially restricted Class 1?", "Entry Program and Core Learning Program", ["Entry Program only", "Competence Building only", "Advanced Driver Training"], "Entry + Core, then the road test, give a provincially restricted Class 1."],
    ["pathway", "Class 1 Learning Pathway — Tier 3", "What removes the provincial restriction from an Alberta Class 1?", "Successfully demonstrating improvement in Competence Building (Tier 3)", ["Driving for one year", "Passing a LeaseOS mock exam", "Adding a Q endorsement"], "The restriction is removed after Competence Building, allowing interprovincial operation.", true],
    ["pathway", "Class 1 Learning Pathway — restricted licence", "A driver holds a provincially restricted Class 1. Where may they operate a Class 1 vehicle?", "Only in Alberta", ["Anywhere in Canada", "Alberta and Saskatchewan", "Anywhere with a company letter"], "The restricted licence allows on-the-job experience driving only in Alberta.", true],
    ["pathway", "Class 1 Learning Pathway — Tier 2", "From September 1, 2026, how many hours is the Core Learning Program?", "67 hours (60 hours for contracts signed on or before August 31, 2026)", ["40 hours", "100 hours", "10 hours"], "Seven hours moved from Competence Building to Core Learning on 2026-09-01."],
    ["pathway", "Class 1 Learning Pathway — Tier 1", "How long is the Entry Program?", "40 hours", ["8 hours", "67 hours", "113 hours"], "The Entry Program is 40 hours and can be taken through the official online learning system or a school."],
    ["pathway", "Class 1 Learning Pathway — air brakes", "A learner without Q enters Core Learning. What is also required?", "An air brake course (8 hours) before the Class 1 road test", ["Nothing — Class 1 includes Q automatically", "A company air brake quiz", "A Class 3 licence"], "A Class 1 licence may not be obtained without first qualifying for the air brake endorsement."],
  ]),
  ...bank("C1G", CDG, [
    ["coupling", "Ch. 6 — Coupling and uncoupling", "After coupling, how do you confirm the fifth wheel has locked on the kingpin?", "A tug test against the trailer brakes and a visual check that the jaws are closed around the kingpin", ["Listening for a click only", "Checking the air gauge", "Raising the landing gear"], "Pull-test plus a visual check under the trailer — never trust the sound alone.", true],
    ["coupling", "Ch. 3 — Additional items for Class 1", "During inspection, what should you see at the fifth wheel?", "Locking jaws closed with the kingpin enclosed", ["Jaws open", "Kingpin visible outside the jaws", "No grease anywhere"], "The Class 1 inspection checks locking jaws closed and kingpin enclosed."],
    ["coupling", "Ch. 3 — Additional items for Class 1", "Before driving away with a coupled trailer, the landing gear should be…", "Fully raised with the handle secured", ["Lowered to the ground", "Half raised", "Removed"], "Landing gear raised, handle secured."],
    ["braking", "Ch. 4 — Class 1 braking", "Unbalanced braking between tractor and trailer can cause…", "A jackknife", ["Better stability", "Lower fuel use", "Less tire wear"], "Using the trailer brake alone or unevenly adjusted brakes unbalance braking."],
    ["reversing", "Ch. 5 — Reversing a Class 1 vehicle", "To move a semi-trailer's rear to the left while reversing, you turn the steering wheel…", "To the right (opposite to where you want the trailer to go)", ["To the left", "Straight", "It does not matter"], "When reversing a semi-trailer, steer opposite to the trailer's intended direction."],
    ["licensing", "Ch. 1 — Class 1 Road Test", "What happens if a driver completes the Class 1 road test in an automatic?", "A condition code restricts them to automatic transmission commercial trucks until a manual road test is passed", ["Nothing", "They must retake C1LP", "They receive a restricted Class 3"], "A second condensed road test in a manual removes the condition code."],
    ["space", "Ch. 4 — Following distance", "Why do double and triple trailer units need more following distance?", "They are longer and cannot turn or stop as quickly", ["They have better brakes", "They are always lighter", "They travel slower by law"], "Long combination vehicles take up more space and need more room."],
    ["lcv", "Ch. 6 — Operating long combination vehicles", "What maximum speed applies to long combination vehicles in the guide?", "100 km/h or the posted limit, whichever is lower", ["110 km/h", "80 km/h", "The posted limit plus 10"], "LCV maximum speed per the guide."],
  ]),
];

const class1Modules: AcademyModuleSeed[] = [
  mod("C1-01", "The official Class 1 Learning Pathway", "pathway", 25, C1LP, "Class 1 Learning Pathway — tiers", [boundaryBlock("C1-01-0"), block("C1-01-A", "lesson", "Four tiers", "Tier 1 Entry (40 h). Tier 2 Core Learning (67 h from 2026-09-01). Road test → provincially restricted Class 1 (Alberta only). Tier 3 Competence Building (10–18 h from 2026-09-01) removes the restriction. Tier 4 advanced training.", "An 8-hour air brake course is required if you do not already have Q."), block("C1-01-B", "callout", "What LeaseOS does here", "Explains the pathway, links the official LMS and licensed schools, records the progress you report, and offers supplementary study and company mentoring. It does not replace the provincial program or a licensed driver training school.")]),
  mod("C1-02", "Restricted versus full Class 1", "pathway", 15, C1LP, "Class 1 Learning Pathway — restricted licence", [block("C1-02-A", "lesson", "Why it matters for dispatch", "A provincially restricted Class 1 is recorded on your wallet credential as a restriction. Work that requires interprovincial operation needs the unrestricted licence; LeaseOS dispatch will say so rather than assign it.")]),
  mod("C1-03", "Coupling, uncoupling and inspection", "coupling", 35, CDG, "Ch. 6 — Coupling and uncoupling (Class 1)", [block("C1-03-A", "procedure", "Couple, then prove it", "Tug test and visual check of jaws around the kingpin, lines and electrical connected, landing gear raised and secured.")], { practical: true }),
  mod("C1-04", "Braking, reversing and long combinations", "braking", 30, CDG, "Ch. 4–6 — Class 1 braking; reversing; LCVs", [block("C1-04-A", "lesson", "Balance and space", "Balanced braking prevents jackknife. Reverse by steering opposite to the trailer's path. Long combinations need more space and have their own limits.")], { practical: true }),
];

/* ------------------------------------------------------------------ */
/* Class 4                                                              */
/* ------------------------------------------------------------------ */

const CLASS4_Q = bank("C4", CDG, [
  ["licensing", "Ch. 1 — Class 4", "Which vehicles does Class 4 add beyond Class 5?", "Taxis, ambulances and buses seating up to 24 excluding the operator", ["Tractor-trailers", "Any 3-axle truck", "Buses of any size"], "Class 4 privileges per the guide; a school bus also needs S."],
  ["licensing", "Ch. 1 — Class 4 Road Test", "Since February 1, 2023, is a road test required for Class 4?", "No, but vision requirements and a driver medical report are required", ["Yes, in a bus", "Yes, in an ambulance", "Only for taxis"], "The guide notes the Class 4 road test was removed; vision and medical remain."],
  ["licensing", "Ch. 1 — Medical fitness", "Between ages 45 and 65, how often is a medical report needed to keep a Class 4?", "Every three years", ["Every five years", "Every year", "Never"], "Five-yearly to 45, three-yearly 45–65, yearly after 65."],
  ["emergency_vehicles", "Ch. 6 — Information for Class 4: emergency vehicles", "What is an ambulance, as the guide defines it?", "An emergency vehicle designed to transport injured persons, equipped with rescue or first aid equipment", ["Any vehicle with lights", "A bus with a stretcher", "A taxi used by a hospital"], "Definition from Chapter 1."],
  ["inspection", "Ch. 3 — Further items for Class 4 (ambulances)", "Which item is part of an ambulance inspection?", "Medical equipment stowed and inventory complete", ["Fifth-wheel jaws", "Dump box hinge", "Trailer landing gear"], "The ambulance items include stowed medical equipment and a charged extinguisher."],
  ["passengers", "Ch. 6 — Operating a taxi or ride-for-hire vehicle", "A passenger asks you to exceed the speed limit to catch a flight. What do you do?", "Decline and drive within the law", ["Speed only on highways", "Speed if they pay extra", "Let them drive"], "Professional drivers drive within the law regardless of passenger pressure."],
  ["passengers", "Ch. 7 — Passenger safety", "Before moving off with passengers, what should you confirm?", "Passengers are seated and secured and doors are closed", ["The radio is on", "The fare is paid", "The meter is running"], "Passenger safety before departure."],
  ["rail", "Ch. 5 — Special railway crossing information for buses (Class 2 or 4)", "A Class 4 school bus approaches an uncontrolled crossing. Which lights?", "Hazard lights, not the alternating amber/red lights", ["Alternating red lights", "No lights", "Strobe only"], "Same rule as for Class 2 school buses."],
]);

const class4Modules: AcademyModuleSeed[] = [
  mod("C4-01", "Class 4 privileges and requirements", "licensing", 20, CDG, "Ch. 1 — Class 4", [boundaryBlock("C4-01-0"), block("C4-01-A", "lesson", "What Class 4 covers", "Taxis, ambulances and buses seating up to 24 excluding the operator. No road test since 2023-02-01; vision and medical still apply.")]),
  mod("C4-02", "Ambulances, taxis and passenger safety", "passengers", 25, CDG, "Ch. 6–7 — Class 4 vehicles; transporting people", [block("C4-02-A", "lesson", "Professional conduct", "Drive within the law. Seat and secure passengers before moving. Ambulance inspections include medical equipment stowage.")], { practical: true }),
];

/* ------------------------------------------------------------------ */
/* Company field training (same Academy, company boundary)              */
/* ------------------------------------------------------------------ */

const FIELD = "SRC-COMPANY-FIELD-TEMPLATE";
const COMPANY_FIELD_Q = bank("CFS", FIELD, [
  ["stop_work", "Company — stop-work authority", "Who may stop work that looks unsafe?", "Any worker, without reprisal", ["Only the supervisor", "Only safety staff", "Only the customer"], "Company procedure — every worker holds stop-work authority.", true],
  ["incident", "Company — incident reporting", "When must a near miss be reported?", "Before the end of the shift, through the incident workflow", ["Only if someone was hurt", "At the monthly meeting", "Never — it was a miss"], "Company procedure — near misses are reported the same shift."],
  ["spill", "Company — spill response", "A hose fitting leaks product on the lease. First action?", "Stop the transfer and make it safe within your training, then report", ["Keep pumping to finish the load", "Cover it with gravel", "Leave and report later"], "Stop the source, contain within your training and equipment, escalate."],
  ["signals", "Company — swamper hand signals", "The driver loses sight of the swamper while backing. What happens?", "The driver stops until the swamper is visible again", ["The driver continues slowly", "The swamper shouts louder", "The driver uses the horn and continues"], "Company procedure — no eye contact, no movement.", true],
  ["hoses", "Company — hose handling", "Before disconnecting a hose, what must you confirm?", "Pressure/vacuum is released and valves are in the correct position", ["The truck is running at high idle", "The tank is full", "The customer is present"], "Stored energy in hoses injures people."],
  ["radio", "Company — radio procedures", "On a radio-controlled road, what do you say at each marker?", "Unit, direction, kilometre and loaded/empty", ["Nothing unless asked", "Only your name", "Your ETA to the yard"], "Company radio procedure."],
  ["journey", "Company — journey management", "You will be overdue on a journey plan. What do you do?", "Call in to the journey contact before the check-in time", ["Nothing — keep driving", "Call after you arrive", "Let dispatch notice"], "Journey management relies on check-ins."],
  ["winter", "Company — winter and mountain driving", "Chains are required on a mountain pass. When do you install them?", "At a safe chain-up area before the grade", ["On the grade when you start to slip", "After the summit", "Only if the police stop you"], "Install before you need them."],
  ["hos", "Company — HOS and fatigue awareness", "You are fatigued but still within your hours. What does company policy expect?", "Stop and rest — being within hours is not the same as being fit", ["Keep driving until hours run out", "Drink energy drinks and continue", "Ask the customer"], "Fatigue is a stop-work condition.", true],
  ["pretrip", "Company — pre-trip / post-trip", "Where do you record a defect found on the post-trip?", "On the inspection report and in the LeaseOS defect workflow", ["Nowhere if minor", "On a sticky note", "Only verbally"], "Defects go on the report and to the carrier."],
  ["whmis_site", "Company — WHMIS workplace-specific procedure", "A product in the truck has no workplace label. What do you do?", "Stop using it until it is identified and labelled per the workplace process", ["Use it if you know what it is", "Guess from the smell", "Label it yourself from memory"], "Workplace-specific WHMIS instruction."],
  ["tdg_company", "Company — TDG procedures", "The shipping document does not match the load. What do you do?", "Do not move the load; escalate for correction", ["Correct the document yourself", "Move it and fix later", "Remove the placards"], "Company TDG procedure consistent with the TDG course."],
]);

const companyFieldModules: AcademyModuleSeed[] = [
  mod("CFS-01", "Stop-work, incident reporting and spill response", "stop_work", 30, FIELD, "Company — stop-work; incidents; spills", [block("CFS-01-A", "callout", "Company content", "Company procedures, identified as such. Not regulation. Your employer must review and publish its own version before any company certificate is issued."), block("CFS-01-B", "procedure", "Stop, secure, report", "Anyone may stop unsafe work. Report incidents and near misses the same shift. For spills: stop the source, contain within training, escalate.")], { companySpecific: true }),
  mod("CFS-02", "Swamper hand signals, spotting and backing", "signals", 30, FIELD, "Company — swamper hand signals", [block("CFS-02-A", "procedure", "Eye contact or stop", "Agree signals before moving. The spotter stays visible in the mirror. Lose sight, stop.")], { companySpecific: true, practical: true }),
  mod("CFS-03", "Hose handling and vac/water/hydrovac orientation", "hoses", 30, FIELD, "Company — hose handling; equipment orientation", [block("CFS-03-A", "procedure", "Stored energy", "Release pressure/vacuum, set valves, then disconnect. Equipment operation is a separate practical competency per unit type.")], { companySpecific: true, practical: true }),
  mod("CFS-04", "Radio, journey management, winter/mountain/gravel driving", "radio", 30, FIELD, "Company — radio; journey management; seasonal driving", [block("CFS-04-A", "procedure", "Plan and call in", "Radio markers on lease roads. Journey plans with check-ins. Chain up before grades. Slow for gravel, dust and soft shoulders.")], { companySpecific: true }),
  mod("CFS-05", "Pre/post-trip, HOS/fatigue, WHMIS and TDG company procedures", "pretrip", 30, FIELD, "Company — inspections; fatigue; WHMIS; TDG", [block("CFS-05-A", "lesson", "Company layer on regulated training", "These procedures sit on top of — never in place of — the WHMIS and TDG courses and the trip inspection standard.")], { companySpecific: true }),
];

/* ------------------------------------------------------------------ */
/* Courses                                                              */
/* ------------------------------------------------------------------ */

const policyOf = (count: number) => ({ questionCount: count, passingScorePercent: 80, failOnCriticalMiss: true });
const practiceOf = (bankSize: number) => ({ mockQuestionCount: Math.min(30, bankSize), mockPassingPercent: 83 });

export const STUDY_CENTRE_COURSES: AcademyCourseSeed[] = [
  { code: "AB-COMMERCIAL-FOUNDATION", version: 1, title: "Alberta Commercial Driver Foundation", category: "commercial_driver", jurisdiction: "CA-AB", credentialBoundary: "external_track_only", qualificationCode: "DRIVER_LICENCE_CLASS_3", regulated: false, requiresPractical: false, sourceRef: CDG, policy: policyOf(15), practice: practiceOf(FOUNDATION_Q.length), studyCentre: studyCentre("CA-AB"), modules: foundationModules, questions: FOUNDATION_Q },
  { code: "CLASS3", version: 2, title: "Class 3 Preparation (Alberta)", category: "commercial_driver", jurisdiction: "CA-AB", credentialBoundary: "external_track_only", qualificationCode: "DRIVER_LICENCE_CLASS_3", regulated: true, requiresPractical: true, sourceRef: CDG, policy: policyOf(10), practice: practiceOf(CLASS3_Q.length), studyCentre: studyCentre("CA-AB"), modules: class3Modules, questions: CLASS3_Q },
  { code: "AIRBRAKE-Q", version: 2, title: "Air Brake Q Preparation (study only)", category: "air_brake", jurisdiction: "CA-AB", credentialBoundary: "external_track_only", qualificationCode: "AIR_BRAKE_Q", regulated: true, requiresPractical: true, sourceRef: CDG, policy: policyOf(15), practice: practiceOf(AIRBRAKE_Q.length), studyCentre: studyCentre("CA-AB", `${BOUNDARY} Completion never creates a Q endorsement.`), modules: airBrakeModules, questions: AIRBRAKE_Q },
  { code: "CLASS2", version: 2, title: "Class 2 Preparation (Alberta bus)", category: "commercial_driver", jurisdiction: "CA-AB", credentialBoundary: "external_track_only", qualificationCode: "DRIVER_LICENCE_CLASS_2", regulated: true, requiresPractical: true, sourceRef: CDG, policy: policyOf(10), practice: practiceOf(CLASS2_Q.length), studyCentre: studyCentre("CA-AB"), modules: class2Modules, questions: CLASS2_Q },
  { code: "CLASS1", version: 2, title: "Class 1 Preparation + Learning Pathway tracker (Alberta)", category: "commercial_driver", jurisdiction: "CA-AB", credentialBoundary: "external_track_only", qualificationCode: "DRIVER_LICENCE_CLASS_1", regulated: true, requiresPractical: true, sourceRef: C1LP, policy: policyOf(10), practice: practiceOf(CLASS1_Q.length), studyCentre: studyCentre("CA-AB", `${BOUNDARY} It cannot replace the provincial Class 1 Learning Pathway or a licensed driver training school.`), modules: class1Modules, questions: CLASS1_Q },
  { code: "CLASS4", version: 1, title: "Class 4 Preparation (Alberta)", category: "commercial_driver", jurisdiction: "CA-AB", credentialBoundary: "external_track_only", qualificationCode: "DRIVER_LICENCE_CLASS_4", regulated: true, requiresPractical: false, sourceRef: CDG, policy: policyOf(6), practice: practiceOf(CLASS4_Q.length), studyCentre: studyCentre("CA-AB"), modules: class4Modules, questions: CLASS4_Q },
  { code: "COMPANY-FIELD", version: 1, title: "Company Field Safety & Equipment Procedures", category: "company", jurisdiction: "COMPANY", credentialBoundary: "company_certificate", qualificationCode: "COMPANY_FIELD_COMPETENT", regulated: false, requiresPractical: true, sourceRef: FIELD, policy: policyOf(10), practice: practiceOf(COMPANY_FIELD_Q.length), studyCentre: { track: "company", jurisdiction: "COMPANY", boundaryNotice: "Company training. Knowledge completion is not equipment competency; a separate practical sign-off by an authorized evaluator (never yourself) is required." }, modules: companyFieldModules, questions: COMPANY_FIELD_Q },
];

/* ------------------------------------------------------------------ */
/* Offline copies                                                       */
/* ------------------------------------------------------------------ */

/**
 * May LeaseOS keep an offline copy of this publication? Only when a reviewer
 * has reviewed the source AND confirmed the redistribution basis. A licence
 * the publisher states is necessary, not sufficient — somebody at the company
 * has to have read it. Otherwise the learner opens the official URL.
 */
export function offlineCopyDecision(src: { reviewStatus: string; licenceStatus: string | null; redistributionConfirmedByUserId: number | null }) {
  const blockers: string[] = [];
  if (src.reviewStatus !== "reviewed") blockers.push("Source has not been reviewed");
  if (src.licenceStatus !== "open_licence_stated") blockers.push("No stated licence permitting redistribution");
  if (!src.redistributionConfirmedByUserId) blockers.push("A reviewer has not confirmed the redistribution rights");
  return { permitted: blockers.length === 0, blockers, fallback: blockers.length ? "open_official_source" as const : null };
}
