import { stableHash, type AcademyQuestion, type AssessmentPolicy, type CredentialBoundary } from "./trainingAcademy";
import { STUDY_CENTRE_COURSES, STUDY_LIBRARY_SOURCES } from "./studyCentreCatalog";

export type AcademyContentBlockSeed = { code: string; kind: "lesson" | "callout" | "procedure" | "scenario" | "knowledge_check" | "source_note"; title: string; body: string[] };
export type AcademyModuleSeed = { code: string; title: string; domain: string; minutes: number; practical?: boolean; blocks: AcademyContentBlockSeed[]; sourceRef?: string; sourceSection?: string; companySpecific?: boolean };
export type AcademyCourseSeed = {
  code: string; title: string; category: "whmis" | "tdg" | "erg" | "commercial_driver" | "air_brake" | "load_securement" | "company" | "external_track";
  jurisdiction: string; credentialBoundary: CredentialBoundary; qualificationCode?: string; regulated?: boolean; requiresPractical?: boolean;
  sourceRef?: string; policy: AssessmentPolicy; modules: AcademyModuleSeed[]; questions: AcademyQuestion[];
  /** 0172 — published version. A new number publishes a new version; older attempts stay on theirs. */
  version?: number;
  /** 0172 — practice/mock settings for study tracks. */
  practice?: { mockQuestionCount: number; mockPassingPercent: number };
  /** 0172 — Study Centre grouping and the boundary warning shown on every lesson. */
  studyCentre?: { track: "commercial_driver" | "company" | "external_credential"; jurisdiction: string; boundaryNotice: string };
};
export type AcademySourceSeed = {
  sourceRef: string; authority: string; sourceTier: "authority" | "industry_association" | "vendor" | "unknown"; title: string; sourceUrl: string; jurisdiction: string; edition: string; notes: string;
  /** 0172 — Study Library fields. */
  sourceKind?: "study_source" | "provider_directory" | "regulatory_reference";
  licenceStatus?: "unknown" | "link_only" | "open_licence_stated" | "redistribution_prohibited";
  licenceNote?: string;
  retrievedOn?: string;
  contentHash?: string | null;
  capabilityCodes?: string[];
};

const block = (code: string, kind: AcademyContentBlockSeed["kind"], title: string, ...body: string[]): AcademyContentBlockSeed => ({ code, kind, title, body });
const module = (code: string, title: string, domain: string, minutes: number, blocks: AcademyContentBlockSeed[], practical = false): AcademyModuleSeed => ({ code, title, domain, minutes, blocks, practical });

type Fact = { domain: string; prompt: string; correct: string; wrong: [string, string, string]; explanation: string; critical?: boolean };
function expand(prefix: string, facts: Fact[], variants: number): AcademyQuestion[] {
  const stems = [
    (f: Fact) => f.prompt,
    (f: Fact) => `During field work, ${f.prompt.charAt(0).toLowerCase()}${f.prompt.slice(1)}`,
    (f: Fact) => `Which answer best follows LeaseOS training policy? ${f.prompt}`,
  ];
  const out: AcademyQuestion[] = [];
  facts.forEach((f, i) => {
    for (let v = 0; v < variants; v++) {
      const options = [f.correct, ...f.wrong];
      out.push({ code: `${prefix}-${String(i + 1).padStart(2, "0")}-${v + 1}`, domain: f.domain, prompt: stems[v % stems.length](f), options, correctIndex: 0, explanation: f.explanation, critical: f.critical });
    }
  });
  return out;
}

const whmisFacts: Fact[] = [
  { domain: "roles", prompt: "What should a worker do before using a hazardous product they have not been trained on?", correct: "Stop and obtain the required product/site instruction before use", wrong: ["Use it if the container looks familiar", "Rely on TDG placards instead of workplace training", "Ask a coworker for a guess"], explanation: "WHMIS education must be paired with workplace/product-specific instruction." , critical:true},
  { domain: "labels", prompt: "What is the safest response to a missing or unreadable workplace label?", correct: "Stop use and have the product identified and relabelled through the workplace process", wrong: ["Write the product nickname on tape", "Use the product only outdoors", "Ignore the label if an SDS exists somewhere"], explanation: "A missing label is a hazard-communication failure that must be corrected.", critical:true },
  { domain: "sds", prompt: "What document gives detailed hazard, handling, exposure and emergency information for a hazardous product?", correct: "The current Safety Data Sheet (SDS)", wrong: ["The vehicle registration", "The TDG manifest only", "The driver's abstract"], explanation: "SDS information supports workplace hazard controls." },
  { domain: "sds", prompt: "If an SDS and the actual product label appear inconsistent, what should the worker do?", correct: "Stop and escalate the inconsistency for verification", wrong: ["Choose the less severe warning", "Average the two instructions", "Follow whichever is shorter"], explanation: "Conflicting hazard information must be resolved, not guessed.", critical:true },
  { domain: "pictograms", prompt: "What is the purpose of a WHMIS pictogram?", correct: "To communicate a hazard class/category visually", wrong: ["To certify the product for transport", "To identify the employer that bought it", "To replace all written precautions"], explanation: "Pictograms are one part of workplace hazard communication." },
  { domain: "controls", prompt: "Which control should be chosen from the company's product-specific procedure rather than improvised by the worker?", correct: "Required engineering controls, safe handling steps and PPE", wrong: ["A personal shortcut", "A placard copied from another truck", "A social-media recommendation"], explanation: "Controls must come from the employer's hazard assessment and product/site procedures." },
  { domain: "storage", prompt: "Before storing two hazardous products together, what should be confirmed?", correct: "Compatibility and the company's/SDS storage requirements", wrong: ["That both containers are the same colour", "That both were delivered on the same day", "That both have TDG UN numbers"], explanation: "Chemical compatibility and storage requirements control segregation." },
  { domain: "emergency", prompt: "What should a worker do first when a hazardous product release exceeds their training or equipment?", correct: "Withdraw/secure the area as trained and activate the site emergency process", wrong: ["Attempt cleanup alone", "Move the product without identification", "Search for a different product label"], explanation: "Workers should act within training and escalate beyond it.", critical:true },
  { domain: "exposure", prompt: "Where should a worker look for product-specific first-aid measures after an exposure?", correct: "The current SDS and workplace emergency procedure", wrong: ["The vehicle's maintenance manual", "A TDG placard chart only", "A generic internet forum"], explanation: "The SDS and employer procedure provide product-specific response information." },
  { domain: "labels", prompt: "Can a TDG transport placard replace a WHMIS workplace label where WHMIS labeling is required?", correct: "No; the two systems serve different purposes and requirements", wrong: ["Yes, whenever the class number is visible", "Yes, but only on night shift", "Yes, if the driver knows the product"], explanation: "LeaseOS keeps workplace hazard communication separate from transport marking." },
  { domain: "roles", prompt: "Who is responsible for ensuring workers receive workplace-specific hazardous-product instruction?", correct: "The employer/workplace under the applicable WHMIS/OHS duties", wrong: ["The truck manufacturer", "The fuel card provider", "The road authority"], explanation: "Generic education alone does not replace workplace instruction." },
  { domain: "sds", prompt: "What should LeaseOS do if the SDS version on file cannot be confirmed as the one in use?", correct: "Flag it for review rather than presenting it as verified current information", wrong: ["Mark it current automatically", "Delete all historical SDS records", "Guess from the filename"], explanation: "Source/version uncertainty must remain visible." },
  { domain: "controls", prompt: "What is the role of PPE in WHMIS training?", correct: "Use the PPE required by the hazard assessment/SDS/workplace procedure", wrong: ["Use any PPE that is comfortable", "PPE eliminates the need for training", "PPE is only relevant to TDG"], explanation: "PPE is selected as part of the control strategy." },
  { domain: "waste", prompt: "How should hazardous waste be handled when ordinary supplier labels may no longer describe the worksite waste container?", correct: "Follow the workplace's hazardous-waste identification and training procedure", wrong: ["Remove every identifier", "Use a random TDG label", "Store it with general garbage"], explanation: "Hazardous waste still requires workers to be informed and trained." },
  { domain: "pictograms", prompt: "What should a learner do when they cannot identify a hazard pictogram shown on the product?", correct: "Pause and use the approved WHMIS/SDS reference before handling", wrong: ["Assume it means flammable", "Cover the pictogram", "Ignore it if gloves are available"], explanation: "Unknown hazard communication is a stop-and-verify condition." },
  { domain: "emergency", prompt: "Why does LeaseOS keep site emergency procedures beside WHMIS knowledge?", correct: "Because workers need both hazard information and the workplace-specific action to take", wrong: ["Because an SDS is a dispatch licence", "Because emergency plans replace labels", "Because all products have the same emergency response"], explanation: "Knowledge must connect to site procedures." },
  { domain: "labels", prompt: "A decanted product is moved into a workplace container. What should happen before routine use?", correct: "Apply the required workplace identification/label process and train the worker on it", wrong: ["Leave it unmarked for one shift", "Use the vehicle unit number", "Apply a road placard to the bottle"], explanation: "Secondary workplace containers must remain identifiable under the workplace process." },
  { domain: "sds", prompt: "What should a worker use the SDS handling/storage sections for?", correct: "To support safe handling, storage and incompatibility controls", wrong: ["To calculate payroll", "To choose a driver's licence class", "To approve a disposal invoice"], explanation: "SDS sections inform workplace controls." },
  { domain: "roles", prompt: "What does completion of a LeaseOS WHMIS course prove by itself?", correct: "Completion of that employer training version, not a government driver's credential", wrong: ["A Class 1 driver's licence", "A Q air-brake endorsement", "An H2S Alive certificate"], explanation: "Credential boundaries prevent course completion from manufacturing unrelated credentials." },
  { domain: "controls", prompt: "If the workplace procedure requires ventilation and the ventilation is unavailable, what is the correct action?", correct: "Do not proceed until the required control is restored or an authorized alternative is approved", wrong: ["Wear two pairs of gloves instead", "Open the vehicle window and continue", "Ignore the control for a small amount"], explanation: "Required controls are not optional worker choices.", critical:true },
  { domain: "exposure", prompt: "Why should exposure symptoms or incidents be recorded promptly?", correct: "So the emergency/medical response and safety record use accurate facts and timing", wrong: ["To replace medical assessment", "To create a TDG certificate", "To avoid reviewing the SDS"], explanation: "Accurate contemporaneous records support response and follow-up." },
  { domain: "storage", prompt: "What should happen if a storage location conflicts with the product's approved storage requirements?", correct: "Move only through the authorized safe-handling process or stop and escalate", wrong: ["Leave it and change the inventory name", "Cover the label", "Mark it as non-hazardous"], explanation: "Storage requirements are controlled, not edited around." },
  { domain: "waste", prompt: "What should the AI Secretary do when a worker asks it to identify an unknown waste chemical from a nickname?", correct: "Refuse to guess and request verified product/waste identification", wrong: ["Pick the closest SDS", "Choose the most common product", "Assign a placard from the nickname"], explanation: "LeaseOS does not invent hazardous-product identity.", critical:true },
  { domain: "pictograms", prompt: "Why is pictogram recognition not enough to perform the work?", correct: "The worker still needs label/SDS details and workplace-specific controls", wrong: ["Pictograms are only decorative", "Pictograms apply only to transport", "Pictograms replace all training"], explanation: "Recognition is one layer of a complete WHMIS program." },
  { domain: "roles", prompt: "When a company policy template has not been reviewed for the employer, may LeaseOS issue the company's training certificate from it?", correct: "No; the governing company/source snapshot must be reviewed first", wrong: ["Yes if the quiz score is high", "Yes if the learner is a supervisor", "Yes if the template is older than one year"], explanation: "Certificate issuance is source/version controlled.", critical:true },
];

const tdgFacts: Fact[] = [
  { domain: "classification", prompt: "What should the driver do if the UN number or dangerous-goods classification is uncertain?", correct: "Stop and have the consignor/qualified classifier verify it before relying on transport requirements", wrong: ["Choose the closest class", "Use the product nickname", "Copy the previous load's placard"], explanation: "LeaseOS must never guess classification.", critical:true },
  { domain: "documents", prompt: "Before accepting a dangerous-goods load for road transport, what information should the driver workflow confirm?", correct: "The required shipping-document information for the verified load is present and available", wrong: ["Only the customer name", "Only the destination postal code", "Only a WHMIS pictogram"], explanation: "The transport document and verified load data must agree.", critical:true },
  { domain: "marks", prompt: "What should happen before LeaseOS recommends a final vehicle/container placard?", correct: "Classification and the applicable Part 4 conditions must be verified", wrong: ["Select from the product colour", "Use the most severe placard available", "Copy a workplace label"], explanation: "Placards depend on verified classification and conditions.", critical:true },
  { domain: "containment", prompt: "What is the correct response to leaking or visibly damaged dangerous-goods containment?", correct: "Stop movement/handling as trained and escalate through the emergency/compliance process", wrong: ["Drive faster to the destination", "Add an extra placard and continue", "Cover the leak with paperwork"], explanation: "Damaged containment is a stop-and-escalate condition.", critical:true },
  { domain: "training", prompt: "What does a TDG road training certificate represent in LeaseOS?", correct: "An employer-issued record that the person was adequately trained for the assigned TDG duties", wrong: ["A government Class 1 driver's licence", "An air-brake endorsement", "An ERG guide number"], explanation: "TDG training is tracked separately from driver licensing." },
  { domain: "training", prompt: "When can an untrained person use LeaseOS's TDG direct-supervision pathway?", correct: "Only when a properly qualified person is physically present and the job/time/scope are recorded", wrong: ["When a supervisor watches GPS", "When a supervisor is reachable by phone", "Whenever the app is online"], explanation: "Remote monitoring is not direct supervision.", critical:true },
  { domain: "documents", prompt: "If the shipping document disagrees with the verified load profile, what should the driver do?", correct: "Stop and have the discrepancy corrected/verified before movement", wrong: ["Edit whichever field seems easiest", "Ignore the load profile", "Ignore the shipping document"], explanation: "Conflicting regulated data requires resolution.", critical:true },
  { domain: "marks", prompt: "Can a WHMIS workplace label be substituted for a TDG transport placard?", correct: "No; workplace labels and transport marks are separate systems", wrong: ["Yes for short trips", "Yes within Alberta only", "Yes when the driver has WHMIS"], explanation: "LeaseOS must maintain system boundaries." },
  { domain: "erg", prompt: "What is the ERG used for in the TDG workflow?", correct: "Initial emergency-response guidance after the material is identified as far as safely possible", wrong: ["To classify an unknown product for shipment", "To issue a TDG certificate", "To replace the company emergency plan"], explanation: "The ERG is an initial-response tool, not a classification engine." },
  { domain: "waste", prompt: "Why does LeaseOS keep hazardous-waste paperwork separate from the TDG shipping document?", correct: "They are different regulatory/document workflows that may overlap but are not interchangeable", wrong: ["Waste is never dangerous goods", "TDG never applies to waste", "Both documents are always identical"], explanation: "Waste and TDG duties can overlap without becoming one document." },
  { domain: "classification", prompt: "Who should supply or verify classification data rather than leaving the driver to infer it?", correct: "The party responsible for classification/consignor workflow using authoritative information", wrong: ["The fuel-card vendor", "A random receiver", "The navigation app"], explanation: "Drivers and AI should not improvise classification." },
  { domain: "documents", prompt: "What should LeaseOS preserve when a document is corrected?", correct: "The correction/audit history rather than silently overwriting the prior fact", wrong: ["Only the newest value with no history", "A screenshot without context", "Nothing once the trip ends"], explanation: "Append-only correction evidence supports auditability." },
  { domain: "marks", prompt: "What should a pre-departure mark check verify?", correct: "Required marks are appropriate to the verified load and visible/legible/conditioned as required", wrong: ["Every possible placard is displayed", "The placard matches the truck colour", "The WHMIS label is on the cab door"], explanation: "Mark checks are load- and rule-specific." },
  { domain: "containment", prompt: "If the means of containment is not approved/appropriate for the verified load, what should happen?", correct: "Block movement until the containment issue is resolved by a qualified person", wrong: ["Reduce speed", "Add a second shipping document", "Ask the driver to accept responsibility"], explanation: "Containment suitability is a safety prerequisite.", critical:true },
  { domain: "training", prompt: "What should happen when a TDG certificate expires?", correct: "The qualification becomes non-current and dangerous-goods dispatch is blocked unless a valid pathway applies", wrong: ["The app extends it automatically", "WHMIS replaces it", "The driver signs a waiver"], explanation: "Expiry is enforced as a qualification state." },
  { domain: "emergency", prompt: "What should the driver do when an incident exceeds the ERG/company procedure and their training?", correct: "Protect themselves/public as trained and escalate to emergency services/CANUTEC/company response", wrong: ["Experiment with containment", "Wait for the app to classify the leak", "Continue transport"], explanation: "Escalation is part of emergency competence.", critical:true },
  { domain: "documents", prompt: "Where should the AI Secretary get the proper shipping name it displays?", correct: "From the verified load/classification record or authoritative source snapshot", wrong: ["From a colloquial product nickname", "From an unrelated SDS title", "From the destination name"], explanation: "Transport identity must be source-backed." },
  { domain: "marks", prompt: "What should LeaseOS do if quantity/containment details needed to decide placarding are missing?", correct: "Return needs-review/block and request the missing verified facts", wrong: ["Default to no placard", "Default to Class 3", "Reuse the last trip"], explanation: "The system fails closed when decisive inputs are unknown.", critical:true },
  { domain: "waste", prompt: "What should happen if a load is both dangerous goods and regulated waste?", correct: "Run both applicable workflows and keep each required record distinct", wrong: ["Choose only the waste workflow", "Choose only TDG", "Use a WHMIS label as both documents"], explanation: "Overlapping regimes are evaluated independently." },
  { domain: "erg", prompt: "What identifier should normally drive a yellow-section ERG lookup when it is verified?", correct: "The UN/NA identification number", wrong: ["The driver's unit number", "The invoice number", "The customer PO"], explanation: "The numeric index is keyed by material identification number." },
  { domain: "erg", prompt: "What identifier drives a blue-section ERG lookup?", correct: "The verified material name", wrong: ["The driver's surname", "The road name", "The trailer plate"], explanation: "The blue index is material-name based." },
  { domain: "training", prompt: "Can LeaseOS's TDG course be used to issue an aviation dangerous-goods certificate?", correct: "No; the course/version scope is road TDG and cannot be relabelled as an air certificate", wrong: ["Yes if the score is 100%", "Yes for company aircraft", "Yes when the worker has WHMIS"], explanation: "Certificates are scoped to the training actually delivered.", critical:true },
  { domain: "classification", prompt: "What should a driver do when a material name is ambiguous between multiple regulated products?", correct: "Escalate for exact identification/classification before transport", wrong: ["Pick the first search result", "Choose the lower-risk class", "Use the waste code as the UN number"], explanation: "Ambiguity is not resolved by guessing.", critical:true },
  { domain: "emergency", prompt: "What facts should the driver be ready to communicate during a dangerous-goods emergency?", correct: "Verified identification, location, condition of the load and observable incident facts", wrong: ["A guessed chemical formula", "Unverified blame", "Only the delivery price"], explanation: "Accurate facts support emergency responders." },
  { domain: "documents", prompt: "What is the safest system response if the TDG source snapshot is unreviewed?", correct: "Allow study/reference but prevent certificate issuance or legal-clearance claims", wrong: ["Issue certificates anyway", "Mark the source reviewed automatically", "Hide the source status"], explanation: "Governance keeps unreviewed source content from becoming authority.", critical:true },
];

const ergFacts: Fact[] = [
  { domain: "purpose", prompt: "What is the ERG designed to support?", correct: "Initial actions during the early phase of a transportation incident involving dangerous goods", wrong: ["Routine product classification for shipping", "Driver licensing", "Long-term remediation design"], explanation: "ERG guidance is for initial response." },
  { domain: "yellow", prompt: "Which ERG section is used to look up a verified UN/NA number?", correct: "Yellow index", wrong: ["Blue index", "Orange guides", "Green tables"], explanation: "Yellow is identification-number indexed." },
  { domain: "blue", prompt: "Which ERG section is used to look up a verified material name?", correct: "Blue index", wrong: ["Yellow index", "Green tables", "White cover only"], explanation: "Blue is material-name indexed." },
  { domain: "orange", prompt: "What do orange guide pages provide?", correct: "Potential hazards, public-safety guidance and emergency-response actions for the guide", wrong: ["Driver qualification records", "Waste manifest numbers", "Licence restrictions"], explanation: "Orange pages contain the response guide information." },
  { domain: "green", prompt: "What is the green section used for when a material is listed for protective-action information?", correct: "Initial isolation/protective-action distance information within the ERG context", wrong: ["Calculating tiedown WLL", "Issuing placards", "Finding payroll rates"], explanation: "Green tables supplement certain orange-guide materials." },
  { domain: "identification", prompt: "What should a driver do if the material cannot be safely identified?", correct: "Do not guess; use the ERG identification aids and escalate to responders/CANUTEC from a safe position", wrong: ["Approach the leak to read a damaged label", "Pick a guide at random", "Assume the most common fuel"], explanation: "Personal safety and verified identification come first.", critical:true },
  { domain: "purpose", prompt: "Does an ERG guide replace the company's site emergency response plan?", correct: "No; it supports initial response and escalation, not replacement of the employer plan", wrong: ["Yes for all highway incidents", "Yes whenever CANUTEC is busy", "Yes if the driver has TDG"], explanation: "ERG and company procedures are complementary." },
  { domain: "orange", prompt: "If two identification methods point to different ERG guide numbers, what should happen?", correct: "Treat the conflict as unresolved and verify the material/guide before relying on it", wrong: ["Choose the lower number", "Choose the higher number", "Average the guide numbers"], explanation: "Conflicting lookup results are a review condition.", critical:true },
  { domain: "green", prompt: "What environmental detail is important when protective-action distances are being considered?", correct: "Wind direction and the table/context stated by the ERG", wrong: ["Vehicle paint colour", "Invoice age", "Driver seniority"], explanation: "Protective actions are context-sensitive." },
  { domain: "canutec", prompt: "When should CANUTEC/company emergency contacts be escalated?", correct: "When the incident requires dangerous-goods technical/emergency support under the response procedure", wrong: ["Only after the delivery is complete", "Only for payroll questions", "Never if the ERG is available"], explanation: "Technical support complements ERG use." },
  { domain: "identification", prompt: "What should LeaseOS display beside an ERG result to reduce misuse?", correct: "The verified identifier/material and the guide source/version used", wrong: ["Only the guide number with no context", "A guessed product nickname", "A placard chosen by colour"], explanation: "Traceability prevents silent mismatches." },
  { domain: "yellow", prompt: "What should happen before a yellow-index lookup is trusted?", correct: "Confirm the UN/NA number came from verified load/incident information", wrong: ["Convert the invoice number into a UN number", "Use the unit number", "Use the route number"], explanation: "A precise lookup still fails if its identifier is wrong." },
  { domain: "blue", prompt: "If a material has several similar names, what should the learner do?", correct: "Cross-check against the verified transport identity rather than selecting by similarity", wrong: ["Pick the shortest name", "Pick the first alphabetically", "Use any result with the same colour"], explanation: "Name ambiguity must be resolved." },
  { domain: "orange", prompt: "What kind of information should be read before taking an action from an orange guide?", correct: "Hazards, public safety and the applicable emergency-response section", wrong: ["Only the guide title", "Only the fire section", "Only the first sentence"], explanation: "The guide is structured; actions need context." },
  { domain: "green", prompt: "Should a driver invent an isolation distance when the material is not covered by the green table?", correct: "No; use the applicable guide and qualified emergency support rather than inventing a distance", wrong: ["Yes, double the vehicle length", "Yes, use 100 metres for everything", "Yes, copy the previous incident"], explanation: "The system must not fabricate safety distances.", critical:true },
  { domain: "purpose", prompt: "What does completing the ERG knowledge course prove?", correct: "The learner completed that knowledge version; it is not itself a TDG certificate or emergency-responder qualification", wrong: ["A Class 1 licence", "A TDG road certificate", "A firefighter credential"], explanation: "Knowledge-only courses do not create external credentials." },
  { domain: "canutec", prompt: "What should be recorded when CANUTEC or company emergency support is contacted through LeaseOS?", correct: "Time, incident/load identifiers, contact path and relevant guidance/decision record", wrong: ["Only the driver's first name", "Nothing if advice is verbal", "Only the GPS speed"], explanation: "Traceable emergency communications support incident review." },
  { domain: "identification", prompt: "Why does LeaseOS keep ERG lookup separate from product classification?", correct: "ERG helps respond to an identified/partly identified incident; it is not a shipping classification authority", wrong: ["Because the ERG is only for payroll", "Because classification is optional", "Because placards replace classification"], explanation: "Response and classification are different functions." },
  { domain: "yellow", prompt: "A verified UN number maps to a guide. What should the learner still confirm?", correct: "That the guide is from the current configured ERG edition and matches the verified identifier", wrong: ["That the truck is the same colour", "That the customer has paid", "That the driver used the guide before"], explanation: "Edition and identifier traceability matter." },
  { domain: "blue", prompt: "When is a blue-index lookup especially useful?", correct: "When the verified material name is known and the identification number is not immediately being used", wrong: ["When choosing a driver's licence", "When setting tire pressure", "When calculating GST"], explanation: "The blue index is keyed by name." },
  { domain: "orange", prompt: "What should the AI Secretary avoid doing with orange-guide text?", correct: "Presenting it as a substitute for trained emergency judgment or site command", wrong: ["Showing the guide number", "Linking it to the verified material", "Recording which edition was used"], explanation: "The assistant supports, not replaces, emergency command." },
  { domain: "green", prompt: "Why must protective-action information be shown with its context?", correct: "Distances depend on material/table conditions and cannot be treated as a universal radius", wrong: ["Because all distances are optional", "Because only dispatch can see distances", "Because placards determine payroll"], explanation: "Context prevents misuse." },
  { domain: "canutec", prompt: "If the app is offline during an incident, what should the driver rely on?", correct: "The offline emergency package/ERG and the company's established emergency communication procedure", wrong: ["Wait for internet before acting", "Guess the material", "Continue driving until coverage returns"], explanation: "Emergency readiness must survive dead zones.", critical:true },
  { domain: "identification", prompt: "What is the safest way to handle an unreadable placard at an incident?", correct: "Do not approach solely to read it; use safe identification clues and responder/CANUTEC escalation", wrong: ["Walk into the vapour cloud", "Assume Class 3", "Remove the placard"], explanation: "Identification must not create additional exposure.", critical:true },
  { domain: "purpose", prompt: "What audit fact should every LeaseOS ERG drill preserve?", correct: "Which ERG edition, scenario identifier and learner response were used", wrong: ["Only whether the screen was opened", "Only the employee number", "Only the final score with no version"], explanation: "Versioned scenario evidence makes training reproducible." },
];

export const WHMIS_QUESTION_BANK = expand("WHMIS", whmisFacts, 2); // 25 x 2 = 50
export const TDG_QUESTION_BANK = expand("TDG", tdgFacts, 3); // 25 x 3 = 75
export const ERG_QUESTION_BANK = expand("ERG", ergFacts, 1); // 25

export const ACADEMY_SOURCES: AcademySourceSeed[] = [
  { sourceRef: "SRC-WHMIS-AB-2026", authority: "Alberta OHS / CCOHS", sourceTier: "authority", title: "WHMIS employer education and workplace-specific training source set", sourceUrl: "https://www.alberta.ca/whmis", jurisdiction: "CA-AB", edition: "review-required snapshot 2026-09", notes: "Seeded unreviewed. A safety/authorized reviewer must review the company's governing snapshot before LeaseOS may issue the employer certificate." },
  { sourceRef: "SRC-TDG-ROAD-2026", authority: "Transport Canada", sourceTier: "authority", title: "TDG road training / documentation / dangerous-goods marks source set", sourceUrl: "https://tc.canada.ca/en/dangerous-goods", jurisdiction: "CA", edition: "review-required snapshot 2026-09", notes: "Road scope only. Does not authorize air/marine training certificates." },
  { sourceRef: "SRC-ERG-2024", authority: "Transport Canada CANUTEC", sourceTier: "authority", title: "Emergency Response Guidebook 2024", sourceUrl: "https://tc.canada.ca/en/dangerous-goods/canutec/emergency-response-guidebook", jurisdiction: "CA", edition: "ERG 2024", notes: "Knowledge/reference source; ERG course remains knowledge-only." },
  ...STUDY_LIBRARY_SOURCES,
  { sourceRef: "SRC-COMPANY-POLICY-TEMPLATE", authority: "Employer", sourceTier: "authority", title: "Company policy template — requires company review before certification", sourceUrl: "internal://leaseos/academy/company-policy-template", jurisdiction: "COMPANY", edition: "template-1", notes: "May be studied/edited. Cannot govern certificate issuance until reviewed for the employer." },
];

const whmisModules = [
  module("WHMIS-01", "WHMIS system, roles and credential boundary", "roles", 20, [
    block("WHMIS-01-A", "lesson", "What this course does", "This is employer-delivered WHMIS education plus a framework for workplace-specific instruction.", "It does not create a driver's licence, air-brake endorsement, H2S Alive or First Aid credential."),
    block("WHMIS-01-B", "callout", "Stop-and-verify rule", "If product identity, label information, SDS version or required controls conflict, stop and escalate. The AI Secretary must not guess."),
  ]),
  module("WHMIS-02", "Pictograms, labels and product identity", "labels", 25, [
    block("WHMIS-02-A", "lesson", "Labels are operational information", "Learn supplier/workplace label elements and the workplace process for secondary containers.", "TDG transport marks are not a substitute for workplace labels."),
    block("WHMIS-02-B", "scenario", "Unreadable label", "Treat missing/unreadable identification as a work stop until the product is identified and the workplace process restores the required label/information."),
  ]),
  module("WHMIS-03", "Safety Data Sheets", "sds", 30, [
    block("WHMIS-03-A", "lesson", "Using the current SDS", "Locate hazards, first aid, fire response, accidental release, handling/storage, exposure controls and PPE.", "LeaseOS should display source/version status beside an SDS reference."),
    block("WHMIS-03-B", "procedure", "Conflict handling", "If the SDS, label, workplace procedure or actual product identity disagree, preserve the discrepancy and escalate for review rather than silently editing one value."),
  ]),
  module("WHMIS-04", "Controls, PPE, storage and exposure", "controls", 30, [
    block("WHMIS-04-A", "lesson", "Work within approved controls", "Use the employer's hazard assessment, product-specific procedures and current SDS to determine engineering controls, safe handling and PPE."),
    block("WHMIS-04-B", "scenario", "Required control unavailable", "Do not substitute an improvised control. Stop until the required control is restored or an authorized alternative is approved."),
  ], true),
  module("WHMIS-05", "Spills, emergencies and hazardous waste", "emergency", 25, [
    block("WHMIS-05-A", "lesson", "Know the boundary of your response", "Follow the company spill/exposure procedure, emergency contacts and evacuation/isolation directions.", "When the event exceeds training/equipment, withdraw and escalate."),
    block("WHMIS-05-B", "lesson", "Hazardous waste", "The workplace still needs a clear hazardous-waste identification/instruction process; transport/waste manifests remain separate compliance workflows."),
  ], true),
];

const tdgModules = [
  module("TDG-01", "TDG roles, road scope and training certificate", "training", 30, [block("TDG-01-A", "lesson", "Road scope only", "The LeaseOS TDG course is configured for road duties. It cannot be relabelled as an air certificate.", "Certificate issuance remains employer-controlled and versioned."), block("TDG-01-B", "callout", "Direct supervision", "A trainee pathway requires a qualified supervisor physically present, on a specific job/time/scope. Phone, GPS, camera or app monitoring alone is not direct supervision.")]),
  module("TDG-02", "Classification literacy and stop-work boundary", "classification", 35, [block("TDG-02-A", "lesson", "Read, do not invent", "Learn to read verified UN number, proper shipping name, class and packing group.", "Classification uncertainty is returned to the responsible consignor/qualified classifier."), block("TDG-02-B", "scenario", "Nickname-only load", "A product nickname is not enough to select a UN number, class or placard. LeaseOS must request verified identity.")]),
  module("TDG-03", "Shipping documents and custody", "documents", 35, [block("TDG-03-A", "procedure", "Pre-acceptance document check", "Compare the shipping document with the verified load record. Missing or conflicting regulated fields block/review movement."), block("TDG-03-B", "lesson", "Corrections remain visible", "Corrections are append-only/audited; do not erase what the driver originally received.")], true),
  module("TDG-04", "Labels, placards, UN numbers and marks", "marks", 40, [block("TDG-04-A", "lesson", "Marks follow verified facts", "Learn the class-mark families and the distinction between labels, placards and supplementary marks.", "Final vehicle/container marking depends on verified classification, quantity, containment and applicable rule."), block("TDG-04-B", "scenario", "Incomplete inputs", "When a fact needed for the marking decision is unknown, the assistant returns review/block—not a guessed placard.")], true),
  module("TDG-05", "Containment and handling", "containment", 30, [block("TDG-05-A", "lesson", "Containment is a prerequisite", "Recognize damage, leaks and incompatibility as stop-and-escalate conditions.", "Do not turn a containment problem into a paperwork workaround.")], true),
  module("TDG-06", "ERG, CANUTEC and incident escalation", "erg", 35, [block("TDG-06-A", "lesson", "ERG integration", "Use verified UN/material identity to reach the appropriate ERG index/guide. ERG supports initial response; it does not classify the shipment."), block("TDG-06-B", "procedure", "Escalation", "Preserve location, verified identity and observable incident facts; contact emergency services/CANUTEC/company response as the plan requires.")], true),
  module("TDG-07", "Waste overlap and Alberta workflows", "waste", 25, [block("TDG-07-A", "lesson", "Two workflows can apply", "Dangerous goods and hazardous waste are evaluated independently. A waste manifest/docket does not replace the TDG shipping document, and vice versa."), block("TDG-07-B", "callout", "Oilfield waste", "Use the configured Alberta oilfield-waste routing rules; do not force every waste load into one generic manifest workflow.")]),
  module("TDG-08", "Job-specific practical competency", "training", 40, [block("TDG-08-A", "procedure", "Observed practical", "A qualified evaluator observes the learner complete the employer's real load-document-marking workflow and stop-work decisions.", "Passing the online quiz alone does not prove practical competence.")], true),
];

const ergModules = [
  module("ERG-01", "ERG purpose, limits and safe identification", "purpose", 20, [block("ERG-01-A", "lesson", "Initial response", "ERG 2024 supports the first phase of a transport incident. It is not a shipping-classification engine or a replacement for incident command."), block("ERG-01-B", "callout", "Do not approach to identify", "If identification cannot be made safely, withdraw and use safe clues plus responder/CANUTEC support.")]),
  module("ERG-02", "Yellow and blue indexes", "identification", 20, [block("ERG-02-A", "lesson", "Two lookup paths", "Yellow: verified UN/NA identification number. Blue: verified material name.", "If lookup paths conflict, stop and verify the identity.")], true),
  module("ERG-03", "Orange guides", "orange", 20, [block("ERG-03-A", "lesson", "Read the whole guide context", "Review potential hazards, public safety and emergency response sections before acting.", "LeaseOS records the guide and ERG edition used in a drill/incident workflow.")], true),
  module("ERG-04", "Green tables and protective action", "green", 20, [block("ERG-04-A", "lesson", "Context matters", "Protective-action distances apply only in the ERG conditions for listed materials. Do not invent a radius when the table does not provide one.")], true),
  module("ERG-05", "CANUTEC and company emergency package", "canutec", 20, [block("ERG-05-A", "procedure", "Escalate with facts", "Be ready with verified identification, location, containment/load condition and observable incident facts.", "Dead-zone operation should fall back to the offline ERG/company emergency package rather than waiting for connectivity.")], true),
];

function genericTrack(code: string, title: string, category: AcademyCourseSeed["category"], qualificationCode: string, modules: string[]): AcademyCourseSeed {
  return { code, title, category, jurisdiction: "CA-AB", credentialBoundary: "external_track_only", qualificationCode, regulated: true, requiresPractical: true, sourceRef: "SRC-COMPANY-POLICY-TEMPLATE", policy: { questionCount: 1, passingScorePercent: 80 }, modules: modules.map((m, i) => module(`${code}-${i + 1}`, m, "knowledge", 20, [block(`${code}-${i + 1}-A`, "lesson", m, `LeaseOS tracks learning and employer competency for ${m}.`, "The actual external licence/endorsement/certificate must be verified separately before dispatch relies on it." )], true)), questions: [{ code: `${code}-TRACK-01`, domain: "knowledge", prompt: `Does completion of this LeaseOS ${title} track create the external credential?`, options: ["No; the external credential must be obtained and verified through the proper issuer", "Yes, automatically", "Yes, after supervisor verbal approval", "Yes, if completed offline"], correctIndex: 0, explanation: "External credentials remain track-only in LeaseOS.", critical: true }] };
}

export const ACADEMY_COURSES: AcademyCourseSeed[] = [
  { code: "WHMIS-AB", title: "WHMIS · Alberta Worker + Workplace", category: "whmis", jurisdiction: "CA-AB", credentialBoundary: "employer_certificate", qualificationCode: "WHMIS_EMPLOYER", regulated: true, requiresPractical: true, sourceRef: "SRC-WHMIS-AB-2026", policy: { questionCount: 25, passingScorePercent: 80, domainMinimumPercent: { roles: 60, labels: 70, sds: 70, controls: 70, emergency: 70 }, failOnCriticalMiss: true, maxAttempts: 3 }, modules: whmisModules, questions: WHMIS_QUESTION_BANK },
  { code: "TDG-ROAD", title: "Transportation of Dangerous Goods · Road", category: "tdg", jurisdiction: "CA", credentialBoundary: "employer_certificate", qualificationCode: "TDG_ROAD", regulated: true, requiresPractical: true, sourceRef: "SRC-TDG-ROAD-2026", policy: { questionCount: 30, passingScorePercent: 80, domainMinimumPercent: { classification: 70, documents: 70, marks: 70, training: 70 }, failOnCriticalMiss: true, maxAttempts: 3 }, modules: tdgModules, questions: TDG_QUESTION_BANK },
  { code: "ERG-2024", title: "Emergency Response Guidebook 2024", category: "erg", jurisdiction: "CA", credentialBoundary: "knowledge_only", qualificationCode: "ERG_KNOWLEDGE", regulated: false, requiresPractical: false, sourceRef: "SRC-ERG-2024", policy: { questionCount: 15, passingScorePercent: 80, failOnCriticalMiss: true, maxAttempts: 5 }, modules: ergModules, questions: ERG_QUESTION_BANK },
  { code: "LOAD-SECUREMENT", title: "Commercial Load Securement · Company Competency", category: "load_securement", jurisdiction: "CA", credentialBoundary: "company_certificate", qualificationCode: "LOAD_SECUREMENT_COMPETENT", requiresPractical: true, sourceRef: "SRC-COMPANY-POLICY-TEMPLATE", policy: { questionCount: 1, passingScorePercent: 100, failOnCriticalMiss: true }, modules: [module("SEC-01", "General securement principles, WLL and damaged equipment", "securement", 30, [block("SEC-01-A", "lesson", "General rule plus commodity rules", "LeaseOS may calculate a configured general WLL check, but a commodity-specific rule remains a separate gate.", "Damaged/unmarked tiedowns and unsuitable anchor points are rejected rather than credited.")], true), module("SEC-02", "Commodity-specific securement and inspections", "securement", 30, [block("SEC-02-A", "scenario", "Do not overgeneralize", "Pipe, logs, heavy equipment, vehicles, coils and other commodities may have specific requirements. The AI Secretary identifies the rule family from verified load type and asks for qualified confirmation.")], true)], questions: [{ code: "SEC-01", domain: "securement", prompt: "If a commodity-specific securement rule applies, may the general aggregate-WLL calculation alone clear the load?", options: ["No; the commodity-specific method must also be checked", "Yes", "Only at night", "Only on private roads"], correctIndex: 0, explanation: "Commodity-specific requirements remain an independent gate.", critical: true }] },
  { code: "COMPANY-CORE", title: "Company / Site / Customer Orientation", category: "company", jurisdiction: "COMPANY", credentialBoundary: "company_certificate", qualificationCode: "COMPANY_CORE", requiresPractical: false, sourceRef: "SRC-COMPANY-POLICY-TEMPLATE", policy: { questionCount: 1, passingScorePercent: 100 }, modules: [module("COMP-01", "Company policies, ERP, stop-work and reporting", "company", 30, [block("COMP-01-A", "lesson", "Company-specific by design", "This course is a template until the employer reviews and publishes its own policy snapshot.", "The Academy may let workers study a draft, but certificate issuance remains blocked until the governing source is reviewed.")])], questions: [{ code: "COMP-01", domain: "company", prompt: "May LeaseOS issue a company certificate from an unreviewed generic policy template?", options: ["No; the employer's governing source snapshot must be reviewed", "Yes after any quiz", "Yes for managers", "Yes when offline"], correctIndex: 0, explanation: "Company certificates are version/source controlled.", critical: true }] },
  // 0172 — CLASS1/2/3 and AIRBRAKE-Q were one-question placeholders at version 1; they are now
  // versioned Study Centre tracks (version 2) with source-grounded modules and original practice banks.
  // Version 1 stays in the database with its attempts; synchronizeCatalog publishes version 2 beside it.
  ...STUDY_CENTRE_COURSES,
  genericTrack("H2S-TRACK", "H2S Alive external credential tracking", "external_track", "H2S_ALIVE", ["Company H2S awareness and external-certificate boundary"]),
  genericTrack("FIRSTAID-TRACK", "First Aid external credential tracking", "external_track", "FIRST_AID", ["Company first-aid response roles and external-certificate boundary"]),
];

export const ACADEMY_REQUIREMENT_SEEDS = [
  { code: "REQ-TDG-ROAD", title: "Current TDG road qualification", qualificationCode: "TDG_ROAD", enforcement: "block" as const, recoveryPath: "Complete/verify current TDG road training or use an explicitly valid physical direct-supervision record." },
  { code: "REQ-WHMIS-WORK", title: "Current WHMIS employer training", qualificationCode: "WHMIS_EMPLOYER", enforcement: "block" as const, recoveryPath: "Complete the employer's current WHMIS version and workplace-specific instruction." },
  { code: "REQ-LOAD-SECUREMENT", title: "Load securement competency", qualificationCode: "LOAD_SECUREMENT_COMPETENT", enforcement: "block" as const, recoveryPath: "Complete current theory plus supervisor practical sign-off." },
  { code: "REQ-CLASS1", title: "Verified Class 1 licence", qualificationCode: "DRIVER_LICENCE_CLASS_1", enforcement: "block" as const, recoveryPath: "Verify the external driver licence; Academy completion alone cannot satisfy this requirement." },
  { code: "REQ-Q", title: "Verified air-brake Q endorsement", qualificationCode: "AIR_BRAKE_Q", enforcement: "block" as const, recoveryPath: "Verify the external Q endorsement; LeaseOS preparation cannot issue it." },
];

export const CATALOG_COUNTS = {
  courses: ACADEMY_COURSES.length,
  whmisQuestions: WHMIS_QUESTION_BANK.length,
  tdgQuestions: TDG_QUESTION_BANK.length,
  ergQuestions: ERG_QUESTION_BANK.length,
  totalQuestions: ACADEMY_COURSES.reduce((n, c) => n + c.questions.length, 0),
  contentBlocks: ACADEMY_COURSES.reduce((n, c) => n + c.modules.reduce((m, x) => m + x.blocks.length, 0), 0),
};

if (CATALOG_COUNTS.whmisQuestions !== 50 || CATALOG_COUNTS.tdgQuestions !== 75 || CATALOG_COUNTS.ergQuestions !== 25) throw new Error(`Academy bank size drift: ${JSON.stringify(CATALOG_COUNTS)}`);

export function courseSeedHash(course: AcademyCourseSeed) { return stableHash({ ...course, questions: course.questions.map(q => q.code) }); }
