/**
 * B23 — the board service.
 *
 * No tRPC, no drizzle, no React. Takes a store and a reader as arguments, so
 * every rule below is testable without a database and the router over it stays
 * thin enough to be read in one screen.
 *
 * The shape is deliberate. `widgetsRouter.ts` cannot be verified in a container
 * without the branch, so nothing that matters lives in it: it resolves the
 * acting scope, calls one function here, returns. Everything worth a test is
 * here or further down in the pure core.
 */

import { presentTile } from "../../client/src/widgets/tilePresentation";
import {
  planBoard, runBoard, offerableWidgets,
  type LayoutItem, type ResolveContext, type ResolveTask, type TileResult,
} from "./widgetDashboard";
import {
  defaultBoardFor, prepareLayoutSave,
  type DeviceClass, type LayoutSaveRequest, type NamedRejection, type NormalizedItem, type WriteContext,
} from "./widgetLayoutWrite";
import { definitionFor, type WidgetKey } from "./widgetRegistry";
import { contextFor, type RoleActor } from "./roleActor";
import type { NamedBlocker, WidgetPayload } from "./widgetPayload";

/* ------------------------------------------------------------------ */
/* Ports                                                               */
/* ------------------------------------------------------------------ */

export type StoredLayout = {
  /** External reference. Null on a create, where the store assigns one. */
  layoutRef: string;
  userId: number;
  roleKey: string;
  deviceClass: DeviceClass;
  name: string;
  isDefault: boolean;
  /** Bumped by the store on every authoritative write. Absent on a create. */
  revision?: number;
};

/**
 * What the service needs from persistence, and nothing more.
 *
 * `saveLayout` is one call rather than a write plus an unset, because "only one
 * default" has to happen inside a single transaction and an interface that
 * exposed two calls would let a caller do half of it.
 */
export type WidgetLayoutStore = {
  findLayout(q: {
    userId: number; roleKey: string; deviceClass: DeviceClass; layoutRef?: string;
  }): Promise<{ layout: StoredLayout; items: readonly LayoutItem[] } | null>;

  /**
   * Insert a new layout. The reference is generated by the store, never taken
   * from the client — a client that chooses its own reference is a client that
   * can choose somebody else's.
   */
  createLayout(
    layout: Omit<StoredLayout, "layoutRef"> & { layoutRef: null },
    items: readonly NormalizedItem[],
    unsetOtherDefaults: boolean,
  ): Promise<{ layoutRef: string }>;

  /**
   * Update an existing layout, but only if it belongs to this user, role,
   * device and tenant. Resolves ownership inside the transaction, before a
   * single item row is touched, and fails closed.
   */
  updateOwnedLayout(
    layout: StoredLayout,
    items: readonly NormalizedItem[],
    unsetOtherDefaults: boolean,
    tenantId: string,
    /**
     * The revision the client edited. Omitted means "no opinion" — used by
     * callers with no offline story. Supplied means compare-and-swap.
     */
    expectedRevision?: number,
  ): Promise<
    | { ok: true; revision?: number }
    | { ok: false; code?: "LAYOUT_CONFLICT"; serverRevision?: number }
  >;
};

/** One read per tile. The router binds this to the real procedures. */
export type TileReader = (task: ResolveTask) => Promise<WidgetPayload<unknown>>;

/**
 * Audit hook, called once per board read.
 *
 * A board is thirty reads a minute. Auditing each tile would bury the log that
 * exists to answer "who saw our compliance records", and each tile's own
 * procedure already audits itself. What is worth recording once is that a
 * person opened a board and how much of it they were shown — including how many
 * tiles were withheld, which is the number an audit would actually ask about.
 */
export type BoardAudit = (event: {
  userId: number; roleKey: string; layoutRef: string | null;
  tiles: number; withheld: number; unknown: number; failed: number;
}) => Promise<void>;

/* ------------------------------------------------------------------ */
/* Reading a board                                                      */
/* ------------------------------------------------------------------ */

export type BoardTile = {
  instanceRef: string;
  widgetKey: string;
  title: string;
  variant: string;
  payload: WidgetPayload<unknown>;
  /** Computed server-side so a second client cannot invent its own rules. */
  appearance: ReturnType<typeof presentTile>;
};

export type Board = {
  layoutRef: string | null;
  /** True when nothing was saved and this is the registry-derived starting board. */
  seeded: boolean;
  name: string;
  deviceClass: DeviceClass;
  tiles: readonly BoardTile[];
};

const titleOf = (widgetKey: string): string =>
  (widgetKey in ({} as Record<string, never>) ? widgetKey : safeTitle(widgetKey));

function safeTitle(widgetKey: string): string {
  try {
    return definitionFor(widgetKey as WidgetKey).title;
  } catch {
    // An unregistered key still needs a heading, or the tile that reports the
    // loss would have nothing to report it about.
    return widgetKey;
  }
}

/**
 * Open a board.
 *
 * A caller with nothing saved gets the registry-derived starting board rather
 * than an empty screen, and is told it was seeded so the UI can offer to keep
 * it. Nothing is written on a read.
 */
export async function openBoard(
  deps: { store: WidgetLayoutStore; read: TileReader; audit?: BoardAudit },
  actor: RoleActor,
  q: {
    deviceClass: DeviceClass; layoutRef?: string;
    connected?: boolean;
    subjects?: Readonly<Partial<Record<"self" | "unit" | "trailer" | "job" | "trip" | "org" | "branch", string>>>;
  },
): Promise<Board> {
  // Everything that decides what may be seen comes off the actor. The request
  // contributes only what the server cannot know: whether the device has a
  // signal and which unit it is sitting in.
  const ctx = contextFor(actor, { connected: q.connected ?? true, subjects: q.subjects ?? {} });

  const found = await deps.store.findLayout({
    userId: actor.userId, roleKey: actor.roleKey, deviceClass: q.deviceClass,
    ...(q.layoutRef === undefined ? {} : { layoutRef: q.layoutRef }),
  });

  const seeded = found === null;
  const items: readonly LayoutItem[] = found
    ? found.items
    : defaultBoardFor(ctx, q.deviceClass).map((b) => ({
        instanceRef: `seed:${b.widgetKey}`,
        widgetKey: b.widgetKey,
        variant: b.variant,
        position: b.position,
      }));

  const plan = planBoard(items, ctx);
  const results: readonly TileResult[] = await runBoard(plan, deps.read);

  const byRef = new Map(items.map((i) => [i.instanceRef, i]));
  const tiles: BoardTile[] = results.map((r) => {
    const title = safeTitle(r.widgetKey);
    return {
      instanceRef: r.instanceRef,
      widgetKey: r.widgetKey,
      title,
      variant: byRef.get(r.instanceRef)?.variant ?? "status",
      payload: r.payload,
      appearance: presentTile(r.payload, title),
    };
  });

  if (deps.audit) {
    await deps.audit({
      userId: actor.userId, roleKey: actor.roleKey,
      layoutRef: found?.layout.layoutRef ?? null,
      tiles: tiles.length,
      withheld: tiles.filter((t) => t.payload.state === "not_permitted").length,
      unknown: tiles.filter((t) => t.payload.state === "unknown").length,
      failed: tiles.filter((t) => t.payload.state === "failed").length,
    });
  }

  return {
    layoutRef: found?.layout.layoutRef ?? null,
    seeded,
    name: found?.layout.name ?? "Default board",
    deviceClass: q.deviceClass,
    tiles,
  };
}

/* ------------------------------------------------------------------ */
/* Saving a board                                                       */
/* ------------------------------------------------------------------ */

export type SaveOutcome =
  | { ok: true; layoutRef: string; tiles: number; created: boolean; revision?: number }
  | { ok: false; rejections: readonly NamedRejection[] }
  /**
   * The board moved while this client was editing it.
   *
   * Named separately from a rejection because it is not the caller's mistake
   * and the remedy is different: a rejection is fixed by changing the board, a
   * conflict is resolved by choosing between two boards. Silently overwriting
   * would lose whoever saved second, which offline makes routine.
   */
  | { ok: false; code: "LAYOUT_CONFLICT"; serverRevision?: number };

/**
 * Rejections from a save outcome, or none.
 *
 * A conflict is not a rejection — nothing about the submitted board was wrong —
 * so the union separates them, and this keeps every caller from writing the
 * same `"rejections" in outcome` check slightly differently.
 */
export const rejectionsOf = (o: SaveOutcome): readonly NamedRejection[] =>
  o.ok || !("rejections" in o) ? [] : o.rejections;

/**
 * Save a board.
 *
 * The validation is `prepareLayoutSave`; this only performs what it approves.
 * If it refuses, nothing is written and every rejection is returned — a partial
 * save would leave a board the user did not arrange.
 */
export async function saveBoard(
  deps: { store: WidgetLayoutStore },
  actor: RoleActor,
  req: Omit<LayoutSaveRequest, "userId" | "roleKey" | "layoutRef"> & {
    layoutRef?: string | null;
    /** The revision this client edited, when it knows one. */
    expectedRevision?: number;
  },
): Promise<SaveOutcome> {
  const prepared = prepareLayoutSave(
    // Identity is the actor's, not the request's. The validator checks this
    // too; passing it from the request at all would be the hole.
    { ...req, userId: actor.userId, roleKey: actor.roleKey, layoutRef: req.layoutRef ?? null },
    { actingUserId: actor.userId, roles: actor.roles, permissions: actor.permissions },
  );
  if (!prepared.ok) return { ok: false, rejections: prepared.rejections };

  const unsetDefaults = prepared.sideEffects.some((e) => e.kind === "unset_other_defaults");

  // Create and update are separate store calls because they are separate
  // authorization problems. A create cannot collide with anyone; an update has
  // to prove ownership of an existing row before a single item is deleted.
  if (prepared.layout.layoutRef === null) {
    const created = await deps.store.createLayout(
      { ...prepared.layout, layoutRef: null }, prepared.items, unsetDefaults,
    );
    return { ok: true, layoutRef: created.layoutRef, tiles: prepared.items.length, created: true };
  }

  const outcome = await deps.store.updateOwnedLayout(
    { ...prepared.layout, layoutRef: prepared.layout.layoutRef },
    prepared.items,
    unsetDefaults,
    actor.tenantId,
    // Forwarded, not dropped. An earlier edit to this call was written and
    // never applied, so compare-and-swap lived in the store and could not be
    // reached through the service — the store's own tests passed because they
    // call it directly. A restore or an offline replay would have overwritten
    // a board that had moved, silently.
    req.expectedRevision,
  );
  if (!outcome.ok && outcome.code === "LAYOUT_CONFLICT") {
    return {
      ok: false, code: "LAYOUT_CONFLICT",
      ...(outcome.serverRevision !== undefined ? { serverRevision: outcome.serverRevision } : {}),
    };
  }
  if (!outcome.ok) {
    return {
      ok: false,
      rejections: [{
        code: "LAYOUT_NOT_OWNED_OR_NOT_FOUND",
        // One message for "does not exist" and for "is not yours". Two
        // messages would turn the save endpoint into a probe for whether a
        // given layoutRef belongs to somebody.
        detail: "no layout with that reference exists for this user, role and device",
      }],
    };
  }
  return {
    ok: true, layoutRef: prepared.layout.layoutRef, tiles: prepared.items.length, created: false,
    ...(outcome.revision !== undefined ? { revision: outcome.revision } : {}),
  };
}

/* ------------------------------------------------------------------ */
/* The picker                                                           */
/* ------------------------------------------------------------------ */

export type Offer = {
  widgetKey: WidgetKey;
  title: string;
  variants: readonly string[];
  defaultVariant: string;
  category: string;
  /** True when this role is the widget's suggested audience. Ordering only. */
  recommended: boolean;
};

export function listOfferable(actor: RoleActor): readonly Offer[] {
  // Offers for the acting role only. A dispatcher-only widget must not appear
  // in a driver board's picker just because the account also dispatches.
  return offerableWidgets({ permissions: actor.permissions }, actor.roles).map((key) => {
    const def = definitionFor(key);
    return {
      widgetKey: key, title: def.title, variants: def.variants,
      defaultVariant: def.defaultVariant, category: def.category,
      recommended: def.suggestedFor.includes(actor.roleKey),
    };
  });
}

export { titleOf };

/* ------------------------------------------------------------------ */
/* Actions                                                             */
/* ------------------------------------------------------------------ */

/**
 * The gate an action must pass, rerun at submission.
 *
 * Returns the blockers standing in the way right now — empty means clear.
 * Deliberately not given the tile, the payload or the board: a gate that could
 * see what the widget claimed might be tempted to agree with it.
 */
export type ActionGate = (args: {
  actor: RoleActor; action: string; subjectRef: string | null;
}) => Promise<readonly NamedBlocker[]>;

export type ActionOutcome =
  | { ok: true; action: string }
  | { ok: false; code: "NOT_PERMITTED" | "BLOCKED"; blockers: readonly NamedBlocker[] };

/**
 * Submit an action from a tile.
 *
 * A widget's button is not an authorization decision. The tile that offered it
 * was rendered from an answer that was true when it was read — five seconds
 * ago, or four hours ago out of a cache — and the conditions behind a dispatch,
 * a mechanic release or an invoice can change in between. So the gate runs
 * again here, from the actor and the subject, and the tile's own state is never
 * consulted.
 *
 * This is why `presentTile`'s `actionable` is a presentation flag and not a
 * permission: it decides whether a button is drawn, never whether the thing
 * behind it may happen.
 */
export async function submitBoardAction(
  deps: { gate: ActionGate },
  actor: RoleActor,
  req: { action: string; subjectRef: string | null; requiredPermission: string },
): Promise<ActionOutcome> {
  // Role first, from the actor's own permission set rather than the board's.
  if (!actor.permissions.includes(req.requiredPermission)) {
    return { ok: false, code: "NOT_PERMITTED", blockers: [] };
  }

  const blockers = await deps.gate({ actor, action: req.action, subjectRef: req.subjectRef });
  if (blockers.length > 0) return { ok: false, code: "BLOCKED", blockers };

  return { ok: true, action: req.action };
}

/* ------------------------------------------------------------------ */
/* Restore default                                                     */
/* ------------------------------------------------------------------ */

export type RestorePreview = {
  items: readonly { widgetKey: WidgetKey; variant: string; position: number; title: string }[];
  /** What the board currently holds, so the user can see what is being replaced. */
  replacing: number;
};

/**
 * What Restore Default would produce, without producing it.
 *
 * Derived from the registry and the actor — there is no second default list in
 * the UI to drift from this one. Only currently offerable widgets appear, so a
 * revoked permission cannot come back through the restore path: the board a
 * driver gets today is the board their permissions today allow.
 */
export function previewDefaultBoard(
  actor: RoleActor,
  deviceClass: DeviceClass,
  currentTileCount: number,
): RestorePreview {
  const items = defaultBoardFor(
    { roles: actor.roles, permissions: actor.permissions },
    deviceClass,
  ).map((b) => ({ ...b, title: definitionFor(b.widgetKey).title }));
  return { items, replacing: currentTileCount };
}

/**
 * Replace the board with the registry default.
 *
 * Goes through `saveBoard`, so it meets the same validation, the same ownership
 * check and the same compare-and-swap as any other save. A restore that wrote
 * directly to the store would be a second write path, and the second one is
 * always the one missing a check.
 */
export async function restoreDefaultBoard(
  deps: { store: WidgetLayoutStore },
  actor: RoleActor,
  req: {
    layoutRef?: string | null;
    expectedRevision?: number;
    deviceClass: DeviceClass;
    name: string;
    isDefault: boolean;
  },
): Promise<SaveOutcome> {
  const preview = previewDefaultBoard(actor, req.deviceClass, 0);
  return saveBoard({ store: deps.store }, actor, {
    layoutRef: req.layoutRef ?? null,
    ...(req.expectedRevision !== undefined ? { expectedRevision: req.expectedRevision } : {}),
    deviceClass: req.deviceClass,
    name: req.name,
    isDefault: req.isDefault,
    items: preview.items.map((b, i) => ({
      // Deterministic instance refs: restoring twice produces the same board,
      // which matters when the result is compared against a staged offline one.
      instanceRef: `default-${b.widgetKey}`,
      widgetKey: b.widgetKey,
      variant: b.variant,
      position: i,
    })),
  });
}
