import { TRPCError } from "@trpc/server";
import { and, eq, or } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "./db";
import type { Tx } from "./_core/dbTypes";
import { roleProcedure, router } from "./_core/trpc";
import { resolveActingScope } from "./_core/actingScope";
import { recordBelongsToOrganization } from "./_core/coreRecordOwnership";
import { nextSequence, pad2 } from "./_core/commercialChainNumbers";
import { commercialJobChains, commercialLoadChainRefs, contractorBusinessProfiles, contractorPayableEvents, contractorPayables, jobCrewAssignments, jobs, loads, organizationRelationships, organizationWorkers, privateRateSchedules } from "../drizzle/schema";

const dbOrThrow = async () => { const db = await getDb(); if (!db) throw new TRPCError({code:"INTERNAL_SERVER_ERROR",message:"Database unavailable"}); return db; };
const ref = (p:string) => `${p}-${crypto.randomUUID()}`;
const relationshipType = z.enum(["PRIME_CONTRACTOR","CONTRACTOR","SUBCONTRACTOR","VENDOR","LEASED_OWNER_OPERATOR","INDEPENDENT_CARRIER","EQUIPMENT_PROVIDER"]);
const workerType = z.enum(["OWNER_DRIVER","EMPLOYEE_DRIVER","CO_DRIVER","SWAMPER","LABORER","EQUIPMENT_OPERATOR","HELPER","SHOP_HAND","MECHANIC","MAINTENANCE_SUPERVISOR","BOOKKEEPER","DISPATCHER","SAFETY_COMPLIANCE","OFFICE_ADMIN"]);
const compensationType = z.enum(["HOURLY","SALARY","DAY_RATE","LOAD_RATE","KM_RATE","PERCENTAGE","PIECE_RATE","CONTRACT_RATE"]);
const quantityUnit = z.enum(["HOUR","DAY","LOAD","KM","PERCENT","PIECE","CONTRACT"]);
const autoUnitFor: Record<string,string> = { HOURLY:"HOUR", DAY_RATE:"DAY", LOAD_RATE:"LOAD", KM_RATE:"KM", PIECE_RATE:"PIECE", CONTRACT_RATE:"CONTRACT" };
// 0234 — the allocator moved to _core/commercialChainNumbers.ts so the marketplace bridge numbers its chains the same way.


export const contractorOperationsRouter = router({
  profileUpsert: roleProcedure("contractorOperations.profileUpsert").input(z.object({ operatingMode:z.enum(["LEASED_OWNER_OPERATOR","INDEPENDENT_CONTRACTOR","INDEPENDENT_CARRIER","CONTRACTOR_COMPANY"]), legalName:z.string().min(1).max(220), carrierNumber:z.string().max(80).nullable().optional() })).mutation(async ({ctx,input})=>{
    const db=await dbOrThrow(), orgRef=(await resolveActingScope(db,ctx.user.id)).tenantId;
    await db.insert(contractorBusinessProfiles).values({orgRef,...input,carrierNumber:input.carrierNumber??null,createdByUserId:ctx.user.id}).onDuplicateKeyUpdate({set:{operatingMode:input.operatingMode,legalName:input.legalName,carrierNumber:input.carrierNumber??null,status:"active"}}); return {orgRef};
  }),
  relationshipCreate: roleProcedure("contractorOperations.relationshipCreate").input(z.object({childOrgRef:z.string().min(1).max(40),relationshipType,effectiveFrom:z.coerce.date()})).mutation(async({ctx,input})=>{
    const db=await dbOrThrow(), parentOrgRef=(await resolveActingScope(db,ctx.user.id)).tenantId; if(parentOrgRef===input.childOrgRef) throw new TRPCError({code:"BAD_REQUEST",message:"An organization cannot contract with itself."});
    const relationshipRef=ref("REL"); await db.insert(organizationRelationships).values({relationshipRef,parentOrgRef,childOrgRef:input.childOrgRef,relationshipType:input.relationshipType,status:"pending",effectiveFrom:input.effectiveFrom,createdByUserId:ctx.user.id}); return {relationshipRef,status:"pending" as const};
  }),
  relationships: roleProcedure("contractorOperations.relationships").query(async({ctx})=>{ const db=await dbOrThrow(), org=(await resolveActingScope(db,ctx.user.id)).tenantId; return db.select().from(organizationRelationships).where(or(eq(organizationRelationships.parentOrgRef,org),eq(organizationRelationships.childOrgRef,org))); }),
  relationshipAccept: roleProcedure("contractorOperations.relationshipAccept").input(z.object({relationshipRef:z.string().min(1).max(64)})).mutation(async({ctx,input})=>{const db=await dbOrThrow(),org=(await resolveActingScope(db,ctx.user.id)).tenantId; const [rel]=await db.select().from(organizationRelationships).where(eq(organizationRelationships.relationshipRef,input.relationshipRef)).limit(1); if(!rel||rel.childOrgRef!==org) throw new TRPCError({code:"FORBIDDEN",message:"Only the invited organization may accept this relationship."}); if(rel.status!=="pending") throw new TRPCError({code:"CONFLICT",message:"Relationship is not pending."}); await db.update(organizationRelationships).set({status:"active"}).where(eq(organizationRelationships.id,rel.id)); return {status:"active" as const};}),
  workerAdd: roleProcedure("contractorOperations.workerAdd").input(z.object({userId:z.number().int().positive().nullable().optional(),operatorId:z.number().int().positive().nullable().optional(),workerType,compensationType:compensationType.nullable().optional(),effectiveFrom:z.coerce.date()})).mutation(async({ctx,input})=>{
    const db=await dbOrThrow(), orgRef=(await resolveActingScope(db,ctx.user.id)).tenantId, workerRef=ref("WRK"); await db.insert(organizationWorkers).values({workerRef,orgRef,...input,userId:input.userId??null,operatorId:input.operatorId??null,compensationType:input.compensationType??null,createdByUserId:ctx.user.id}); return {workerRef};
  }),
  crewAssign: roleProcedure("contractorOperations.crewAssign").input(z.object({chainRef:z.string().min(1).max(80),unitId:z.number().int().positive(),primaryDriverWorkerRef:z.string().min(1).max(64),coDriverWorkerRef:z.string().min(1).max(64).nullable().optional(),additionalCrew:z.array(z.object({workerRef:z.string().min(1).max(64),role:workerType})).default([]),startsAt:z.coerce.date()})).mutation(async({ctx,input})=>{
    const db=await dbOrThrow(), org=(await resolveActingScope(db,ctx.user.id)).tenantId; const [chain]=await db.select().from(commercialJobChains).where(eq(commercialJobChains.chainRef,input.chainRef)).limit(1); if(!chain || chain.performingOrgRef!==org) throw new TRPCError({code:"FORBIDDEN",message:"Only the performing organization may assign its crew."}); if(input.coDriverWorkerRef===input.primaryDriverWorkerRef) throw new TRPCError({code:"BAD_REQUEST",message:"Primary driver and co-driver must be different workers."});
    if(!(await recordBelongsToOrganization(db,org,"unit",input.unitId))) throw new TRPCError({code:"FORBIDDEN",message:"Unit is not owned by the performing organization."}); const workerRefs=[input.primaryDriverWorkerRef,...(input.coDriverWorkerRef?[input.coDriverWorkerRef]:[]),...input.additionalCrew.map(x=>x.workerRef)]; const workers=await db.select().from(organizationWorkers).where(and(eq(organizationWorkers.orgRef,org),eq(organizationWorkers.status,"active"))); const owned=new Set(workers.map(w=>w.workerRef)); if(workerRefs.some(w=>!owned.has(w))) throw new TRPCError({code:"FORBIDDEN",message:"Every assigned crew member must be an active worker of the performing organization."});
    const assignmentRef=ref("CREW"); await db.insert(jobCrewAssignments).values({assignmentRef,chainRef:input.chainRef,unitId:input.unitId,primaryDriverWorkerRef:input.primaryDriverWorkerRef,coDriverWorkerRef:input.coDriverWorkerRef??null,additionalCrewJson:JSON.stringify(input.additionalCrew),startsAt:input.startsAt,createdByUserId:ctx.user.id}); return {assignmentRef,hosLedgerPolicy:"INDIVIDUAL_PER_DRIVER" as const};
  }),
  jobChainCreate: roleProcedure("contractorOperations.jobChainCreate").input(z.object({rootJobId:z.number().int().positive(),performingOrgRef:z.string().min(1).max(40),parentChainRef:z.string().max(80).nullable().optional(),customerOrgRef:z.string().max(40).nullable().optional(),operatingCarrierOrgRef:z.string().max(40).nullable().optional(),equipmentOwnerOrgRef:z.string().max(40).nullable().optional(),relationshipType:z.enum(["EMPLOYEE","LEASED_OWNER_OPERATOR","INDEPENDENT_CONTRACTOR","SUBCONTRACTOR","INDEPENDENT_CARRIER"])})).mutation(async({ctx,input})=>{
    const db=await dbOrThrow(), assigningOrgRef=(await resolveActingScope(db,ctx.user.id)).tenantId; if(input.parentChainRef){const [p]=await db.select().from(commercialJobChains).where(eq(commercialJobChains.chainRef,input.parentChainRef)).limit(1); if(!p || p.performingOrgRef!==assigningOrgRef) throw new TRPCError({code:"FORBIDDEN",message:"Only the performing organization may subcontract its assignment."});}
    if(input.relationshipType==="EMPLOYEE"){ if(input.performingOrgRef!==assigningOrgRef) throw new TRPCError({code:"BAD_REQUEST",message:"Employee assignments cannot cross organization boundaries."}); } else { const allowedMap:Record<string,string[]>={LEASED_OWNER_OPERATOR:["LEASED_OWNER_OPERATOR"],INDEPENDENT_CONTRACTOR:["CONTRACTOR"],SUBCONTRACTOR:["SUBCONTRACTOR","CONTRACTOR"],INDEPENDENT_CARRIER:["INDEPENDENT_CARRIER"]}; const allowed=allowedMap[input.relationshipType]??[]; const rels=await db.select().from(organizationRelationships).where(and(eq(organizationRelationships.parentOrgRef,assigningOrgRef),eq(organizationRelationships.childOrgRef,input.performingOrgRef),eq(organizationRelationships.status,"active"))); if(!rels.some(r=>allowed.includes(r.relationshipType))) throw new TRPCError({code:"PRECONDITION_FAILED",message:"No active commercial relationship authorizes this assignment."}); }
    const result=await db.transaction(async(tx)=>{
      const [job]=await tx.select().from(jobs).where(eq(jobs.id,input.rootJobId)).limit(1); if(!job) throw new TRPCError({code:"NOT_FOUND",message:"Root job not found."});
      let chainNumber:string;
      if(input.parentChainRef){ const [parent]=await tx.select().from(commercialJobChains).where(eq(commercialJobChains.chainRef,input.parentChainRef)).for("update").limit(1); if(!parent?.chainNumber) throw new TRPCError({code:"CONFLICT",message:"Parent chain has no inherited commercial number."}); const n=await nextSequence(tx,`SUB:${parent.chainRef}`); chainNumber=`${parent.chainNumber}-S${pad2(n)}`; }
      else { const n=await nextSequence(tx,`CONTRACT:${input.rootJobId}`); chainNumber=`${job.jobCode}-C${pad2(n)}`; }
      const chainRef=ref(input.parentChainRef?"SUB":"JOB"); await tx.insert(commercialJobChains).values({chainRef,chainNumber,rootJobId:input.rootJobId,parentChainRef:input.parentChainRef??null,assigningOrgRef,performingOrgRef:input.performingOrgRef,customerOrgRef:input.customerOrgRef??null,operatingCarrierOrgRef:input.operatingCarrierOrgRef??null,equipmentOwnerOrgRef:input.equipmentOwnerOrgRef??null,relationshipType:input.relationshipType,createdByUserId:ctx.user.id}); return {chainRef,chainNumber};
    }); return result;
  }),
  rateSet: roleProcedure("contractorOperations.rateSet").input(z.object({counterpartyOrgRef:z.string().min(1).max(40),chainRef:z.string().max(80).nullable().optional(),compensationType,rateCents:z.number().int().nonnegative(),currency:z.string().length(3).default("CAD"),effectiveFrom:z.coerce.date()})).mutation(async({ctx,input})=>{
    const db=await dbOrThrow(), ownerOrgRef=(await resolveActingScope(db,ctx.user.id)).tenantId, rateRef=ref("RATE"); await db.insert(privateRateSchedules).values({rateRef,ownerOrgRef,...input,chainRef:input.chainRef??null,createdByUserId:ctx.user.id}); return {rateRef};
  }),
  ratesMine: roleProcedure("contractorOperations.ratesMine").query(async({ctx})=>{const db=await dbOrThrow(),org=(await resolveActingScope(db,ctx.user.id)).tenantId; return db.select().from(privateRateSchedules).where(or(eq(privateRateSchedules.ownerOrgRef,org),eq(privateRateSchedules.counterpartyOrgRef,org)));}),
  loadLink: roleProcedure("contractorOperations.loadLink").input(z.object({chainRef:z.string().min(1).max(80),loadId:z.number().int().positive()})).mutation(async({ctx,input})=>{
    const db=await dbOrThrow(), org=(await resolveActingScope(db,ctx.user.id)).tenantId; return db.transaction(async(tx)=>{ const [chain]=await tx.select().from(commercialJobChains).where(eq(commercialJobChains.chainRef,input.chainRef)).for("update").limit(1); if(!chain || chain.performingOrgRef!==org || !chain.chainNumber) throw new TRPCError({code:"FORBIDDEN",message:"Only the performing organization may number loads on this chain."}); const [load]=await tx.select().from(loads).where(eq(loads.id,input.loadId)).limit(1); if(!load || load.jobId!==chain.rootJobId) throw new TRPCError({code:"BAD_REQUEST",message:"Load does not belong to the root job."}); const [existing]=await tx.select().from(commercialLoadChainRefs).where(eq(commercialLoadChainRefs.loadId,input.loadId)).limit(1); if(existing){if(existing.chainRef!==input.chainRef) throw new TRPCError({code:"CONFLICT",message:"Load is already bound to another commercial chain."}); return {loadChainNumber:existing.loadChainNumber};} const n=await nextSequence(tx,`LOAD:${chain.chainRef}`),loadChainNumber=`${chain.chainNumber}-L${String(n).padStart(3,"0")}`; await tx.insert(commercialLoadChainRefs).values({loadId:input.loadId,chainRef:input.chainRef,loadChainNumber,createdByUserId:ctx.user.id}); return {loadChainNumber}; });
  }),
  payablePrepare: roleProcedure("contractorOperations.payablePrepare").input(z.object({chainRef:z.string().min(1).max(80),rateRef:z.string().min(1).max(80),quantityMillis:z.number().int().positive(),quantityUnit,evidenceRefs:z.array(z.string().min(1).max(160)).min(1),preparationSource:z.enum(["HUMAN","AI_SECRETARY"]).default("HUMAN")})).mutation(async({ctx,input})=>{
    const db=await dbOrThrow(), payerOrgRef=(await resolveActingScope(db,ctx.user.id)).tenantId; const [chain]=await db.select().from(commercialJobChains).where(eq(commercialJobChains.chainRef,input.chainRef)).limit(1); if(!chain || chain.assigningOrgRef!==payerOrgRef) throw new TRPCError({code:"FORBIDDEN",message:"Only the assigning organization may prepare this contractor payable."}); const [rate]=await db.select().from(privateRateSchedules).where(and(eq(privateRateSchedules.rateRef,input.rateRef),eq(privateRateSchedules.ownerOrgRef,payerOrgRef),eq(privateRateSchedules.counterpartyOrgRef,chain.performingOrgRef))).limit(1); if(!rate) throw new TRPCError({code:"FORBIDDEN",message:"Rate is not a private contract rate between these parties."}); if(rate.chainRef && rate.chainRef!==input.chainRef) throw new TRPCError({code:"BAD_REQUEST",message:"Rate is scoped to another job chain."}); const expected=autoUnitFor[rate.compensationType]; if(!expected) throw new TRPCError({code:"PRECONDITION_FAILED",message:"Salary and percentage compensation require reviewed calculation evidence and cannot be auto-settled."}); if(expected!==input.quantityUnit) throw new TRPCError({code:"BAD_REQUEST",message:`${rate.compensationType} requires ${expected} quantity.`}); const now=new Date(); if(rate.effectiveFrom>now || (rate.effectiveTo && rate.effectiveTo<now)) throw new TRPCError({code:"PRECONDITION_FAILED",message:"Rate is not currently effective."}); const grossAmountCents=Math.round(input.quantityMillis*rate.rateCents/1000); const payableRef=ref("PAY"); await db.transaction(async(tx)=>{await tx.insert(contractorPayables).values({payableRef,chainRef:input.chainRef,payerOrgRef,payeeOrgRef:chain.performingOrgRef,rateRef:rate.rateRef,compensationType:rate.compensationType,quantityMillis:input.quantityMillis,quantityUnit:input.quantityUnit,rateCentsSnapshot:rate.rateCents,grossAmountCents,currency:rate.currency,evidenceRefsJson:JSON.stringify(input.evidenceRefs),preparationSource:input.preparationSource,preparedByUserId:ctx.user.id}); await tx.insert(contractorPayableEvents).values({eventRef:ref("PAYEV"),payableRef,actorOrgRef:payerOrgRef,actorUserId:ctx.user.id,eventType:"PREPARED",amountCentsSnapshot:grossAmountCents});}); return {payableRef,grossAmountCents,currency:rate.currency,state:"prepared" as const,approvalRequired:true};
  }),
  payablesMine: roleProcedure("contractorOperations.payablesMine").query(async({ctx})=>{const db=await dbOrThrow(),org=(await resolveActingScope(db,ctx.user.id)).tenantId; return db.select().from(contractorPayables).where(or(eq(contractorPayables.payerOrgRef,org),eq(contractorPayables.payeeOrgRef,org)));}),
  payableSubmitReview: roleProcedure("contractorOperations.payableSubmitReview").input(z.object({payableRef:z.string().min(1).max(80)})).mutation(async({ctx,input})=>{const db=await dbOrThrow(),org=(await resolveActingScope(db,ctx.user.id)).tenantId; return db.transaction(async(tx)=>{const [p]=await tx.select().from(contractorPayables).where(eq(contractorPayables.payableRef,input.payableRef)).for("update").limit(1); if(!p||p.payerOrgRef!==org) throw new TRPCError({code:"FORBIDDEN"}); if(p.state!=="prepared") throw new TRPCError({code:"CONFLICT",message:"Only prepared payables may enter review."}); await tx.update(contractorPayables).set({state:"review"}).where(eq(contractorPayables.id,p.id)); await tx.insert(contractorPayableEvents).values({eventRef:ref("PAYEV"),payableRef:p.payableRef,actorOrgRef:org,actorUserId:ctx.user.id,eventType:"SUBMITTED_REVIEW",amountCentsSnapshot:p.grossAmountCents}); return {state:"review" as const};});}),
  payableApprove: roleProcedure("contractorOperations.payableApprove").input(z.object({payableRef:z.string().min(1).max(80)})).mutation(async({ctx,input})=>{const db=await dbOrThrow(),org=(await resolveActingScope(db,ctx.user.id)).tenantId; return db.transaction(async(tx)=>{const [p]=await tx.select().from(contractorPayables).where(eq(contractorPayables.payableRef,input.payableRef)).for("update").limit(1); if(!p||p.payerOrgRef!==org) throw new TRPCError({code:"FORBIDDEN"}); if(p.state!=="review") throw new TRPCError({code:"CONFLICT",message:"Payable must be in review before approval."}); if(p.preparedByUserId===ctx.user.id) throw new TRPCError({code:"PRECONDITION_FAILED",message:"The preparer cannot approve the same contractor payable."}); const at=new Date(); await tx.update(contractorPayables).set({state:"approved",approvedByUserId:ctx.user.id,approvedAt:at}).where(eq(contractorPayables.id,p.id)); await tx.insert(contractorPayableEvents).values({eventRef:ref("PAYEV"),payableRef:p.payableRef,actorOrgRef:org,actorUserId:ctx.user.id,eventType:"APPROVED",amountCentsSnapshot:p.grossAmountCents}); return {state:"approved" as const,approvedAt:at};});}),
});
