/**
 * C1b-3 — characterization of every document-validity decision, written BEFORE the four inline
 * implementations were routed through `documentValidity`.
 *
 * The table below was generated by running the four callers as they stood on main (3d05d32) over one
 * frozen clock. After the reconciliation it must still hold, except for the rows listed in
 * RESOLVED — each a place where the four disagreed and the canonical rule now decides.
 */
import { describe, expect, it } from "vitest";
import { evaluateRequirement } from "./_core/compliancePassport";
import { credentialBlocker } from "./_core/dispatchReadiness";
import { credentialState } from "./readinessComposer";
import { expiryState } from "./widgetSources";

const NOW = new Date("2026-10-15T12:00:00Z");
const S = 1000, D = 86_400_000;
const EXPIRIES: Record<string, Date | null> = {
  noExpiry: null, future400d: new Date(NOW.getTime() + 400 * D), laterToday: new Date(NOW.getTime() + 6 * 3600 * S),
  oneSecondBefore: new Date(NOW.getTime() - S), oneSecondAfter: new Date(NOW.getTime() + S), exactInstant: new Date(NOW),
  expired10d: new Date(NOW.getTime() - 10 * D), exactly30d: new Date(NOW.getTime() + 30 * D), window30_5d: new Date(NOW.getTime() + 30.5 * D),
  // A date-only expiry is midnight UTC of that day; a local end-of-day is an absolute instant too.
  dateOnlyToday: new Date("2026-10-15"), tzEndOfLocalDay: new Date("2026-10-15T23:59:59-07:00"),
};
const VER = ["verified", "needs_review", "rejected"] as const;

const requirement = {
  requirementKey: "r", version: 1, family: "f", title: "Doc", subjectType: "operator" as const, jurisdiction: "*",
  satisfiedByDocTypes: ["d"], warnDaysBeforeExpiry: 30, missingSeverity: "blocked" as const, verificationStatus: "verified" as const,
  effectiveFrom: new Date(0),
};

function observe() {
  const out: Record<string, unknown> = {};
  for (const [k, e] of Object.entries(EXPIRIES)) for (const v of VER) {
    const w = expiryState({ id: 1, ownerType: "operator", ownerId: 1, docType: "d", title: "t", expiresAt: e, verificationStatus: v }, NOW, 30);
    const cs = credentialState([{ id: 1, docType: "d", expiresAt: e, verificationStatus: v } as never], ["d"], "Doc", NOW);
    const b = credentialBlocker(cs, NOW, "operator", "doc");
    const p = evaluateRequirement({ requirement, credentials: [{ docType: "d", expiresAt: e, verificationStatus: v, privateDetail: false }], now: NOW });
    out[`${k}|${v}`] = { widget: w, dispatch: b ? b.code : null, passport: `${p.status}:${p.daysToExpiry}` };
  }
  out["noExpiry|null"] = { widget: expiryState({ id: 1, ownerType: "operator", ownerId: 1, docType: "d", title: "t", expiresAt: null, verificationStatus: null }, NOW, 30) };
  return out;
}

/** As generated from main 3d05d32, before any change. */
const BEFORE: Record<string, unknown> = {
  "noExpiry|verified": {"widget": "current", "dispatch": "doc_unknown", "passport": "satisfied:null"},
  "noExpiry|needs_review": {"widget": "unverified", "dispatch": "doc_unknown", "passport": "evidence_unverified:null"},
  "noExpiry|rejected": {"widget": "rejected", "dispatch": "doc_missing", "passport": "evidence_rejected:null"},
  "future400d|verified": {"widget": "current", "dispatch": null, "passport": "satisfied:400"},
  "future400d|needs_review": {"widget": "unverified", "dispatch": null, "passport": "evidence_unverified:400"},
  "future400d|rejected": {"widget": "rejected", "dispatch": "doc_missing", "passport": "evidence_rejected:null"},
  "laterToday|verified": {"widget": "expiring", "dispatch": null, "passport": "expiring:0"},
  "laterToday|needs_review": {"widget": "unverified", "dispatch": null, "passport": "evidence_unverified:0"},
  "laterToday|rejected": {"widget": "rejected", "dispatch": "doc_missing", "passport": "evidence_rejected:null"},
  "oneSecondBefore|verified": {"widget": "expired", "dispatch": "doc_expired", "passport": "expired:-1"},
  "oneSecondBefore|needs_review": {"widget": "unverified", "dispatch": "doc_expired", "passport": "expired:-1"},
  "oneSecondBefore|rejected": {"widget": "rejected", "dispatch": "doc_missing", "passport": "evidence_rejected:null"},
  "oneSecondAfter|verified": {"widget": "expiring", "dispatch": null, "passport": "expiring:0"},
  "oneSecondAfter|needs_review": {"widget": "unverified", "dispatch": null, "passport": "evidence_unverified:0"},
  "oneSecondAfter|rejected": {"widget": "rejected", "dispatch": "doc_missing", "passport": "evidence_rejected:null"},
  "exactInstant|verified": {"widget": "expiring", "dispatch": null, "passport": "expired:0"},
  "exactInstant|needs_review": {"widget": "unverified", "dispatch": null, "passport": "expired:0"},
  "exactInstant|rejected": {"widget": "rejected", "dispatch": "doc_missing", "passport": "evidence_rejected:null"},
  "expired10d|verified": {"widget": "expired", "dispatch": "doc_expired", "passport": "expired:-10"},
  "expired10d|needs_review": {"widget": "unverified", "dispatch": "doc_expired", "passport": "expired:-10"},
  "expired10d|rejected": {"widget": "rejected", "dispatch": "doc_missing", "passport": "evidence_rejected:null"},
  "exactly30d|verified": {"widget": "expiring", "dispatch": null, "passport": "expiring:30"},
  "exactly30d|needs_review": {"widget": "unverified", "dispatch": null, "passport": "evidence_unverified:30"},
  "exactly30d|rejected": {"widget": "rejected", "dispatch": "doc_missing", "passport": "evidence_rejected:null"},
  "window30_5d|verified": {"widget": "current", "dispatch": null, "passport": "expiring:30"},
  "window30_5d|needs_review": {"widget": "unverified", "dispatch": null, "passport": "evidence_unverified:30"},
  "window30_5d|rejected": {"widget": "rejected", "dispatch": "doc_missing", "passport": "evidence_rejected:null"},
  "dateOnlyToday|verified": {"widget": "expired", "dispatch": "doc_expired", "passport": "expired:-1"},
  "dateOnlyToday|needs_review": {"widget": "unverified", "dispatch": "doc_expired", "passport": "expired:-1"},
  "dateOnlyToday|rejected": {"widget": "rejected", "dispatch": "doc_missing", "passport": "evidence_rejected:null"},
  "tzEndOfLocalDay|verified": {"widget": "expiring", "dispatch": null, "passport": "expiring:0"},
  "tzEndOfLocalDay|needs_review": {"widget": "unverified", "dispatch": null, "passport": "evidence_unverified:0"},
  "tzEndOfLocalDay|rejected": {"widget": "rejected", "dispatch": "doc_missing", "passport": "evidence_rejected:null"},
  "noExpiry|null": {"widget": "current"},
};

/**
 * Where the four disagreed, and what the canonical rule decides. Empty until the reconciliation;
 * every entry is a documented semantic difference (docs/compliance/checkpoints/C1B_3_…md).
 */
const RESOLVED: Record<string, unknown> = {
  // 1. The exact expiry instant. The passport said expired (`<=`); dispatch, the tile and the engine
  //    said still in force (`<`). The dispatch rule is canonical — dispatch behaviour must not change —
  //    so the passport moves, by one instant, to "expiring".
  "exactInstant|verified": { widget: "expiring", dispatch: null, passport: "expiring:0" },
  "exactInstant|needs_review": { widget: "unverified", dispatch: null, passport: "evidence_unverified:0" },
  // 2. The tile's warning window counted milliseconds (30.5 days > 30 days → current); the passport and
  //    the engine count whole days (30.5 → 30 → expiring). Whole days are canonical.
  "window30_5d|verified": { widget: "expiring", dispatch: null, passport: "expiring:30" },
  // 3. A row with no verification status read as verified on the tile (`if (status && status !==
  //    "verified")`). A missing status is not evidence: it now reads unverified. The column is NOT NULL,
  //    so only a malformed serialized row can reach this.
  "noExpiry|null": { widget: "unverified" },
};

describe("document validity — characterization across the four callers", () => {
  it("matches the recorded behaviour, except where a difference was resolved on purpose", () => {
    expect(observe()).toEqual({ ...BEFORE, ...RESOLVED });
  });
});

describe("document validity — which row governs when there are several", () => {
  const row = (id: number, expiresInDays: number, v: "verified" | "needs_review" | "rejected", capturedDaysAgo: number) => ({
    id, docType: "d", expiresAt: new Date(NOW.getTime() + expiresInDays * D), verificationStatus: v,
    capturedAt: new Date(NOW.getTime() - capturedDaysAgo * D), privateDetail: false,
  });
  const both = (rows: ReturnType<typeof row>[]) => {
    const p = evaluateRequirement({ requirement, credentials: rows, now: NOW });
    const b = credentialBlocker(credentialState(rows as never, ["d"], "Doc", NOW), NOW, "operator", "doc");
    return { passport: `${p.status}:${p.daysToExpiry}`, dispatch: b ? b.code : null };
  };
  it("prefers verified, then the latest expiry — not the latest capture", () => {
    // An older verified capture with the later expiry governs over a newer verified capture.
    expect(both([row(1, 400, "verified", 30), row(2, 10, "verified", 1)])).toEqual({ passport: "satisfied:400", dispatch: null });
    expect(both([row(1, 10, "verified", 30), row(2, 400, "needs_review", 1)])).toEqual({ passport: "expiring:10", dispatch: null });
    expect(both([row(1, 400, "rejected", 30), row(2, -5, "needs_review", 1)])).toEqual({ passport: "expired:-5", dispatch: "doc_expired" });
    expect(both([row(1, 400, "rejected", 30)])).toEqual({ passport: "evidence_rejected:null", dispatch: "doc_missing" });
  });
});
