/**
 * Payroll P2 — pay schedules, generated periods and the period machine, met the way a client meets them.
 *
 * Every call goes through `appRouter.createCaller` with real role grants, organization memberships and
 * financial entities. The pure calendar and transition rules are in `_core/payrollSchedule.test.ts`; this file
 * proves the tenant boundary, the lock against earnings, runs and collection, separation of duties, and who holds
 * which door.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import mysql from "mysql2/promise";
import { appRouter } from "./routers";
import * as payrollSvc from "./payrollService";

const DB_URL = process.env.DATABASE_URL;
const d = DB_URL ? describe : describe.skip;
let pool: mysql.Pool;
let seq = 350_000_000 + Math.floor(Math.random() * 50_000);
const rnd = () => Math.random().toString(36).slice(2, 9).toUpperCase();
beforeAll(() => { if (DB_URL) pool = mysql.createPool({ uri: DB_URL, connectionLimit: 4 }); });
afterAll(async () => { await pool?.end(); });

const callerFor = (userId: number) => appRouter.createCaller({ req: {} as never, res: {} as never, user: { id: userId, role: "user" } as never });
async function org() { const orgRef = `ORG-${rnd()}`; await pool.execute("INSERT INTO organizations (orgRef, name, status) VALUES (?,?,'active')", [orgRef, `o ${orgRef}`]); return orgRef; }
async function member(orgRef: string, roles: string[]) {
  const userId = seq++;
  for (const role of roles) await pool.execute("INSERT INTO userRoleAssignments (userId, role, scopeType, grantedByUserId, grantedAt) VALUES (?,?,'global',1,NOW())", [userId, role]);
  await pool.execute("INSERT INTO organizationMemberships (membershipRef, orgRef, userId, membershipType, status, effectiveFrom, createdByUserId) VALUES (?,?,?,'employee','active','2020-01-01',1)", [`MEM-${rnd()}`, orgRef, userId]);
  return userId;
}
const entityInput = () => ({ entityRef: `FE-${rnd()}`, legalName: `Entity ${rnd()} Ltd`, taxpayerType: "corporation" as const, jurisdiction: "AB" });
const code = (e: unknown) => (typeof e === "object" && e !== null && "code" in e ? (e as { code: string }).code : undefined);
async function refusal(fn: () => Promise<unknown>): Promise<{ code?: string; message: string }> {
  try { await fn(); } catch (e) { return { code: code(e), message: (e as Error).message }; }
  throw new Error("expected a refusal");
}

async function company() {
  const orgRef = await org();
  const controller = await member(orgRef, ["controller"]);
  const admin = await member(orgRef, ["payroll_admin"]);
  const hr = await member(orgRef, ["hr"]);
  const worker = await member(orgRef, ["driver"]);
  const entityId = (await callerFor(controller).finance.entityCreate(entityInput())).id as number;
  const profileId = (await callerFor(admin).payroll.profileUpsert({ employeeNumber: `EMP-${rnd()}`, financialEntityId: entityId, userId: worker, workerKind: "employee", employmentType: "full_time", defaultPayMethod: "hourly" })).id as number;
  return { orgRef, controller, admin, hr, worker, entityId, profileId };
}
type Co = Awaited<ReturnType<typeof company>>;

/** A weekly Monday calendar in Edmonton, paid five days after each period's last day. */
async function weekly(c: Co) {
  return (await callerFor(c.admin).payrollSchedule.scheduleCreate({ financialEntityId: c.entityId, name: "Drivers weekly", frequency: "weekly", anchorDate: "2026-01-05", paymentLagDays: 5, cutoffLagDays: 1, timezone: "America/Edmonton" })).scheduleRef;
}
/** One generated, OPEN period, generated by the administrator. */
async function openPeriod(c: Co) {
  const scheduleRef = await weekly(c);
  const g = await callerFor(c.admin).payrollSchedule.periodsGenerate({ scheduleRef, through: "2026-01-05" });
  const periodRef = g.created[0]!;
  return { scheduleRef, periodRef, periodId: await idOf(periodRef) };
}
async function idOf(periodRef: string) {
  const [[r]] = await pool.query<mysql.RowDataPacket[]>("SELECT id FROM payPeriods WHERE periodRef = ?", [periodRef]);
  return Number(r!.id);
}
const earning = (c: Co, payPeriodId: number) => callerFor(c.admin).payroll.earningPropose({
  earningRef: `ERN-${rnd()}`, employeePayrollProfileId: c.profileId, payPeriodId, earningType: "REG", source: "approved_timesheet",
  quantity: 8, unit: "hour", workedOn: new Date("2026-01-06T12:00:00Z"),
});
const run = (c: Co, payPeriodId: number, payRunRef = `RUN-${rnd()}`) => callerFor(c.admin).payroll.runCreate({ payRunRef, payPeriodId, financialEntityId: c.entityId }).then(() => payRunRef);

d("P2 — tenant boundary", () => {
  it("refuses another organization creating a schedule in its book, or reading, generating or moving its periods", async () => {
    const a = await company(), b = await company();
    expect((await refusal(() => callerFor(b.admin).payrollSchedule.scheduleCreate({ financialEntityId: a.entityId, name: "x", frequency: "weekly", anchorDate: "2026-01-05", timezone: "America/Edmonton" }))).code).toBe("NOT_FOUND");
    const { scheduleRef, periodRef } = await openPeriod(a);
    expect((await refusal(() => callerFor(b.admin).payrollSchedule.periodsGenerate({ scheduleRef, through: "2026-03-01" }))).code).toBe("NOT_FOUND");
    expect((await refusal(() => callerFor(b.admin).payrollSchedule.periodsList({ scheduleRef }))).code).toBe("NOT_FOUND");
    expect((await refusal(() => callerFor(b.admin).payrollSchedule.scheduleRetire({ scheduleRef }))).code).toBe("NOT_FOUND");
    expect((await refusal(() => callerFor(b.admin).payrollSchedule.periodGet({ periodRef }))).code).toBe("NOT_FOUND");
    expect((await refusal(() => callerFor(b.admin).payrollSchedule.periodSubmit({ periodRef }))).code).toBe("NOT_FOUND");
    expect((await refusal(() => callerFor(b.controller).payrollSchedule.periodVoid({ periodRef, reason: "not ours to void" }))).code).toBe("NOT_FOUND");
    expect((await callerFor(b.admin).payrollSchedule.schedulesList()).some(s => s.scheduleRef === scheduleRef)).toBe(false);
    expect((await callerFor(a.hr).payrollSchedule.schedulesList()).some(s => s.scheduleRef === scheduleRef)).toBe(true);
    // Nothing moved.
    expect((await callerFor(a.admin).payrollSchedule.periodGet({ periodRef })).state).toBe("collecting");
  }, 60_000);
});

d("P2 — generation", () => {
  it("generates calendar periods idempotently, with date columns authoritative and legacy instants at local midnight", async () => {
    const a = await company();
    const scheduleRef = await weekly(a);
    const first = await callerFor(a.admin).payrollSchedule.periodsGenerate({ scheduleRef, through: "2026-01-20" });
    expect(first.created).toEqual([`${scheduleRef}-2026-01-05`, `${scheduleRef}-2026-01-12`, `${scheduleRef}-2026-01-19`]);
    expect(first.existing).toEqual([]);
    const again = await callerFor(a.admin).payrollSchedule.periodsGenerate({ scheduleRef, through: "2026-01-27" });
    expect(again.existing).toHaveLength(3);
    expect(again.created).toEqual([`${scheduleRef}-2026-01-26`]);
    const periods = await callerFor(a.hr).payrollSchedule.periodsList({ scheduleRef });
    expect(periods).toHaveLength(4);
    expect(periods[0]).toMatchObject({ periodStartDate: "2026-01-05", periodEndDate: "2026-01-12", paymentDate: "2026-01-16", cutoffDate: "2026-01-12", state: "collecting", stateLabel: "OPEN", createdByUserId: a.admin });
    const [[row]] = await pool.query<mysql.RowDataPacket[]>("SELECT startsOn, endsOn FROM payPeriods WHERE periodRef = ?", [`${scheduleRef}-2026-01-05`]);
    // Edmonton is UTC−7 in January: the legacy instants are the schedule's local midnights.
    expect(new Date(row!.startsOn).toISOString()).toBe("2026-01-05T07:00:00.000Z");
    expect(new Date(row!.endsOn).toISOString()).toBe("2026-01-12T07:00:00.000Z");
    // Generation before the anchor is refused, and the database will not hold two periods on one start.
    expect((await refusal(() => callerFor(a.admin).payrollSchedule.periodsGenerate({ scheduleRef, through: "2025-12-01" }))).code).toBe("BAD_REQUEST");
    const [[n]] = await pool.query<mysql.RowDataPacket[]>("SELECT COUNT(*) AS n FROM payPeriods p JOIN paySchedules s ON s.id = p.payScheduleId WHERE s.scheduleRef = ?", [scheduleRef]);
    expect(Number(n!.n)).toBe(4);
  }, 60_000);

  it("refuses a calendar that cannot generate, and stops generating once retired", async () => {
    const a = await company();
    expect((await refusal(() => callerFor(a.admin).payrollSchedule.scheduleCreate({ financialEntityId: a.entityId, name: "x", frequency: "custom", anchorDate: "2026-01-05", timezone: "America/Edmonton" }))).code).toBe("BAD_REQUEST");
    expect((await refusal(() => callerFor(a.admin).payrollSchedule.scheduleCreate({ financialEntityId: a.entityId, name: "x", frequency: "weekly", anchorDate: "2026-01-05", timezone: "Mars/Olympus" }))).code).toBe("BAD_REQUEST");
    expect((await refusal(() => callerFor(a.admin).payrollSchedule.scheduleCreate({ financialEntityId: a.entityId, name: "x", frequency: "semi_monthly", anchorDate: "2026-01-05", timezone: "America/Edmonton" }))).code).toBe("BAD_REQUEST");
    const { scheduleRef, periodRef } = await openPeriod(a);
    expect(await callerFor(a.admin).payrollSchedule.scheduleRetire({ scheduleRef })).toMatchObject({ status: "retired" });
    expect((await refusal(() => callerFor(a.admin).payrollSchedule.periodsGenerate({ scheduleRef, through: "2026-03-01" }))).code).toBe("PRECONDITION_FAILED");
    expect((await refusal(() => callerFor(a.admin).payrollSchedule.scheduleRetire({ scheduleRef }))).code).toBe("PRECONDITION_FAILED");
    // The period it already generated keeps its state.
    expect((await callerFor(a.admin).payrollSchedule.periodGet({ periodRef })).state).toBe("collecting");
  }, 60_000);
});

d("P2 — the lock", () => {
  it("locks an approved period against earnings, runs and collection, and a reopen releases it", async () => {
    const a = await company();
    const { periodRef, periodId } = await openPeriod(a);
    await earning(a, periodId);
    await callerFor(a.admin).payrollSchedule.periodSubmit({ periodRef });
    // REVIEWING: no new earnings, but a run may still be created.
    expect((await refusal(() => earning(a, periodId))).code).toBe("PRECONDITION_FAILED");
    await callerFor(a.controller).payrollSchedule.periodApprove({ periodRef });
    const got = await callerFor(a.admin).payrollSchedule.periodGet({ periodRef });
    expect(got).toMatchObject({ state: "approved", stateLabel: "APPROVED", approvedByUserId: a.controller, lockedByUserId: a.controller, submittedByUserId: a.admin });
    expect(got.lockedAt).not.toBeNull();
    const e = await refusal(() => earning(a, periodId));
    expect(e.code).toBe("PRECONDITION_FAILED");
    expect(e.message).toMatch(/APPROVED/);
    expect((await refusal(() => run(a, periodId))).code).toBe("PRECONDITION_FAILED");
    // A finalized period is not reopened; an approved one steps back to REVIEWING, then OPEN, with a reason.
    expect((await refusal(() => callerFor(a.controller).payrollSchedule.periodReopen({ periodRef, reason: "no" }))).code).toBe("BAD_REQUEST");
    expect(await callerFor(a.controller).payrollSchedule.periodReopen({ periodRef, reason: "missed a timesheet" })).toMatchObject({ state: "review", locked: false });
    const back = await callerFor(a.admin).payrollSchedule.periodGet({ periodRef });
    expect(back).toMatchObject({ lockedAt: null, approvedByUserId: null, reopenedByUserId: a.controller, reopenReason: "missed a timesheet" });
    await run(a, periodId);
    await callerFor(a.controller).payrollSchedule.periodReopen({ periodRef, reason: "back to collection" });
    expect((await earning(a, periodId)).status).toBeDefined();
  }, 60_000);

  it("refuses collection into a run whose period was locked after the run was created", async () => {
    const a = await company();
    const { periodId } = await openPeriod(a);
    const payRunRef = await run(a, periodId);
    await pool.execute("UPDATE payPeriods SET state = 'approved' WHERE id = ?", [periodId]);
    const r = await refusal(() => callerFor(a.admin).payroll.runCollect({ payRunRef }));
    expect(r.code).toBe("PRECONDITION_FAILED");
    expect(r.message).toMatch(/approved/);
    const [[row]] = await pool.query<mysql.RowDataPacket[]>("SELECT state FROM payRuns WHERE payRunRef = ?", [payRunRef]);
    expect(row!.state).toBe("draft");
  }, 60_000);

  it("re-reads the lock inside the insert, so an approval that lands after the router's check still wins", async () => {
    const a = await company();
    const { periodId } = await openPeriod(a);
    await pool.execute("UPDATE payPeriods SET state = 'approved' WHERE id = ?", [periodId]);
    const trail = (subjectType: "payRun" | "payrollEarning", subjectId: string) => ({ actorUserId: a.admin, procedureName: "test", permission: "payroll.run", subjectType, subjectId, detail: "race" });
    const e = await refusal(() => payrollSvc.insertEarningWithTrail({ earning: { earningRef: `ERN-${rnd()}`, employeePayrollProfileId: a.profileId, payPeriodId: periodId, earningType: "REG", source: "approved_timesheet", quantity: 1, unit: "hour", status: "held" }, trail: trail("payrollEarning", "x") }));
    expect(e.code).toBe("PRECONDITION_FAILED");
    const r = await refusal(() => payrollSvc.createPayRunWithTrail({ run: { payRunRef: `RUN-${rnd()}`, payPeriodId: periodId, financialEntityId: a.entityId, state: "draft" }, trail: trail("payRun", "x") }));
    expect(r.code).toBe("PRECONDITION_FAILED");
    const [[n]] = await pool.query<mysql.RowDataPacket[]>("SELECT (SELECT COUNT(*) FROM payrollEarningEvents WHERE payPeriodId = ?) + (SELECT COUNT(*) FROM payRuns WHERE payPeriodId = ?) AS n", [periodId, periodId]);
    expect(Number(n!.n)).toBe(0);
  }, 60_000);
});

d("P2 — separation of duties (D4)", () => {
  it("refuses the opener, the submitter, and a period whose opener is not on record", async () => {
    const a = await company();
    // The opener: a controller who generated the period may not approve it.
    const scheduleRef = (await callerFor(a.controller).payrollSchedule.scheduleCreate({ financialEntityId: a.entityId, name: "c", frequency: "biweekly", anchorDate: "2026-01-05", timezone: "America/Edmonton" })).scheduleRef;
    const periodRef = (await callerFor(a.controller).payrollSchedule.periodsGenerate({ scheduleRef, through: "2026-01-05" })).created[0]!;
    await callerFor(a.admin).payrollSchedule.periodSubmit({ periodRef });
    expect((await refusal(() => callerFor(a.controller).payrollSchedule.periodApprove({ periodRef }))).code).toBe("FORBIDDEN");
    // Holding the administrator's role and the controller's does not combine into both doors: the administrator's
    // denial of `payroll.approve` wins, so the person who submits cannot reach approval through roles at all.
    const both = await member(a.orgRef, ["payroll_admin", "controller"]);
    const p2 = await openPeriod(a);
    await callerFor(both).payrollSchedule.periodSubmit({ periodRef: p2.periodRef });
    expect((await refusal(() => callerFor(both).payrollSchedule.periodApprove({ periodRef: p2.periodRef }))).code).toBe("FORBIDDEN");
    // The submitter rule stands behind that: a period on record as submitted by the controller is refused to them.
    await pool.execute("UPDATE payPeriods SET submittedByUserId = ? WHERE id = ?", [a.controller, p2.periodId]);
    const r = await refusal(() => callerFor(a.controller).payrollSchedule.periodApprove({ periodRef: p2.periodRef }));
    expect(r.code).toBe("FORBIDDEN");
    expect(r.message).toMatch(/submitted/);
    await pool.execute("UPDATE payPeriods SET submittedByUserId = ? WHERE id = ?", [both, p2.periodId]);
    // A legacy period with no opener on record is refused, not assumed to be someone else's.
    const legacyRef = `PP-LEGACY-${rnd()}`;
    await pool.execute("INSERT INTO payPeriods (periodRef, financialEntityId, startsOn, endsOn, state) VALUES (?,?,'2025-01-01','2025-01-15','review')", [legacyRef, a.entityId]);
    expect((await refusal(() => callerFor(a.controller).payrollSchedule.periodApprove({ periodRef: legacyRef }))).code).toBe("FORBIDDEN");
    // Someone else approves.
    expect((await callerFor(a.controller).payrollSchedule.periodApprove({ periodRef: p2.periodRef })).state).toBe("approved");
  }, 60_000);
});

d("P2 — approving, finalizing and voiding", () => {
  it("refuses approval while a run gathers lines, finalization until every run is paid, and any reopen after", async () => {
    const a = await company();
    const { periodRef, periodId } = await openPeriod(a);
    const payRunRef = await run(a, periodId);
    await callerFor(a.admin).payroll.runCollect({ payRunRef });
    await callerFor(a.admin).payrollSchedule.periodSubmit({ periodRef });
    const r = await refusal(() => callerFor(a.controller).payrollSchedule.periodApprove({ periodRef }));
    expect(r.code).toBe("PRECONDITION_FAILED");
    expect(r.message).toMatch(/still collecting/);
    await callerFor(a.admin).payroll.runSubmit({ payRunRef });
    await callerFor(a.controller).payrollSchedule.periodApprove({ periodRef });
    // Finalizing straight from APPROVED skips PROCESSING.
    expect((await refusal(() => callerFor(a.admin).payrollSchedule.periodFinalize({ periodRef }))).code).toBe("PRECONDITION_FAILED");
    await callerFor(a.admin).payrollSchedule.periodProcess({ periodRef });
    await callerFor(a.controller).payroll.runApprove({ payRunRef, toState: "approved" });
    const unpaid = await refusal(() => callerFor(a.admin).payrollSchedule.periodFinalize({ periodRef }));
    expect(unpaid.code).toBe("PRECONDITION_FAILED");
    expect(unpaid.message).toMatch(/not paid/);
    await callerFor(a.controller).payroll.runApprove({ payRunRef, toState: "processing" });
    await callerFor(a.controller).payroll.runApprove({ payRunRef, toState: "paid" });
    expect(await callerFor(a.admin).payrollSchedule.periodFinalize({ periodRef })).toMatchObject({ state: "closed", stateLabel: "FINALIZED" });
    expect((await callerFor(a.hr).payrollSchedule.periodGet({ periodRef })).finalizedByUserId).toBe(a.admin);
    expect((await refusal(() => callerFor(a.controller).payrollSchedule.periodReopen({ periodRef, reason: "change something" }))).code).toBe("PRECONDITION_FAILED");
    expect((await refusal(() => callerFor(a.controller).payrollSchedule.periodVoid({ periodRef, reason: "change something" }))).code).toBe("PRECONDITION_FAILED");
    expect((await refusal(() => earning(a, periodId))).code).toBe("PRECONDITION_FAILED");
  }, 90_000);

  it("voids only an empty period, with a reason, and a voided period takes nothing", async () => {
    const a = await company();
    const used = await openPeriod(a);
    await earning(a, used.periodId);
    const r = await refusal(() => callerFor(a.controller).payrollSchedule.periodVoid({ periodRef: used.periodRef, reason: "opened by mistake" }));
    expect(r.code).toBe("PRECONDITION_FAILED");
    expect(r.message).toMatch(/earning/);
    const empty = await openPeriod(a);
    expect(await callerFor(a.controller).payrollSchedule.periodVoid({ periodRef: empty.periodRef, reason: "opened by mistake" })).toMatchObject({ state: "voided", stateLabel: "VOIDED" });
    expect(await callerFor(a.hr).payrollSchedule.periodGet({ periodRef: empty.periodRef })).toMatchObject({ voidedByUserId: a.controller, voidReason: "opened by mistake" });
    expect((await refusal(() => earning(a, empty.periodId))).code).toBe("PRECONDITION_FAILED");
    expect((await refusal(() => run(a, empty.periodId))).code).toBe("PRECONDITION_FAILED");
    expect((await refusal(() => callerFor(a.admin).payrollSchedule.periodSubmit({ periodRef: empty.periodRef }))).code).toBe("PRECONDITION_FAILED");
  }, 60_000);
});

d("P2 — who holds which door", () => {
  it("refuses operational roles and the bookkeeper the calendar; the administrator neither approves nor voids; HR only reads", async () => {
    const a = await company();
    const { scheduleRef, periodRef } = await openPeriod(a);
    for (const role of ["dispatcher", "driver", "mechanic", "management", "bookkeeper", "auditor"]) {
      const c = callerFor(await member(a.orgRef, [role]));
      for (const call of [
        () => c.payrollSchedule.schedulesList(),
        () => c.payrollSchedule.periodsList({ scheduleRef }),
        () => c.payrollSchedule.periodGet({ periodRef }),
        () => c.payrollSchedule.scheduleCreate({ financialEntityId: a.entityId, name: "x", frequency: "weekly", anchorDate: "2026-01-05", timezone: "America/Edmonton" }),
        () => c.payrollSchedule.periodsGenerate({ scheduleRef, through: "2026-02-01" }),
        () => c.payrollSchedule.periodFinalize({ periodRef }),
        () => c.payrollSchedule.periodVoid({ periodRef, reason: "not my call" }),
      ]) expect((await refusal(call)).code, role).toBe("FORBIDDEN");
    }
    await callerFor(a.admin).payrollSchedule.periodSubmit({ periodRef });
    expect((await refusal(() => callerFor(a.admin).payrollSchedule.periodApprove({ periodRef }))).code).toBe("FORBIDDEN");
    expect((await refusal(() => callerFor(a.admin).payrollSchedule.periodVoid({ periodRef, reason: "admin voiding" }))).code).toBe("FORBIDDEN");
    expect((await callerFor(a.hr).payrollSchedule.periodGet({ periodRef })).stateLabel).toBe("REVIEWING");
    expect((await refusal(() => callerFor(a.hr).payrollSchedule.periodsGenerate({ scheduleRef, through: "2026-02-01" }))).code).toBe("FORBIDDEN");
    expect((await refusal(() => callerFor(a.hr).payrollSchedule.scheduleRetire({ scheduleRef }))).code).toBe("FORBIDDEN");
    expect((await refusal(() => callerFor(a.worker).payrollSchedule.periodGet({ periodRef }))).code).toBe("FORBIDDEN");
  }, 90_000);
});
