/**
 * Alberta Commercial / Oilfield Safety Template Pack — category 1: Company foundation.
 *
 * Nineteen templates with written bodies. Every one loads as `draft`: it is a
 * starting text a company adapts and a person reviews against the cited
 * instruments before it is anything else. Nothing here asserts a section number
 * of an Act, Regulation or Code — the reference keys carry those, and the
 * references are verified separately.
 *
 * Merge fields: `{{company.name}}`, `{{company.president}}`,
 * `{{company.safetyManager}}`, `{{policy.code}}`, `{{policy.effectiveFrom}}`,
 * `{{policy.version}}`. A field left unresolved at draft time is reported, not
 * hidden.
 */
import type { ContentTemplate } from "../safetyProgramContentTypes";

const revision = "| Version | Date | Change | Prepared by | Approved by |\n|---|---|---|---|---|\n| {{policy.version}} | {{policy.effectiveFrom}} | Initial issue from the LeaseOS Alberta Commercial / Oilfield pack, adapted by {{company.name}} | | {{company.president}} |";
const records = (what: string) => `${what} are controlled records of {{company.name}}: retained under the Document-control and revision policy, available to workers on request, and produced for a regulator, client or auditor when asked. LeaseOS records who acknowledged which version and when.`;
const nonCompliance = "A breach of this policy is dealt with under the Policy enforcement and disciplinary process. The response is proportionate to the breach and considers whether the person was trained, equipped and supervised to comply. Reporting a hazard, an incident or a near miss in good faith is never a breach and never attracts discipline.";

const T = (templateKey: string, summary: string, sections: [string, string][]): ContentTemplate => ({ templateKey, summary, sections: sections.map(([heading, body]) => ({ heading, body })) });

export const COMPANY_FOUNDATION: readonly ContentTemplate[] = [
  T("company_foundation.company_mission_statement", "Who the company is, who it serves and what it will not trade away.", [
    ["Statement", "{{company.name}} exists to deliver safe, dependable commercial transportation, hydrovac, vacuum-truck and industrial services to the clients who rely on us, on time and to the standard they were promised. We compete on the quality of our people, the condition of our equipment and the trust our clients place in us to work on their sites without harm to anyone or anything."],
    ["Commitment", "We will not trade safety, legal compliance or honesty for a load, a schedule or a contract. A job that cannot be done safely and lawfully is a job we will re-plan or decline. Every worker, supervisor, manager and contractor working for {{company.name}} carries this mission with them onto every lease, road and yard."],
    ["Signature and date", "{{company.president}}, President — effective {{policy.effectiveFrom}}"],
  ]),
  T("company_foundation.safety_philosophy_and_safety_motto", "The belief the safety program is built on, in one page.", [
    ["Statement", "We believe every injury, collision and release is preventable, and that the people closest to the work see the hazards first. Our safety philosophy is simple: plan the work, assess the hazards, control them before starting, stop when something changes, and report what we learn so the next crew does not learn it the hard way.\n\nMotto: **Nobody gets hurt. Every load, every site, every day.**"],
    ["Commitment", "Management will provide the training, equipment, time and authority to work this way. Supervisors will lead it on site. Workers will practise it and will stop work when it is not being practised. Contractors will meet the same standard. No production target, client deadline or pay structure at {{company.name}} rewards cutting a corner on safety."],
    ["Signature and date", "{{company.president}}, President — effective {{policy.effectiveFrom}}"],
  ]),
  T("company_foundation.management_commitment_statement", "What management promises, personally and in writing.", [
    ["Statement", "The management of {{company.name}} accepts that health, safety and environmental performance is a management responsibility that cannot be delegated away. We are accountable for establishing this safety management system, resourcing it, leading by example and measuring whether it operates as written."],
    ["Commitment", "Management commits to: providing a written health and safety program and, as a National Safety Code carrier, written and implemented safety and maintenance programs; maintaining a hazard assessment and control process that workers participate in; providing competent supervision and the training each position requires; investigating incidents and near misses and completing corrective actions; reviewing this program at least annually and after any serious incident; and reporting our performance honestly to workers, clients and regulators.\n\nThe President holds overall accountability. {{company.safetyManager}} is the designated safety authority with the standing to stop any operation."],
    ["Signature and date", "{{company.president}}, President — effective {{policy.effectiveFrom}}"],
  ]),
  T("company_foundation.health_and_safety_policy", "The top-level health and safety policy of the company.", [
    ["Purpose", "This policy states the commitment of {{company.name}} to the health and safety of every worker and every person affected by our work, and establishes the health and safety program through which that commitment is carried out."],
    ["Scope", "Every worker, supervisor, manager, owner-operator, contractor, subcontractor and visitor, at every work site, in every vehicle and at every yard or shop operated by {{company.name}}."],
    ["Policy statement", "{{company.name}} will provide a healthy and safe workplace, and will meet or exceed the Alberta Occupational Health and Safety Act, Regulation and Code and every other law that applies to our work. Health and safety has equal standing with production, quality and cost, and takes precedence over them whenever they conflict.\n\nWe will identify the hazards of our work, eliminate them where we can and control them where we cannot; provide the information, training, supervision and equipment needed to work safely; involve workers in the program through hazard assessments, safety meetings and, where the workforce size requires it, a joint work site health and safety committee or a health and safety representative; investigate every incident and near miss; and measure and review this program so that it operates as written."],
    ["Responsibilities", "**Management** establishes, resources and reviews the program and holds supervisors accountable for it. **Supervisors** ensure the work under their direction is planned, assessed and performed safely, that workers are competent for it, and that hazards and incidents are reported. **Workers** take reasonable care of their own health and safety and that of others, follow the safe work practices and procedures, use the equipment provided, report hazards, and refuse dangerous work. **Contractors** meet this policy as a condition of working for {{company.name}}. {{company.safetyManager}} administers the program and reports on it to the President."],
    ["Requirements", "The health and safety program consists of the policies, practices, procedures, plans and records assembled in the LeaseOS Safety Program for {{company.name}}, including hazard assessment and control, safe work practices and procedures, worker orientation and training, inspections, emergency response, incident reporting and investigation, and corrective action. Each is a controlled document with a code, a version, an owner and a review date. Workers acknowledge the policies that apply to them. The program is reviewed at least annually, when the law changes, and after any serious incident."],
    ["Non-compliance", nonCompliance],
    ["Records", records("This policy, its versions, acknowledgements, reviews and the records the program generates")],
    ["References", "Alberta Occupational Health and Safety Act; Occupational Health and Safety Regulation; Occupational Health and Safety Code. Linked reference keys are verified in LeaseOS by a person other than the one who recorded them."],
    ["Revision history", revision],
  ]),
  T("company_foundation.environmental_policy", "The company's environmental commitment.", [
    ["Purpose", "To state the commitment of {{company.name}} to protecting the land, water, air and wildlife where we work, and to set the expectations the environmental program carries out."],
    ["Scope", "All operations, including transportation, hydrovac and vacuum-truck work, fluid and waste handling, fuel storage, shop and yard operations, and the disposal of any material we haul."],
    ["Policy statement", "{{company.name}} will prevent pollution, comply with the Environmental Protection and Enhancement Act and every environmental condition of a client's permit, licence or site rule that applies to our work, handle and dispose of waste only at facilities authorized to receive it, report every release as the law and the client require, and leave every site as we found it or better."],
    ["Responsibilities", "Management resources the environmental program and reviews environmental performance. Supervisors plan environmental controls into every job and ensure spill kits, containment and manifests are in place before work starts. Workers follow the spill prevention, waste segregation, fuel handling and site protection procedures and report every release immediately, however small. {{company.safetyManager}} administers the program."],
    ["Requirements", "Spill prevention and response procedures; secondary containment for fuel and fluid storage; waste manifests and disposal-facility verification for every load hauled; wildlife and watercourse protection; idling limits; environmental incident reporting with regulator and client notification; and site reclamation on completion. Each is a controlled document in the environmental module."],
    ["Non-compliance", nonCompliance],
    ["Records", records("Manifests, disposal receipts, spill reports, containment inspections and environmental incident records")],
    ["References", "Environmental Protection and Enhancement Act (Alberta); client environmental requirements as recorded in client overlays."],
    ["Revision history", revision],
  ]),
  T("company_foundation.quality_policy", "The standard of work the company commits to.", [
    ["Purpose", "To state what {{company.name}} means by quality and how it is delivered and checked."],
    ["Scope", "Every service provided and every record produced for a client."],
    ["Policy statement", "Quality at {{company.name}} means the job was done as scoped, on the equipment promised, by competent people, documented completely and accurately, and delivered when we said it would be. A field ticket, manifest or inspection record is part of the product: an inaccurate record is a defective job."],
    ["Responsibilities", "Management sets the standard and provides the equipment and training to meet it. Dispatch assigns qualified people and suitable equipment. Supervisors and operators deliver the work and complete the records at the time of the work. The office reviews records before they go to the client."],
    ["Requirements", "Work is scoped before dispatch; equipment is inspected before use; records are completed contemporaneously and signed where the client requires it; client complaints and rejected tickets are logged, investigated and closed with a corrective action; and quality performance is reviewed with safety performance."],
    ["Non-compliance", nonCompliance],
    ["Records", records("Field tickets, client sign-offs, complaint logs and corrective actions")],
    ["References", "Client contract terms and site rules as recorded in client overlays."],
    ["Revision history", revision],
  ]),
  T("company_foundation.transportation_safety_policy", "The carrier safety policy an Alberta National Safety Code carrier must have written and implemented.", [
    ["Purpose", "To establish the transportation safety program of {{company.name}} as a National Safety Code carrier. This program is separate from, and in addition to, the occupational health and safety program: in Alberta an OHS program alone does not satisfy the carrier's obligation to have written and implemented safety and maintenance programs."],
    ["Scope", "Every commercial vehicle operated under the carrier's Safety Fitness Certificate, every driver of one, and every person who dispatches, loads or maintains one."],
    ["Policy statement", "{{company.name}} will operate its commercial vehicles safely and lawfully. Our drivers will be qualified, licensed and fit for duty; our vehicles will be inspected before every trip and maintained under a written maintenance program; our loads will be secured; our hours of service will be recorded honestly and never exceeded; and no dispatcher, manager or client will require or reward a driver to violate any of this."],
    ["Responsibilities", "The President is the carrier's accountable officer. {{company.safetyManager}} administers the carrier safety program, monitors the carrier profile and reports on it. Dispatch plans trips that can be completed within hours-of-service limits and never pressures a driver to exceed them. Drivers hold the licence class and endorsements their vehicle requires, complete trip inspections, secure their loads, keep accurate records of duty status, and refuse to drive when fatigued, impaired or in unsafe conditions."],
    ["Requirements", "The program addresses at least: driver qualification, abstracts and licence verification; hours of service and records of duty status; safe vehicle operation, speed, seat belts, distracted driving and defensive driving; drugs and alcohol; load securement and weight compliance; fueling; trip inspections and defect reporting; collision reporting; roadside inspection response; driver training, conduct, evaluation and progressive correction; and carrier profile monitoring. Each element is a controlled document in the commercial trucking module."],
    ["Non-compliance", nonCompliance + " A driver who reports an hours-of-service or equipment concern is protected; a dispatcher or manager who coerces a violation is disciplined."],
    ["Records", records("Driver files, records of duty status, trip inspections, load securement checks, collision reports, roadside inspection reports and carrier profile reviews")],
    ["References", "Alberta Commercial Vehicle Safety Regulation (Traffic Safety Act); Alberta carrier safety program guidance; National Safety Code Standards 9, 10, 13 and 15; federal Commercial Vehicle Drivers Hours of Service Regulations where they apply."],
    ["Revision history", revision],
  ]),
  T("company_foundation.maintenance_policy", "The written maintenance program of a National Safety Code carrier.", [
    ["Purpose", "To establish the written and implemented maintenance program that {{company.name}} maintains as a National Safety Code carrier, so that every commercial vehicle is safe to operate every time it leaves the yard."],
    ["Scope", "Every commercial vehicle and trailer operated under the carrier's Safety Fitness Certificate, and every piece of equipment mounted on one."],
    ["Policy statement", "No vehicle operates with a defect that makes it unsafe. Every vehicle is inspected before and after each trip, every defect is reported and repaired or the vehicle is taken out of service, and every vehicle receives preventive maintenance on schedule and a Commercial Vehicle Inspection Program inspection when due. A repair is released by the technician who performed it and recorded against the unit."],
    ["Responsibilities", "Management funds the maintenance program and does not defer safety-critical repairs. The shop lead schedules preventive maintenance and CVIP inspections and maintains the records. Mechanics perform and record repairs and release the work they did. Drivers inspect, report defects in writing, and refuse a unit with an out-of-service defect. Dispatch does not assign a unit with an open out-of-service defect."],
    ["Requirements", "A preventive maintenance schedule by unit; pre-trip and post-trip inspection procedures with written defect reports; a defect classification that names which defects take a unit out of service; repair authorization and mechanic release; tire and wheel inspection; CVIP tracking with the inspection due date visible to dispatch; and retention of maintenance records for each unit for the period the law requires."],
    ["Non-compliance", nonCompliance],
    ["Records", records("Inspection reports, defect reports, work orders, mechanic releases, CVIP certificates and preventive maintenance records by unit")],
    ["References", "Alberta Commercial Vehicle Safety Regulation; National Safety Code Standard 13 (trip inspections); CVIP requirements."],
    ["Revision history", revision],
  ]),
  T("company_foundation.stop_work_authority", "Every person's authority and duty to stop unsafe work.", [
    ["Purpose", "To give every person working for {{company.name}} the authority, and the duty, to stop any work they believe is unsafe, and to guarantee that they will never be penalized for doing so."],
    ["Scope", "Every worker, supervisor, manager, contractor and visitor, on every site, road and yard."],
    ["Policy statement", "Anyone may stop any task at any time when they see a condition or behaviour they believe could cause injury, damage or a release. The work stays stopped until the concern is addressed to the satisfaction of the person who stopped it and the supervisor. Nobody is disciplined, demoted, reassigned or paid less for stopping work in good faith, even if the concern turns out to be unfounded."],
    ["Responsibilities", "The person stopping work says clearly that they are exercising stop-work authority, makes the area safe, and reports the concern to the supervisor. The supervisor treats the stop as a hazard report, investigates, and either corrects the condition or explains why the work is safe. Management records every stop-work event, reviews it, and thanks the person publicly. Contractors extend the same authority to their workers on our sites."],
    ["Requirements", "Stop-work authority is covered in orientation and on every tailgate meeting. Every stop-work event is recorded in LeaseOS as a safety event with what was stopped, why, what was done and who was involved, and is reviewed for a corrective action."],
    ["Non-compliance", "Retaliation against a person who stopped work is a serious breach dealt with under the Policy enforcement and disciplinary process, up to termination."],
    ["Records", records("Stop-work event records and their corrective actions")],
    ["References", "Alberta Occupational Health and Safety Act — the right to refuse dangerous work; Worker rights and responsibilities policy."],
    ["Revision history", revision],
  ]),
  T("company_foundation.worker_rights_and_responsibilities", "What every worker is entitled to and accountable for.", [
    ["Purpose", "To state the rights every worker of {{company.name}} holds under Alberta law and this program, and the responsibilities that go with them."],
    ["Scope", "Every worker, including owner-operators and contractor workers while on our sites."],
    ["Policy statement", "Every worker has the right to know the hazards of their work and how they are controlled; the right to participate in health and safety through hazard assessments, safety meetings and the committee or representative; and the right to refuse work they reasonably believe is dangerous to themselves or others, without reprisal. With those rights come responsibilities: to work safely and follow the practices and procedures; to use and care for the equipment provided; to report hazards, incidents, near misses and injuries promptly; to be fit for duty; and to cooperate with anyone carrying out a duty under the Act."],
    ["Responsibilities", "Workers exercise and respect these rights. Supervisors make sure workers know them, and act on a refusal or a hazard report immediately. Management guarantees no reprisal and investigates any allegation of one."],
    ["Requirements", "Rights and responsibilities are explained at orientation and posted at the office and shop. A refusal of dangerous work is handled as the Act requires: the worker reports it, the supervisor investigates with the worker and, where one exists, a committee member or representative, the hazard is corrected or the work is shown to be safe, and the worker is not assigned to the task in the meantime except as the law allows."],
    ["Non-compliance", nonCompliance],
    ["Records", records("Orientation acknowledgements and refusal-of-dangerous-work records")],
    ["References", "Alberta Occupational Health and Safety Act — obligations of workers, right to refuse dangerous work, prohibition on discriminatory action."],
    ["Revision history", revision],
  ]),
  T("company_foundation.supervisor_responsibilities", "What a supervisor owns.", [
    ["Purpose", "To define what {{company.name}} expects of every person who directs the work of others, whether their title is supervisor, lead hand, foreman, dispatcher or shop lead."],
    ["Scope", "Every person who directs, assigns or oversees the work of another worker."],
    ["Policy statement", "A supervisor is accountable for the health and safety of the workers under their direction and of anyone affected by that work. A supervisor is competent for the work they supervise, familiar with the Act, Regulation and Code as they apply to it, and present enough to know how the work is actually being done."],
    ["Responsibilities", "Before work: plan the job, confirm the hazard assessment is done with the crew, confirm every worker is trained and competent for their task, and confirm equipment is inspected and fit. During work: enforce the practices and procedures, correct unsafe acts and conditions on the spot, stop work when needed, and keep the crew informed of changes. After work: ensure records are complete, report and investigate incidents and near misses, and follow corrective actions through. Always: model the behaviour expected, take every hazard report and refusal seriously, and never assign a task the worker is not competent or equipped to do."],
    ["Requirements", "Supervisors complete supervisor training within the period set in the training matrix and refresher training on the interval set there. Supervisors hold a tailgate meeting before each job and record it. Supervisors receive and act on inspection findings within their area."],
    ["Non-compliance", nonCompliance],
    ["Records", records("Tailgate meetings, hazard assessments, inspections, incident reports and training records under the supervisor's direction")],
    ["References", "Alberta Occupational Health and Safety Act — obligations of supervisors; Health and Safety Policy."],
    ["Revision history", revision],
  ]),
  T("company_foundation.management_responsibilities", "What management owns.", [
    ["Purpose", "To define the health, safety and environmental accountabilities of the owners and managers of {{company.name}}."],
    ["Scope", "The President, every manager and every person with authority over budgets, staffing, equipment or scheduling."],
    ["Policy statement", "Management is accountable for the existence, resourcing and operation of this safety management system. Management sets the safety culture of {{company.name}} by what it funds, what it measures, what it rewards and what it tolerates."],
    ["Responsibilities", "Establish and approve the program's policies; provide the budget for equipment, training, PPE and maintenance; employ competent supervisors and hold them accountable; ensure a health and safety committee or representative exists where the workforce size requires one and that it functions; review incident investigations and approve corrective actions; review the program at least annually and after serious incidents; communicate performance to workers; and personally participate in inspections, meetings and investigations."],
    ["Requirements", "The President reviews and signs the Health and Safety Policy, Transportation Safety Policy and Maintenance Policy at least annually. Management reviews the COR readiness picture, the training matrix and open corrective actions at least quarterly and records the review."],
    ["Non-compliance", "A manager who fails these responsibilities is accountable to the President; the President is accountable to the company's owners and, under the Act, to the regulator."],
    ["Records", records("Management review records, budget approvals for safety items and signed policies")],
    ["References", "Alberta Occupational Health and Safety Act — obligations of employers; Management commitment statement."],
    ["Revision history", revision],
  ]),
  T("company_foundation.contractor_responsibilities", "What a contractor or subcontractor working for the company must meet.", [
    ["Purpose", "To set the health, safety and environmental conditions under which a contractor, subcontractor or owner-operator works for or alongside {{company.name}}."],
    ["Scope", "Every contractor, subcontractor and owner-operator engaged by {{company.name}}, and their workers, at any site where we are the employer, the prime contractor or the carrier."],
    ["Policy statement", "A contractor working for {{company.name}} meets the same standard as our own workers. They are qualified before they start, oriented to our program and the site, competent and equipped for the work, and accountable for their performance. Where {{company.name}} is the prime contractor, we coordinate the health and safety of every employer on the site."],
    ["Responsibilities", "Contractors provide the qualification documents the contractor management module requires (insurance, WCB clearance, COR or SECOR where applicable, training records, equipment documentation), attend orientation, follow our practices and the client's site rules, report hazards and incidents to us immediately, and correct non-compliance when asked. {{company.name}} qualifies contractors before engagement, orients them, monitors their work, and records non-compliance and corrective actions."],
    ["Requirements", "No contractor starts work without a completed qualification and orientation. Contractor incidents on our sites are reported and investigated as our own. Contractor performance is reviewed at least annually and at the end of each major engagement."],
    ["Non-compliance", "Non-compliance is recorded and corrected; repeated or serious non-compliance suspends or ends the engagement."],
    ["Records", records("Contractor qualification files, orientations, monitoring records, non-compliance notices and performance reviews")],
    ["References", "Alberta Occupational Health and Safety Act — obligations of contractors and prime contractors; contractor management module."],
    ["Revision history", revision],
  ]),
  T("company_foundation.code_of_conduct", "How people are expected to behave at work and on a client's site.", [
    ["Purpose", "To set the standard of personal conduct expected of everyone who represents {{company.name}}."],
    ["Scope", "All workers, supervisors, managers and contractors, at every work site, in every vehicle, and wherever they represent the company."],
    ["Policy statement", "We treat every person with respect. We are honest in what we record and what we say. We follow the law, our policies and the client's rules. We look after the equipment and the sites entrusted to us. We do not come to work impaired, and we do not tolerate violence, harassment, discrimination or bullying in any form."],
    ["Responsibilities", "Every person follows this code and speaks up when it is not followed. Supervisors set the example and address conduct issues promptly. Management applies this code consistently at every level."],
    ["Requirements", "Respectful workplace, violence and harassment prevention, impairment and social-media conduct are each covered in detail in the workplace conduct module; this code binds them together. Client-site behaviour follows the client's rules as recorded in the client overlay in addition to this code."],
    ["Non-compliance", nonCompliance],
    ["Records", records("Acknowledgements of this code and any conduct investigation records")],
    ["References", "Workplace conduct module; Alberta Occupational Health and Safety Code — violence and harassment."],
    ["Revision history", revision],
  ]),
  T("company_foundation.ethics_and_integrity_policy", "Honesty in records, dealings and reporting.", [
    ["Purpose", "To state that {{company.name}} does business honestly and that its records tell the truth."],
    ["Scope", "Every person acting for the company, and every record the company creates."],
    ["Policy statement", "We do not falsify a record of duty status, an inspection, a field ticket, a manifest, a training record or an incident report, and we do not ask anyone else to. We do not offer or accept payments, gifts or favours to win or keep work. We report incidents, releases and violations as the law and our clients require, whether or not anyone else would have noticed. We declare conflicts of interest and step aside from decisions they affect."],
    ["Responsibilities", "Every person keeps accurate records and reports dishonesty they see. Management protects anyone who reports in good faith and investigates every report. The office does not process a record it knows to be false."],
    ["Requirements", "Records are completed by the person who did the work at the time of the work. Corrections are made by amendment with the reason stated, never by rewriting; LeaseOS keeps the original. Concerns may be raised with any manager, {{company.safetyManager}} or the President, and are investigated without retaliation."],
    ["Non-compliance", "Falsification of a record is a serious breach that may end employment or the engagement and may be reported to a regulator where the law requires."],
    ["Records", records("Amendment records, conflict-of-interest declarations and investigation records")],
    ["References", "Transportation Safety Policy; Policy enforcement and disciplinary process."],
    ["Revision history", revision],
  ]),
  T("company_foundation.regulatory_compliance_commitment", "The commitment to know and meet the law that applies to the work.", [
    ["Purpose", "To commit {{company.name}} to identifying, meeting and keeping current with every law, regulation, code, permit and standard that applies to its operations."],
    ["Scope", "All operations, in every jurisdiction where the company works."],
    ["Policy statement", "We will know what the law requires of us before we do the work, and we will do the work that way. Where a client's rule or an industry standard is stricter than the law, we meet the stricter one. Where we are unsure, we find out rather than assume."],
    ["Responsibilities", "{{company.safetyManager}} maintains the register of regulatory references in LeaseOS, has each reference verified against the current instrument by a second person, and monitors for changes. Management approves the program changes a legal change requires. Supervisors and workers apply the requirements as written into the practices and procedures."],
    ["Requirements", "Every policy cites the references it rests on. A cited reference is verified by a person other than the one who recorded it, and re-verified when the instrument changes. A change in the law triggers a policy review. Entering a new jurisdiction adds that jurisdiction's pack as an overlay before work starts there."],
    ["Non-compliance", "A known legal requirement that is not met is a corrective action with an owner and a due date, and is reported to management."],
    ["Records", records("The regulatory reference register, verification records and the reviews a legal change triggered")],
    ["References", "The regulatory reference register in LeaseOS for the jurisdictions selected in the company's program."],
    ["Revision history", revision],
  ]),
  T("company_foundation.client_and_site_rule_compliance", "Meeting each client's site rules on top of the company's own.", [
    ["Purpose", "To establish how {{company.name}} identifies and meets the site rules, orientations and contractual safety requirements of each client."],
    ["Scope", "Every job performed on or for a client site, and every worker and contractor sent there."],
    ["Policy statement", "A client's site rules apply to our people on that site in addition to our own policies. Where the two differ, the stricter applies. Our workers arrive with the client orientation, permits and documentation the client requires, and follow the client's permit-to-work, journey management and emergency procedures while on site."],
    ["Responsibilities", "The office records each client's requirements as a client overlay in LeaseOS, with the source document. Dispatch confirms the assigned worker holds the client orientation and any client-required training before dispatch. Supervisors and workers follow the client's rules on site and report conflicts between the client's rules and our procedures to {{company.safetyManager}}."],
    ["Requirements", "A client overlay is recorded before the first job for that client and reviewed when the client changes its rules. Client-required training and orientations are training requirements in the matrix. A conflict between a client rule and a legal requirement is resolved in favour of the law, and raised with the client."],
    ["Non-compliance", nonCompliance],
    ["Records", records("Client overlays, client orientation records and site-rule conflict reports")],
    ["References", "Client overlays recorded in LeaseOS; contractor management module."],
    ["Revision history", revision],
  ]),
  T("company_foundation.policy_enforcement_and_disciplinary_process", "How breaches are handled: consistently, proportionately, with a record.", [
    ["Purpose", "To set out how {{company.name}} responds when a policy, practice, procedure or site rule is not followed."],
    ["Scope", "All workers, supervisors and managers. Contractor breaches are handled under the Contractor responsibilities policy."],
    ["Policy statement", "Enforcement is consistent, proportionate and recorded. Its purpose is to correct behaviour and protect people, not to punish. The response considers the seriousness of the breach and its potential consequences, whether the person was trained, equipped and supervised to comply, and any prior record. Reporting a hazard, incident or near miss in good faith, refusing dangerous work, or exercising stop-work authority is never a breach."],
    ["Responsibilities", "Supervisors address breaches promptly and document them. {{company.safetyManager}} reviews safety-related breaches for a program cause (missing training, an unworkable procedure) before discipline is decided. Management decides discipline beyond a written warning and applies it consistently. Human resources keeps the record."],
    ["Requirements", "Progressive steps, unless the breach is serious enough to warrant skipping them: coaching and retraining; verbal warning, recorded; written warning; suspension; termination. Serious breaches include working impaired, falsifying a record, disabling a safety device, coercing an hours-of-service violation, violence, and retaliation against a reporter. The person is told what the breach was and what is expected, and may respond before a decision is made."],
    ["Non-compliance", "This policy applies to itself: a supervisor who ignores a breach, or disciplines inconsistently, is subject to the same process."],
    ["Records", records("Disciplinary records, kept confidential in the personnel file")],
    ["References", "Code of conduct; Worker rights and responsibilities; Stop-Work Authority."],
    ["Revision history", revision],
  ]),
  T("company_foundation.document_control_and_revision_policy", "How the program's documents are numbered, versioned, approved, acknowledged and reviewed.", [
    ["Purpose", "To ensure that every document in the safety management system of {{company.name}} is the current, approved version, that its history cannot be quietly rewritten, and that workers acknowledge the version that applies to them."],
    ["Scope", "Every policy, practice, procedure, plan, program and form in the safety management system."],
    ["Policy statement", "Every controlled document has a code assigned by LeaseOS (for example {{policy.code}}), an owner, an approver, a version, an effective date and a review interval. A version is prepared by one person and approved by another. Once approved it is never edited: a change is a new version that supersedes the old one, and the old one is kept. Workers acknowledge the specific version that applies to them. An uncontrolled copy is not the policy."],
    ["Responsibilities", "The document owner drafts and maintains it and schedules its review. The approver (the President for foundation policies; management or {{company.safetyManager}} for others as assigned) approves versions. {{company.safetyManager}} administers document control. Workers acknowledge and follow the current version."],
    ["Requirements", "Codes follow the pattern MODULE-KIND-NNN. Each version records who prepared it, who approved it, when it became effective, and what changed. Versions are hash-chained so that a rewritten history is detectable. Every document is reviewed at least on its review interval and after any incident, legal change or client requirement that affects it; the review is recorded with its outcome. Retired documents are marked retired, never deleted. Printed copies are uncontrolled and carry the version they were printed from."],
    ["Non-compliance", "Working from a superseded or uncontrolled document is a corrective action against document control, not against the worker, unless the worker was told of the current version."],
    ["Records", records("The document register, every version, every acknowledgement, every review and the event ledger")],
    ["References", "LeaseOS Safety & Compliance Program Builder: policy versions, acknowledgements, reviews and the event ledger."],
    ["Revision history", revision],
  ]),
];
