/**
 * Alberta Commercial / Oilfield Safety Template Pack — category 3: Commercial trucking / National Safety Code.
 *
 * Forty-one templates, loaded as drafts. Together with the Transportation Safety Policy and Maintenance
 * Policy in category 1, these are the written carrier safety and maintenance programs an Alberta NSC
 * carrier must have and implement, separate from the OHS program.
 *
 * Hours-of-service limits are deliberately NOT restated here: they live in LeaseOS's hours-of-service rule
 * profiles, which are versioned, verified and read by the duty-status engine. A policy that repeated the
 * figures would be a second source that could disagree with the one enforced; a test holds the HOS
 * policies free of hour figures. The few figures stated (the 24-hour validity of a trip inspection, the
 * 12-month abstract review, the cargo-securement performance and working-load-limit criteria) are ones a
 * reviewer confirms against the instrument as consolidated.
 */
import type { ContentTemplate } from "../safetyProgramContentTypes";
import { form, policy, procedure, program } from "./shared";

const DRIVERS = "Every driver of a commercial vehicle operated by {{company.name}}, including owner-operators under its operating authority, and every person who dispatches, loads, inspects or maintains one.";
const NSC_REFS = "Alberta Commercial Vehicle Safety Regulation and carrier safety program guidance; National Safety Code standards; federal regulations where the carrier operates extra-provincially — as cited by the reference keys linked to this document in LeaseOS.";
const HOS_SOURCE = "The limits that apply are the ones in the LeaseOS hours-of-service rule profile for the jurisdiction and cycle the driver is operating under. That profile is the single source of the figures; this policy does not restate them.";

export const NSC_TRUCKING: readonly ContentTemplate[] = [
  policy("nsc_trucking.driver_qualification_policy", "Who may drive a company commercial vehicle, and how that is established and kept current.", {
    purpose: "To ensure every driver of {{company.name}} is licensed, qualified, trained, medically fit and has an acceptable driving record for the vehicle they operate.",
    scope: DRIVERS,
    statement: "No person drives a commercial vehicle for {{company.name}} until their qualification has been established and recorded, and no driver continues to drive once a qualification lapses. Qualification is established from source documents, not from the driver's word.",
    responsibilities: "{{company.safetyManager}} maintains driver files and approves each driver as qualified. Dispatch assigns only drivers whose qualifications are current for the vehicle and load. Drivers disclose licence changes, suspensions, convictions and medical changes immediately.",
    requirements: "A driver file for every driver holding: the application and employment history; a copy of the licence of the class and endorsements the vehicle requires (including air brake where applicable); the driver abstract obtained at hire and reviewed at least once every 12 months; medical fitness where the licence class requires it; training records (hours of service, load securement, TDG where applicable, defensive driving, winter driving); a road test or evaluation by a competent evaluator; and the record of convictions, collisions and roadside inspections. The driver portfolio in LeaseOS holds these and the training matrix flags gaps.",
    records: "Driver files, abstracts, licence copies, road tests and qualification approvals",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.driver_abstract_review", "Obtaining and reviewing driver abstracts, and what a poor record triggers.", {
    purpose: "To ensure {{company.name}} knows each driver's driving record and acts on it.",
    scope: DRIVERS,
    definitions: "**Driver abstract**: the licensing authority's record of a driver's licence status, convictions, suspensions and demerits. **Commercial abstract**: an abstract that includes commercial driving history where the authority issues one.",
    responsibilities: "{{company.safetyManager}} obtains abstracts with the driver's consent and reviews them. Management decides on any restriction or remedial action. Drivers consent to abstracts and disclose changes between reviews.",
    equipment: "Driver consent on file; access to the licensing authority's abstract service; the driver file in LeaseOS.",
    hazards: "A driver with a pattern of convictions or collisions presents a higher risk to the public and to the carrier's safety rating.",
    steps: "1. Obtain the driver's written consent.\n2. Obtain the abstract at hire, before the driver is dispatched, and at least once every 12 months thereafter, and after any collision or conviction the carrier learns of.\n3. Review it for licence status, class and endorsements, suspensions, convictions and demerits.\n4. Compare it with the carrier's records; a conviction or event on the abstract that the carrier did not know of is investigated.\n5. Record the review outcome: acceptable; acceptable with conditions (coaching, training, monitoring); or not acceptable to drive.\n6. File the abstract and the review in the driver portfolio; set the next review date.",
    emergency: "A suspended or invalid licence discovered at review removes the driver from driving immediately.",
    training: "The reviewer understands the abstract format, the demerit system and the carrier's acceptance criteria.",
    records: "Abstracts, consents and review outcomes",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.licence_verification", "Verifying the licence class, endorsements and validity for the vehicle driven.", {
    purpose: "To confirm that every driver of {{company.name}} holds a valid licence of the class and with the endorsements the vehicle and configuration require.",
    scope: DRIVERS,
    definitions: "**Licence class**: the category of vehicle a licence permits. **Endorsement**: an addition to a licence, such as air brakes, required for certain vehicles.",
    responsibilities: "{{company.safetyManager}} verifies licences against the source. Dispatch checks the class against the unit assigned. Drivers keep their licence valid and carry it.",
    equipment: "The driver portfolio in LeaseOS; the unit's configuration and registered weight; the licensing authority's verification service where available.",
    hazards: "Driving a vehicle beyond the licence class or without a required endorsement is unlawful and uninsured.",
    steps: "1. Inspect the original licence; record the number, class, endorsements, conditions and expiry.\n2. Verify it against the abstract or licensing authority.\n3. Record the classes of unit the driver may operate.\n4. Set the expiry as a requirement in the training matrix so a lapse surfaces before it happens.\n5. Re-verify at renewal and at each abstract review.",
    emergency: "Not applicable.",
    training: "Staff who verify licences know the licence classes and endorsements for the fleet's configurations.",
    records: "Licence copies and verification records",
    references: NSC_REFS,
  }),
  policy("nsc_trucking.hours_of_service_policy", "Hours of service are recorded honestly and never exceeded.", {
    purpose: "To ensure drivers of {{company.name}} do not drive fatigued and that hours of service are recorded accurately and comply with the rules that apply.",
    scope: DRIVERS,
    statement: "Every driver records their duty status accurately, as it happens, and does not exceed the driving, on-duty, cycle or rest limits that apply. " + HOS_SOURCE + " A driver who is fatigued does not drive, whatever the hours available.",
    responsibilities: "Drivers keep accurate records of duty status, carry the records the rules require, and stop driving before a limit is reached. Dispatch plans loads that can be completed within the limits, including travel to and from remote sites. {{company.safetyManager}} audits records against supporting documents (fuel receipts, GPS, tickets) and acts on violations.",
    requirements: "Records of duty status are kept in the form the rules require (ELD for federally regulated carriers unless exempt). Supporting documents are retained. Records are audited on a sample basis at least monthly and in full for any driver with a violation. Violations are investigated for cause, including dispatch pressure. Exemptions and special provisions (such as adverse driving conditions or an emergency) are used only as the rules allow and are recorded with the reason.",
    records: "Records of duty status, supporting documents, audits and violation follow-up",
    references: NSC_REFS + " The hours-of-service rule profile in LeaseOS carries the specific limits.",
  }),
  policy("nsc_trucking.eld_and_logbook_policy", "Use of electronic logging devices and paper logs.", {
    purpose: "To set out how {{company.name}} drivers record duty status on an electronic logging device or, where permitted, on paper.",
    scope: DRIVERS + " Applies to extra-provincial operation where the federal ELD requirement applies, and to any provincial operation where the carrier chooses an ELD.",
    statement: "Where the federal requirement applies, drivers use a certified ELD unless an exemption applies and is recorded. ELD records are not edited to misstate duty status. A paper log is used only when the rules permit it (for example, during an ELD malfunction) and for no longer than they allow.",
    responsibilities: "Drivers log in, select the correct status, annotate edits with the reason, and certify each day's record. Drivers report an ELD malfunction to dispatch immediately. {{company.safetyManager}} manages ELD accounts, malfunction follow-up and record transfer to officials.",
    requirements: "Each unit's ELD is certified and working. Drivers carry the ELD user information, malfunction instructions and blank paper logs. A malfunction is recorded, repaired or replaced within the period the rules allow. Unidentified driving events are assigned or annotated. Records can be transferred at roadside.",
    records: "ELD records, edits with reasons, malfunction reports and unidentified driving reviews",
    references: NSC_REFS,
  }),
  policy("nsc_trucking.sleeper_berth_policy", "When and how the sleeper berth provision is used.", {
    purpose: "To ensure {{company.name}} drivers use the sleeper berth provision correctly and only where it gives real rest.",
    scope: DRIVERS + " Applies to units equipped with a compliant sleeper berth.",
    statement: "Split sleeper-berth rest is used only as the rules allow and only where it gives the driver genuine rest. " + HOS_SOURCE,
    responsibilities: "Drivers record sleeper time accurately and use it for rest. Dispatch does not plan split rest as a way to extend the working day. {{company.safetyManager}} audits split-rest periods.",
    requirements: "The sleeper berth meets the equipment requirements the rules set. Team drivers record their own status. A driver who cannot rest in the berth takes rest in a qualifying facility.",
    records: "Records of duty status showing sleeper periods",
    references: NSC_REFS,
  }),
  program("nsc_trucking.fatigue_management_drivers", "Driver-specific fatigue controls beyond the hours-of-service rules.", {
    purpose: "To reduce fatigue-related risk for {{company.name}} drivers beyond what the hours-of-service limits alone achieve.",
    scope: DRIVERS,
    elements: "Hours-of-service compliance as the floor. Journey planning that includes rest before long or night drives and accounts for travel to remote leases. Recognition of fatigue signs (yawning, drifting, missed exits, heavy eyelids). A no-penalty right for a driver to stop when fatigued. Limiting consecutive night shifts where practicable. Education on sleep, diet and medical conditions such as sleep apnea.",
    responsibilities: "Management sets expectations and does not reward driving fatigued. Dispatch plans rest into journeys and acts on fatigue calls. Drivers arrive rested and stop when fatigued.",
    implementation: "Fatigue is a prompt on the journey plan and FLHA. A driver's fatigue call is logged, the trip is paused or reassigned, and there is no penalty.",
    evaluation: "Collisions, near misses and HOS violations are reviewed for fatigue as a factor. Fatigue calls and their outcomes are reviewed quarterly.",
    records: "Journey plans, fatigue calls and review records",
    references: NSC_REFS,
  }),
  policy("nsc_trucking.dispatch_responsibility", "What dispatch owns for driver and public safety.", {
    purpose: "To define the safety responsibilities of dispatchers and anyone who assigns work to drivers at {{company.name}}.",
    scope: "Every person who assigns loads, routes, units or schedules to drivers.",
    statement: "Dispatch assigns only qualified drivers, fit units and lawful loads, and plans work that can be completed within the hours-of-service limits and in the conditions forecast. Dispatch never asks, pressures or rewards a driver to exceed a limit, drive an unfit unit, or drive in unsafe conditions.",
    responsibilities: "Check driver qualification, hours available and unit status before assigning. Plan routes that account for road bans, weight limits, radio-controlled roads and weather. Monitor journeys and check-ins. Act on a driver's refusal, fatigue call or equipment concern. Record every assignment decision in LeaseOS.",
    requirements: "Dispatch uses the LeaseOS readiness check, which blocks or flags unqualified drivers, units with open out-of-service defects, and loads without required documentation. Overrides require the grant the readiness system names and are recorded with who granted them.",
    records: "Dispatch assignments, readiness checks and overrides",
    references: NSC_REFS,
  }),
  policy("nsc_trucking.driver_responsibility", "What every driver owns.", {
    purpose: "To define the safety responsibilities of every driver of {{company.name}}.",
    scope: DRIVERS,
    statement: "A driver is responsible for the safe operation of their vehicle, the security of their load, the accuracy of their records, and the safety of the public they share the road with.",
    responsibilities: "Hold a valid licence and qualifications and report changes. Arrive fit for duty. Inspect the unit before and after each trip and report defects. Secure the load. Obey traffic law, speed limits and this program. Wear a seat belt. Keep accurate records of duty status. Carry required documents. Report collisions, roadside inspections, convictions and near misses. Refuse to drive when fatigued, impaired or unsafe.",
    requirements: "Drivers acknowledge the carrier safety program policies that apply to them in LeaseOS and complete the training in the matrix for their position.",
    records: "Driver acknowledgements and training records",
    references: NSC_REFS,
  }),
  policy("nsc_trucking.no_coercion_to_violate_hours_of_service", "No one at the company or a client may pressure a driver to break the rules.", {
    purpose: "To protect drivers of {{company.name}} from being coerced, pressured or rewarded to violate hours of service or any other safety rule.",
    scope: "Every manager, dispatcher, supervisor and customer contact who deals with drivers.",
    statement: "No person at {{company.name}}, and no client or shipper we work for, may require, request, induce or reward a driver to exceed an hours-of-service limit, falsify a record, drive a unit with an out-of-service defect, or drive in unsafe conditions. A driver who refuses is protected. " + HOS_SOURCE,
    responsibilities: "Drivers refuse and report any such request. Managers and dispatchers never make one and act on any report. {{company.safetyManager}} investigates reports and records the outcome. Management raises client pressure with the client.",
    requirements: "A report of coercion is investigated as a serious matter. The driver is not disciplined, reassigned or paid less for refusing. Pay structures are reviewed to ensure they do not reward exceeding limits.",
    records: "Coercion reports, investigations and outcomes",
    references: NSC_REFS,
    nonCompliance: "Coercing a driver is a serious breach under the Policy enforcement and disciplinary process, up to termination. Client coercion is raised with the client and may end the relationship.",
  }),
  policy("nsc_trucking.speed_policy", "Speed limits and the company's own lower limits.", {
    purpose: "To prevent speed-related collisions involving {{company.name}} vehicles.",
    scope: DRIVERS,
    statement: "Drivers never exceed the posted limit, drive slower when conditions require it, and never exceed the maximum speed {{company.name}} sets for its units, even where the posted limit is higher. Lease and resource road speeds set by the client or road operator are obeyed.",
    responsibilities: "Drivers obey limits and adjust to conditions. Supervisors review telematics speed events and coach. Management sets the company maximum and the speed governor setting where fitted.",
    requirements: "The company maximum is posted in each unit. Telematics speed events are reviewed weekly. Speeding convictions and repeated events are addressed through the progressive correction system.",
    records: "Telematics speed reports, coaching records and convictions",
    references: NSC_REFS,
  }),
  policy("nsc_trucking.seat_belt_policy", "Seat belts are worn by everyone, always.", {
    purpose: "To protect occupants of {{company.name}} vehicles in a collision or rollover.",
    scope: "Every driver and passenger in any company vehicle or piece of mobile equipment fitted with a seat belt.",
    statement: "The vehicle does not move until every occupant is belted. Seat belts are worn at all times the vehicle is in motion, on public roads, lease roads and sites.",
    responsibilities: "Drivers ensure all occupants are belted. Mechanics and drivers report damaged belts, which take the unit out of service until repaired. Supervisors enforce the policy.",
    requirements: "Seat belts are part of the pre-trip inspection. Telematics seat-belt events are reviewed where available.",
    records: "Inspection records and any enforcement records",
    references: NSC_REFS,
  }),
  policy("nsc_trucking.distracted_driving_and_mobile_device_policy", "No handheld devices while driving, and stricter than the law where it matters.", {
    purpose: "To prevent collisions caused by distraction in {{company.name}} vehicles.",
    scope: DRIVERS,
    statement: "While the vehicle is in motion, drivers do not hold, text, email, browse, type or watch on any device. Hands-free calls are limited to brief, necessary operational calls. Radio communication on radio-controlled roads is permitted as required. Tablets and navigation are set before departure and adjusted only when stopped.",
    responsibilities: "Drivers pull over safely to use a device. Dispatch does not expect an immediate answer from a moving driver. Supervisors enforce the policy.",
    requirements: "Devices are mounted, not held. Messaging from LeaseOS to a driver in motion is queued for when the vehicle stops, where the device supports it. Distracted-driving convictions are addressed through the progressive correction system.",
    records: "Enforcement records and convictions",
    references: NSC_REFS + " Alberta Traffic Safety Act — distracted driving.",
  }),
  policy("nsc_trucking.defensive_driving_requirements", "Defensive driving training and the habits it builds.", {
    purpose: "To ensure {{company.name}} drivers are trained in and practise defensive driving.",
    scope: DRIVERS,
    statement: "Every driver completes defensive driving training before driving and refresher training on the interval in the training matrix, and drives defensively: space cushion, following distance, scanning, anticipating other road users, and adjusting to conditions.",
    responsibilities: "{{company.safetyManager}} arranges training and evaluations. Drivers apply it. Supervisors observe and coach.",
    requirements: "Defensive driving training is a requirement in the training matrix for every driving position. Drivers involved in a preventable collision complete remedial training.",
    records: "Training records and evaluations",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.backing_policy", "Avoid backing; when you must, do it with a spotter or after looking.", {
    purpose: "To prevent backing collisions and struck-by injuries with {{company.name}} units.",
    scope: DRIVERS,
    definitions: "**Spotter**: a person who guides a backing vehicle using agreed signals from a safe position visible to the driver. **GOAL**: get out and look.",
    responsibilities: "Drivers plan to avoid backing, and when backing, use a spotter or get out and look. Spotters stay visible and out of the path. Supervisors plan site layouts to reduce backing.",
    equipment: "Mirrors; backup camera and alarm where fitted; high-visibility clothing for spotters; radio where agreed.",
    hazards: "Blind spots, workers and equipment behind the unit, overhead obstructions, soft ground, and pipelines or wellheads on leases.",
    steps: "1. Plan the approach to avoid backing where possible (pull-through, circle).\n2. If backing is necessary, get out and look at the whole path, including overhead.\n3. Use a spotter wherever one is available; agree signals before moving.\n4. If the spotter is lost from view, stop.\n5. Back slowly, using mirrors and camera, with the alarm working.\n6. Without a spotter, stop and get out and look again as often as needed.",
    emergency: "If anyone is struck, stop, secure the unit, give first aid, and follow the emergency response plan.",
    training: "Backing and spotter signals are covered in driver training and site orientation.",
    records: "Backing incidents and near misses",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.journey_management", "Planning, tracking and closing out each journey.", {
    purpose: "To ensure every journey by a {{company.name}} unit is planned, tracked and closed out, so that a driver in trouble is found quickly.",
    scope: DRIVERS + " Applies to every trip; the level of planning rises with distance, remoteness and conditions.",
    definitions: "**Journey plan**: the route, timing, rest, check-ins, hazards and communication for a trip. **Journey manager**: the person tracking the journey (usually dispatch).",
    responsibilities: "Drivers review and follow the plan and check in. Dispatch prepares or approves the plan, monitors progress and escalates missed check-ins. Supervisors review plans for remote or high-risk journeys.",
    equipment: "LeaseOS route and journey plan; GPS tracking where consented; communication device suited to the route (cellular, radio, satellite).",
    hazards: "Remote roads without coverage, weather, wildlife, fatigue, road bans, radio-controlled roads, unfamiliar sites.",
    steps: "1. Plan the route with LeaseOS, checking road restrictions, bans and radio-controlled roads.\n2. Estimate times including rest and site time, within hours-of-service limits.\n3. Identify hazards and communication gaps on the route.\n4. Set check-in points and times.\n5. Review the plan with the driver.\n6. Track progress; a missed check-in starts escalation as in the working alone procedure.\n7. Close the journey when the driver arrives and reports.",
    emergency: "The plan names what happens if the driver is overdue, breaks down, or has a collision in a no-coverage area.",
    training: "Drivers and dispatchers are trained on journey management.",
    records: "Journey plans, check-ins and escalations",
    references: NSC_REFS,
  }),
  policy("nsc_trucking.winter_driving_policy", "Driving and equipping units for Alberta winter conditions.", {
    purpose: "To prevent winter-related collisions and strandings involving {{company.name}} units.",
    scope: DRIVERS,
    statement: "Units are winterized and carry winter survival equipment. Drivers slow down, increase following distance, and do not drive when conditions exceed what they and the unit can handle safely.",
    responsibilities: "The shop winterizes units before the season. Drivers check road reports before departure and carry the winter kit. Dispatch adjusts schedules to conditions and supports decisions to wait.",
    requirements: "Winter tires or traction devices as required for the route. Winter survival kit: warm clothing, blankets, food, water, flashlight, shovel, traction aids, candles and matches, first aid. Chains where the route requires them. Fuel kept above half a tank in cold weather. Check road reports before departing.",
    records: "Winterization records and kit inspections",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.adverse_weather_shutdown", "When conditions stop the work or the drive, and who decides.", {
    purpose: "To give {{company.name}} a clear, no-penalty way to stop driving or work when weather makes it unsafe.",
    scope: DRIVERS + " Applies to field work as well as driving.",
    definitions: "**Shutdown**: stopping driving or work until conditions improve. **Criteria**: the conditions that trigger a shutdown (visibility, wind, road condition, lightning, extreme cold).",
    responsibilities: "Any driver may stop because of weather without penalty. Supervisors and dispatch may order a shutdown. Management sets criteria and supports shutdowns.",
    equipment: "Weather and road reports; communication device; winter survival kit.",
    hazards: "Whiteout, freezing rain, high wind on high-sided units, lightning on raised equipment, extreme cold, flooding and washouts.",
    steps: "1. Check the forecast and road reports before departure and at each check-in.\n2. Apply the criteria; if met, do not start or stop at the first safe location.\n3. Notify dispatch with the location.\n4. Keep warm, keep the exhaust clear, and check in at the set interval.\n5. Resume only when conditions improve and dispatch agrees.",
    emergency: "A driver stranded in dangerous conditions calls for help and stays with the vehicle unless it is unsafe to do so.",
    training: "Drivers and dispatchers know the criteria and the right to stop.",
    records: "Shutdown decisions and their outcomes",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.mountain_driving_procedures", "Grades, brakes, chains and runaway lanes.", {
    purpose: "To prevent brake failure, runaways and loss of control on mountain routes.",
    scope: DRIVERS + " Applies to routes with long or steep grades.",
    definitions: "**Brake fade**: loss of braking from overheated brakes. **Runaway lane**: an escape ramp for a vehicle that has lost braking. **Chain-up area**: a designated place to install traction devices.",
    responsibilities: "Drivers inspect brakes before the descent and use the correct technique. Dispatch routes drivers new to mountain driving with an experienced driver where practicable.",
    equipment: "Properly adjusted brakes; engine or exhaust brake; chains where required; winter kit.",
    hazards: "Brake overheating, loss of traction, sharp curves, rockfall, rapidly changing weather.",
    steps: "1. Check brake adjustment and air system before starting the grade.\n2. Select a low gear before the descent and let the engine brake control speed.\n3. Use snub braking; never ride the brakes.\n4. Watch for runaway lanes and use one without hesitation if braking is lost.\n5. Chain up at chain-up areas when required.\n6. Check brakes at the bottom and at brake-check areas.",
    emergency: "Loss of brakes: use the runaway lane; warn others; call for help once stopped.",
    training: "Mountain driving training before a first mountain route.",
    records: "Route assignments and training records",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.remote_and_backroad_travel", "Driving lease and resource roads away from help.", {
    purpose: "To keep drivers of {{company.name}} safe on remote lease, resource and backroads.",
    scope: DRIVERS,
    definitions: "**Resource road**: a road built for resource extraction, often narrow, unsurfaced and shared with heavy industrial traffic.",
    responsibilities: "Drivers follow the journey plan and road rules. Dispatch tracks and escalates. Supervisors confirm communication coverage.",
    equipment: "Satellite communicator where there is no coverage; survival kit; spare tire and tools; first aid kit; fire extinguisher.",
    hazards: "No coverage, narrow roads, oncoming heavy traffic, soft shoulders, wildlife, washouts, dust, isolation after a breakdown.",
    steps: "1. Confirm the journey plan and communication method.\n2. Drive at speeds suited to the road and posted by the operator.\n3. Keep right, use lights, and follow radio-call procedures where the road is radio-controlled.\n4. Stop only where the road is wide enough and visible.\n5. Check in at each checkpoint.",
    emergency: "After a breakdown or collision, secure the scene, use the satellite device to call for help, stay with the vehicle, and follow the working-alone escalation.",
    training: "Remote road training for drivers assigned to those routes.",
    records: "Journey plans and check-in records",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.radio_controlled_roads", "Calling kilometres and direction on radio-controlled resource roads.", {
    purpose: "To prevent head-on and passing collisions on radio-controlled roads travelled by {{company.name}} units.",
    scope: DRIVERS + " Applies on any road posted as radio-controlled or where the road operator or client requires radio calling.",
    definitions: "**Radio-controlled road**: a road on which drivers must announce their position, direction and type of vehicle on a posted radio channel. **Kilometre marker**: a posted sign showing distance along the road.",
    responsibilities: "Drivers set the posted channel and call as required. Dispatch loads the road's channel and calling rules into the communication plan. Management ensures units carry a radio programmed for the channels on their routes and that the company holds any licence the channels require.",
    equipment: "A two-way radio programmed for the road's channel; the LeaseOS communication plan for the route.",
    hazards: "Oncoming heavy trucks on narrow roads with limited sight lines.",
    steps: "1. Before entering, set the posted channel.\n2. Call at the entrance and at each posted kilometre marker (or the interval the road requires): road name, kilometre, direction (loaded/empty or up/down as posted), and unit type.\n3. Listen for other traffic and yield as the road's rules require.\n4. Pull out only where the road is wide enough.\n5. Call when leaving the road.",
    emergency: "Use the road channel to warn others of a hazard or collision, then contact dispatch.",
    training: "Drivers are trained on radio calling before travelling radio-controlled roads.",
    records: "Communication plans and radio authorizations",
    references: NSC_REFS + " Road operator and client radio calling requirements recorded in LeaseOS.",
  }),
  procedure("nsc_trucking.load_securement", "Securing cargo to the NSC cargo securement standard.", {
    purpose: "To ensure every load carried by {{company.name}} is contained, immobilized or secured so it cannot leak, spill, blow off, fall off, fall through or shift in a way that affects the vehicle's stability.",
    scope: DRIVERS + " Applies to every load, including equipment, pipe, tools and loose material.",
    definitions: "**Working load limit (WLL)**: the maximum load a tiedown may carry in service. **Aggregate WLL**: the sum of the WLLs of the tiedowns securing an article. **Blocking and bracing**: devices that prevent cargo from moving.",
    responsibilities: "Drivers secure the load and inspect it at the start and during the trip. Loaders assist and do not leave the driver to secure alone. Supervisors check securement on unusual loads.",
    equipment: "Rated chains, straps and binders marked with their WLL; edge protectors; blocking and bracing; tarps; headboard.",
    hazards: "Shifting and falling cargo; tiedown failure; injuries while tightening binders and throwing straps.",
    steps: "1. Plan the securement for the cargo type, following any commodity-specific requirement.\n2. Position cargo against the headboard or blocking where possible.\n3. Use tiedowns with an aggregate WLL of at least one-half the weight of the cargo, and at least the number of tiedowns the standard requires for the article's length and weight.\n4. The securement system must withstand the performance criteria of the standard (0.8 g forward, 0.5 g rearward and 0.5 g sideways).\n5. Protect tiedowns from sharp edges.\n6. Inspect the load and tiedowns before departure, within the distance the standard requires after starting, and at each duty change or stop thereafter.\n7. Re-tension or re-secure as needed.",
    emergency: "A shifted load: stop in a safe place, secure the scene, and re-secure or call for help.",
    training: "Load securement training for every driver, in the training matrix.",
    records: "Securement inspection records and training records",
    references: NSC_REFS + " National Safety Code Standard 10 — cargo securement.",
  }),
  policy("nsc_trucking.weight_and_axle_compliance", "Staying within legal weights, axle loads, dimensions and road bans.", {
    purpose: "To ensure {{company.name}} units operate within legal weights, axle loads and dimensions, and respect road bans.",
    scope: DRIVERS + " Includes dispatchers planning loads and routes.",
    statement: "No unit is loaded beyond its registered weight, its legal axle loads, or the limit of a road or bridge on its route. Over-dimension or over-weight moves are made only under a valid permit and its conditions. Seasonal road bans are respected.",
    responsibilities: "Dispatch plans loads and routes within limits and obtains permits. Drivers check weight where scales or onboard measurement are available and do not accept an overweight load. Management keeps registrations appropriate to the work.",
    requirements: "Registered weights recorded for each unit in LeaseOS. Fluid loads planned by volume and density to stay within limits. Road bans checked before dispatch. Permits carried and their conditions followed. Weight violations are investigated for cause.",
    records: "Scale tickets, permits, and weight violations",
    references: NSC_REFS + " Alberta Traffic Safety Act — vehicle weights and dimensions; road ban orders.",
  }),
  policy("nsc_trucking.dangerous_goods_transportation_road", "Transporting dangerous goods by road under the TDG rules.", {
    purpose: "To ensure {{company.name}} handles, offers for transport and transports dangerous goods in compliance with the Transportation of Dangerous Goods Act and Regulations.",
    scope: "Every worker who handles, offers for transport or transports dangerous goods, and every load that contains them.",
    statement: "Only workers who are adequately trained and hold a valid TDG training certificate issued by {{company.name}} (or who work under the direct supervision of such a person) handle, offer or transport dangerous goods. Dangerous goods are classified, documented, marked, placarded, contained and reported as the Regulations require.",
    responsibilities: "{{company.safetyManager}} administers the TDG program and issues training certificates after training. Consignors classify and document. Drivers verify documents and safety marks before departure and carry the shipping document where the Regulations require. All workers report releases.",
    requirements: "Shipping documents, safety marks and placards meet the Regulations. Means of containment are suitable and in good condition. An emergency response assistance plan is referenced where one is required. Releases and anticipated releases are reported as the Regulations require. Training certificates are employer-specific and tracked in the training matrix with their expiry.",
    records: "TDG training certificates, shipping documents and release reports",
    references: NSC_REFS + " Transportation of Dangerous Goods Act and Regulations.",
  }),
  form("nsc_trucking.shipping_documents", "The shipping document for a load of dangerous goods.", {
    header: "TDG shipping document. Completed by the consignor before the dangerous goods are offered for transport; carried by the driver where the Regulations require.",
    fields: "Consignor name and address. Date. Consignee where required. Description of each dangerous good in the order the Regulations set: UN number, shipping name, primary class, subsidiary class(es) where applicable, packing group. Quantity and unit of measure. Number of means of containment. Emergency response telephone number. ERAP reference number and activation telephone number where an ERAP is required. Any additional information the Regulations require for the goods. Consignor's certification.",
    signoff: "The consignor signs the certification. The driver verifies the document matches the load and the safety marks before departure.",
    retention: "A copy is kept for the period the Regulations require.",
  }),
  procedure("nsc_trucking.placarding", "Displaying the right placards and UN numbers.", {
    purpose: "To ensure {{company.name}} units carrying dangerous goods display the safety marks the Regulations require.",
    scope: "Every unit carrying dangerous goods, and the workers who load and drive it.",
    definitions: "**Placard**: a diamond-shaped safety mark displayed on a large means of containment. **UN number**: the four-digit number identifying a dangerous good.",
    responsibilities: "The consignor provides or confirms the safety marks. The driver checks placards and UN numbers against the shipping document before departure and removes or covers them when the goods are unloaded and the container cleaned.",
    equipment: "Placards and UN number panels for the goods carried; placard holders.",
    hazards: "Wrong or missing placards mislead emergency responders.",
    steps: "1. Determine the placards required from the shipping document and the Regulations.\n2. Display them on each side and each end of the large means of containment, as required.\n3. Display the UN number where the Regulations require it.\n4. Keep placards clean, legible and unobstructed.\n5. Remove or cover placards when the goods are no longer present and the container is cleaned or purged.",
    emergency: "In a release, responders rely on the placards and shipping document: keep the document accessible.",
    training: "Part of TDG training.",
    records: "Shipping documents showing marks required",
    references: NSC_REFS + " Transportation of Dangerous Goods Regulations — safety marks.",
  }),
  procedure("nsc_trucking.fueling_procedures", "Fueling units safely, at stations, cardlocks and bulk tanks.", {
    purpose: "To prevent fires, spills and injuries during fueling of {{company.name}} units.",
    scope: DRIVERS + " Includes bulk-tank fueling in the yard and on site.",
    definitions: "**Bulk tank**: a company-owned fuel storage tank. **Static discharge**: a spark from built-up static electricity.",
    responsibilities: "Drivers follow this procedure and report spills. The yard manager maintains bulk tanks, containment and spill kits.",
    equipment: "Spill kit; fire extinguisher; grounding for portable containers.",
    hazards: "Fire from ignition sources and static; spills; slips on fuel.",
    steps: "1. Shut off the engine and any auxiliary heater.\n2. No smoking or open flame.\n3. Do not leave the nozzle unattended.\n4. Place portable containers on the ground to fill them.\n5. Do not overfill; stop at the automatic shut-off.\n6. Clean up drips; report and clean any spill with the spill kit.\n7. Record fuel in LeaseOS with the unit and odometer.",
    emergency: "Fire: shut off the pump emergency stop, use an extinguisher if safe, evacuate and call for help. Spill: stop the source, contain, report.",
    training: "Covered in driver orientation.",
    records: "Fuel transactions and spill reports",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.pre_trip_inspection", "The daily trip inspection before a unit is driven.", {
    purpose: "To ensure every {{company.name}} unit is inspected before it is driven and that defects are found and dealt with.",
    scope: DRIVERS + " Applies to every commercial vehicle and trailer before it is driven each day.",
    definitions: "**Trip inspection**: the inspection the NSC trip inspection standard requires. **Minor defect**: a defect that must be reported and repaired but does not stop the unit being driven. **Major defect**: a defect that means the unit must not be driven until repaired.",
    responsibilities: "Drivers perform and record the inspection. Mechanics repair reported defects. Dispatch does not dispatch a unit with a major defect.",
    equipment: "The inspection schedule for the vehicle type; LeaseOS inspection form; flashlight; tire gauge.",
    hazards: "Inspecting near traffic; engine and moving parts; climbing.",
    steps: "1. Inspect the unit against the schedule for its type, including brakes, air system, lights, tires and wheels, steering, coupling devices, cargo securement, emergency equipment and any mounted equipment.\n2. Record the inspection with the unit, date, time, location, odometer and the driver's name.\n3. Record every defect found, or that none was found.\n4. A major defect: do not drive; report and tag the unit out of service.\n5. A minor defect: report it; it is repaired before the next inspection unless the schedule allows otherwise.\n6. The inspection report is valid for 24 hours; carry it and produce it on request.",
    emergency: "Not applicable.",
    training: "Every driver is trained on the schedule for the units they drive.",
    records: "Trip inspection reports",
    references: NSC_REFS + " National Safety Code Standard 13 — trip inspections.",
  }),
  procedure("nsc_trucking.post_trip_inspection", "The end-of-trip walkaround and handover to the next driver or the shop.", {
    purpose: "To catch defects that developed during the trip so they are repaired before the unit next leaves.",
    scope: DRIVERS,
    definitions: "**Post-trip inspection**: an inspection at the end of the day's driving.",
    responsibilities: "Drivers inspect and report. The shop reviews reports daily.",
    equipment: "LeaseOS inspection form; flashlight.",
    hazards: "As for the pre-trip inspection.",
    steps: "1. Walk around the unit checking tires, wheels, lights, leaks, damage and securement devices.\n2. Record defects found during the trip and at the walkaround.\n3. Tag out a unit with a major defect.\n4. Hand over to the next driver with a note of any defect.",
    emergency: "Not applicable.",
    training: "Covered with the pre-trip inspection.",
    records: "Post-trip inspection reports",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.defect_reporting", "How a defect is reported, classified, repaired and closed.", {
    purpose: "To ensure every defect on a {{company.name}} unit is reported in writing, classified, and repaired or the unit taken out of service.",
    scope: DRIVERS + " Includes mechanics and the shop lead.",
    definitions: "**Defect**: a condition of the vehicle that does not meet the schedule or the maintenance standard. **Defect report**: the written record of a defect.",
    responsibilities: "Drivers report every defect in LeaseOS. The shop lead classifies and schedules repair. Mechanics repair and release. Dispatch sees the unit's status.",
    equipment: "LeaseOS defect report; photos where helpful.",
    hazards: "Driving with an unreported defect.",
    steps: "1. Record the defect, its location on the unit and its severity.\n2. A major defect takes the unit out of service at once.\n3. The shop lead confirms the classification and creates a work order.\n4. The mechanic who performs the repair records it and releases it.\n5. The defect is resolved in LeaseOS against the release, which is what readiness reads.",
    emergency: "A defect discovered while driving that makes the unit unsafe: stop in a safe place, secure the scene, call dispatch.",
    training: "Drivers and mechanics are trained on the LeaseOS defect process.",
    records: "Defect reports, work orders and releases",
    references: NSC_REFS + " National Safety Code Standard 13.",
  }),
  procedure("nsc_trucking.out_of_service_equipment_procedure", "Taking a unit out of service and returning it.", {
    purpose: "To ensure a unit that is unsafe is taken out of service and not used until a competent person returns it.",
    scope: "Every commercial vehicle, trailer and mounted equipment of {{company.name}}.",
    definitions: "**Out of service**: a status in which the unit must not be driven or used. **Release**: the mechanic's record that the defect has been repaired.",
    responsibilities: "Anyone who finds a major defect tags the unit out. The shop repairs and releases. Dispatch does not assign an out-of-service unit.",
    equipment: "Out-of-service tags; LeaseOS unit status.",
    hazards: "An out-of-service unit used by someone unaware of the defect.",
    steps: "1. Tag the unit at the driver's position and record it out of service in LeaseOS.\n2. Remove the keys where practicable.\n3. Notify dispatch and the shop.\n4. Repair; the mechanic who did the work records the release.\n5. The unit returns to service only when the release is recorded; the tag is removed by the shop.\n6. A roadside out-of-service order is released only as the order requires.",
    emergency: "Not applicable.",
    training: "Drivers, mechanics and dispatchers know the procedure.",
    records: "Out-of-service records and releases",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.cvip_inspection_tracking", "Tracking Commercial Vehicle Inspection Program inspections so none lapse.", {
    purpose: "To ensure every {{company.name}} vehicle required to have a Commercial Vehicle Inspection Program inspection has a current one.",
    scope: "Every vehicle and trailer to which the CVIP requirement applies.",
    definitions: "**CVIP**: the Alberta Commercial Vehicle Inspection Program. **CVIP decal and certificate**: evidence of a passed inspection by a licensed facility.",
    responsibilities: "The shop lead schedules CVIPs before they expire. Drivers check the decal is current. Dispatch does not assign a unit with an expired CVIP.",
    equipment: "LeaseOS unit records with the CVIP expiry.",
    hazards: "Operating without a current CVIP is unlawful and may hide unsafe conditions.",
    steps: "1. Record each unit's CVIP certificate and expiry in LeaseOS.\n2. Schedule the inspection before expiry, at the interval the regulation sets for the vehicle type.\n3. Repair any defects found and re-inspect as required.\n4. Keep the certificate and place the decal.\n5. Units with an expired CVIP are blocked from dispatch.",
    emergency: "Not applicable.",
    training: "Shop staff know the CVIP intervals for the fleet.",
    records: "CVIP certificates and inspection reports by unit",
    references: NSC_REFS,
  }),
  program("nsc_trucking.preventive_maintenance", "The scheduled maintenance at the heart of the written maintenance program.", {
    purpose: "To keep {{company.name}} vehicles safe and reliable through scheduled preventive maintenance.",
    scope: "Every commercial vehicle, trailer and mounted piece of equipment.",
    elements: "A preventive maintenance schedule for each unit by distance, engine hours or time, following the manufacturer's recommendations and adjusted for severe service. Inspection checklists for each service level. Brake inspection and adjustment. Lubrication and fluids. Tires and wheels. Records by unit. Deferral only with the shop lead's recorded decision, never for safety-critical items.",
    responsibilities: "The shop lead maintains the schedule and records. Mechanics perform and record the service. Management funds the program. Dispatch releases units for scheduled service.",
    implementation: "Due services show in LeaseOS by unit. An overdue safety-critical service takes the unit out of service.",
    evaluation: "Completion against schedule and defect trends are reviewed monthly. Roadside inspection results are reviewed for maintenance causes.",
    records: "Maintenance schedules, service records and deferrals by unit",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.repair_authorization", "Who may authorize a repair, in the shop and on the road.", {
    purpose: "To control repairs so they are done by competent people with the right parts, and recorded.",
    scope: "Every repair to a {{company.name}} unit, in the shop, on the road and by third-party vendors.",
    definitions: "**Repair authorization**: approval to perform a repair and incur its cost. **Roadside repair**: a repair by a vendor away from the shop.",
    responsibilities: "The shop lead authorizes shop repairs. Road repairs are authorized by the shop lead or dispatch within the limits set in LeaseOS purchasing. Mechanics release their own work.",
    equipment: "LeaseOS work orders and purchase authorizations.",
    hazards: "Repairs by unqualified people or with wrong parts.",
    steps: "1. The defect or service creates a work order.\n2. The authorizer approves the repair and any vendor within their limit.\n3. The work is performed and recorded with parts used.\n4. The mechanic who did the work releases it.\n5. Vendor invoices are matched to the authorization.",
    emergency: "Not applicable.",
    training: "Authorizers know their limits and vendor requirements.",
    records: "Work orders, authorizations and releases",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.tire_and_wheel_inspection", "Inspecting and maintaining tires and wheels.", {
    purpose: "To prevent tire and wheel failures on {{company.name}} units.",
    scope: "Every unit's tires, rims, wheels and fasteners.",
    definitions: "**Out-of-service criteria**: the conditions under which a tire or wheel makes the vehicle unfit to drive.",
    responsibilities: "Drivers check tires and wheels at every trip inspection. Mechanics maintain them and re-torque after wheel work.",
    equipment: "Tire gauge; tread depth gauge; torque wrench; wheel nut indicators where fitted.",
    hazards: "Blowouts, wheel-offs, and injury during inflation of multi-piece rims.",
    steps: "1. Check inflation, tread depth, cuts, bulges and exposed cords at each trip inspection.\n2. Check wheels for cracks and loose or missing fasteners.\n3. A tire or wheel meeting the out-of-service criteria takes the unit out of service.\n4. Re-torque wheel fasteners after wheel installation at the interval the manufacturer sets.\n5. Inflate multi-piece or split rims only in a restraining device.",
    emergency: "A blowout: grip the wheel, maintain lane, slow gradually, and stop in a safe place.",
    training: "Drivers on trip inspection; mechanics on tire and wheel service.",
    records: "Tire and wheel inspection and service records",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.trailer_coupling_and_uncoupling", "Coupling and uncoupling tractors and trailers safely.", {
    purpose: "To prevent trailer separation, roll-away and crush injuries during coupling and uncoupling.",
    scope: DRIVERS,
    definitions: "**Tug test**: pulling against the trailer brakes to confirm the fifth wheel is locked.",
    responsibilities: "Drivers follow the procedure and never go under a trailer that is not secured.",
    equipment: "Wheel chocks; flashlight; gloves.",
    hazards: "Trailer roll-away; high-hooking; crushing between units; landing gear collapse.",
    steps: "Coupling: 1. Check the fifth wheel is open and greased and the trailer height is correct. 2. Back slowly under the trailer. 3. Tug test in low gear with trailer brakes set. 4. Get out and visually confirm the jaws are closed around the kingpin and the release handle is locked. 5. Connect air and electrical lines. 6. Raise landing gear fully. 7. Check lights and brakes.\nUncoupling: 1. Park on firm, level ground. 2. Set trailer brakes and chock the trailer. 3. Lower landing gear to take weight. 4. Disconnect lines. 5. Release the fifth wheel. 6. Pull clear slowly.",
    emergency: "If the trailer begins to move, get clear; do not try to stop it.",
    training: "Coupling training during driver orientation and road test.",
    records: "Training records and incidents",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.cargo_and_equipment_securement", "Securing tools, hoses and equipment carried on the unit.", {
    purpose: "To prevent tools, hoses, tanks and equipment carried on {{company.name}} units from falling or shifting.",
    scope: DRIVERS,
    definitions: "As in the load securement procedure.",
    responsibilities: "Drivers secure everything on the unit before moving. Supervisors check on site.",
    equipment: "Tool boxes, racks, hose trays, straps and pins.",
    hazards: "Falling objects striking the public; shifting equipment affecting stability.",
    steps: "1. Stow tools in closed boxes.\n2. Secure hoses in trays or on reels with latches closed.\n3. Pin or strap booms, tanks and mounted equipment in travel position.\n4. Walk around before moving.",
    emergency: "Lost equipment on the road: stop safely and report it.",
    training: "Covered in driver orientation.",
    records: "Trip inspection reports",
    references: NSC_REFS + " National Safety Code Standard 10.",
  }),
  procedure("nsc_trucking.collision_reporting", "What to do and report after a collision.", {
    purpose: "To ensure every collision involving a {{company.name}} unit is handled safely, reported to the people who must know, and investigated.",
    scope: DRIVERS,
    definitions: "**Collision**: any contact between a company vehicle and another vehicle, person, animal or object, whatever the damage. **Reportable collision**: one that must be reported to police under the law.",
    responsibilities: "Drivers secure the scene, give aid, report and cooperate. Dispatch notifies management and {{company.safetyManager}}. {{company.safetyManager}} investigates and handles regulatory reporting.",
    equipment: "Collision kit: reporting form, camera (the phone), warning triangles, first aid kit.",
    hazards: "Secondary collisions, fire, dangerous goods release, injury.",
    steps: "1. Stop, secure the scene, set warning devices.\n2. Give first aid and call emergency services where there are injuries, fire or a dangerous goods release.\n3. Report to police where the law requires.\n4. Call dispatch.\n5. Exchange information; do not admit fault.\n6. Photograph the scene, vehicles and road conditions.\n7. Complete the LeaseOS collision report the same day.\n8. Post-incident steps under the impairment policy apply where they lawfully can.\n9. The collision is investigated and assessed for preventability.",
    emergency: "Follow the emergency response plan for injury, fire and dangerous goods release.",
    training: "Drivers are trained on this procedure at orientation.",
    records: "Collision reports, police reports and investigations",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.roadside_inspection_response", "How a driver handles a roadside inspection, and what the office does after.", {
    purpose: "To ensure {{company.name}} drivers cooperate with roadside inspections and that every result is acted on.",
    scope: DRIVERS,
    definitions: "**Roadside inspection**: an inspection of the driver, vehicle or load by an enforcement officer. **Out-of-service order**: an order that the driver or vehicle may not proceed.",
    responsibilities: "Drivers cooperate and report. {{company.safetyManager}} records the result, investigates violations, and follows the carrier profile.",
    equipment: "Documents to be carried: licence, registration, insurance, trip inspection report, records of duty status, permits, shipping documents.",
    hazards: "Inspection areas near traffic.",
    steps: "1. Follow the officer's directions; be courteous.\n2. Produce the documents requested.\n3. If placed out of service, do not proceed; call dispatch.\n4. Photograph and upload the inspection report to LeaseOS the same day.\n5. The office repairs defects, releases the order as it requires, and investigates violations.\n6. The result is checked against the carrier profile when it appears.",
    emergency: "Not applicable.",
    training: "Covered in driver orientation.",
    records: "Roadside inspection reports and follow-up",
    references: NSC_REFS,
  }),
  procedure("nsc_trucking.carrier_profile_monitoring", "Reviewing the carrier profile and acting on what it shows.", {
    purpose: "To ensure {{company.name}} knows its carrier safety record as the regulator sees it and acts before it deteriorates.",
    scope: "The carrier's Safety Fitness Certificate and carrier profile.",
    definitions: "**Carrier profile**: the regulator's record of the carrier's convictions, inspections and collisions. **Risk factor**: the regulator's score derived from the profile.",
    responsibilities: "{{company.safetyManager}} obtains and reviews the profile. Management reviews trends and approves actions.",
    equipment: "The carrier profile from the regulator; LeaseOS carrier profile review record.",
    hazards: "A deteriorating profile can lead to an audit, a lower safety rating, or loss of the operating certificate.",
    steps: "1. Obtain the profile at least quarterly.\n2. Compare every event on it with LeaseOS records; an event the carrier did not know of is investigated.\n3. Review the trend and the risk factor.\n4. Record the review in LeaseOS.\n5. Open corrective actions for trends (driver, unit, violation type).\n6. Report to management.",
    emergency: "Not applicable.",
    training: "The reviewer understands the profile and the risk factor.",
    records: "Carrier profile reviews and corrective actions",
    references: NSC_REFS,
  }),
  policy("nsc_trucking.driver_disciplinary_and_progressive_correction_system", "How driving violations and poor performance are corrected.", {
    purpose: "To correct unsafe driving behaviour at {{company.name}} consistently, and to meet the carrier safety program's requirement for driver discipline and evaluation.",
    scope: DRIVERS,
    statement: "Driving performance is evaluated from convictions, roadside inspections, collisions, telematics events, complaints and observations. Correction is progressive and recorded: coaching, retraining, verbal warning, written warning, suspension from driving, termination. Serious events (impaired driving, falsified records, dangerous driving) may skip steps.",
    responsibilities: "{{company.safetyManager}} reviews driving events and recommends action. Supervisors deliver coaching. Management decides on suspension or termination. Drivers may respond before a decision.",
    requirements: "Every driver is evaluated at least annually. Each event and action is recorded in the driver file. Reporting in good faith, refusing to violate hours of service, and stopping for fatigue or weather are never grounds for discipline.",
    records: "Driver evaluations and correction records",
    references: NSC_REFS,
  }),
];
