/**
 * Alberta Commercial / Oilfield Safety Template Pack — category 2: Occupational health and safety.
 *
 * Thirty-nine templates, loaded as drafts. The same rules as category 1 hold: the company and its
 * officers appear only as merge fields, and no text cites a section number of any instrument — the
 * reference keys carry the citations and are verified separately. Where a figure is given (the 3-metre
 * fall-protection threshold, the 85 dBA noise exposure limit, the 20-worker and 5-worker thresholds for a
 * committee or representative) it is the figure a person must confirm against the Code or Act as
 * consolidated when reviewing the draft.
 */
import type { ContentTemplate } from "../safetyProgramContentTypes";
import { ALL_WORKERS, OHS_REFS, form, policy, procedure, program, swp } from "./shared";

const HIERARCHY = "Controls are chosen in this order: eliminate the hazard; if it cannot be eliminated, control it with engineering controls; then with administrative controls (procedures, training, scheduling, signage); and then with personal protective equipment. A combination is used where one control is not enough, and PPE is never the only control when a higher one is reasonably practicable.";
const FLHA_TRIGGER = "at the start of each job or shift, and again whenever the work, the crew, the equipment, the weather or the site conditions change";

export const OHS: readonly ContentTemplate[] = [
  policy("ohs.hazard_assessment_policy", "Hazards are identified and controlled before work begins, with the workers who do the work.", {
    purpose: "To ensure that {{company.name}} identifies the existing and potential hazards of its work before the work begins, eliminates or controls them, and involves the workers affected in doing so.",
    scope: ALL_WORKERS + " Applies to routine and non-routine work, new work sites, new equipment and new processes.",
    statement: "No work begins until its hazards have been assessed and controlled. {{company.name}} prepares written hazard assessments, dates them, involves the affected workers in preparing them, makes them available to those workers, and repeats them at reasonable intervals, when a new work process is introduced, when a process or operation changes, and before work begins at a new work site. " + HIERARCHY,
    responsibilities: "Management ensures a formal hazard assessment exists for every job type and position and is reviewed. Supervisors ensure a field level hazard assessment is completed " + FLHA_TRIGGER + ", that controls are in place before work starts, and that the crew has signed it. Workers participate in the assessment, follow the controls, and stop and reassess when something changes. {{company.safetyManager}} maintains the hazard register and reviews assessments for completeness.",
    requirements: "Three levels of assessment are used: the formal hazard assessment (by job type, position or task, reviewed at least annually); the job hazard analysis and job safety analysis for specific tasks; and the field level hazard assessment for the day's work on site. Every identified hazard has a named control. Hazards that cannot be controlled are escalated before work starts. Client hazard assessments and permits supplement ours; they do not replace them.",
    records: "Formal hazard assessments, JHAs, JSAs and completed FLHAs",
    references: "Alberta Occupational Health and Safety Code — hazard assessment, elimination and control. " + OHS_REFS,
  }),
  procedure("ohs.formal_hazard_assessment", "How the formal hazard assessment for a job type or position is prepared and kept current.", {
    purpose: "To set out how {{company.name}} prepares, approves and reviews the formal hazard assessment that underpins every task-level and field-level assessment.",
    scope: "Every job type, position and recurring task performed by {{company.name}}, including driving, hydrovac and vacuum-truck operation, shop work and office work.",
    definitions: "**Hazard**: a situation, condition or thing that may be dangerous to health or safety. **Risk**: the combination of how likely harm is and how severe it would be. **Formal hazard assessment**: a written assessment of the hazards of a job type, position or task, prepared before the work is performed and reviewed on a schedule.",
    responsibilities: "{{company.safetyManager}} leads the assessment and keeps the register. Supervisors and experienced workers in the position take part. Management approves the assessment and the controls it requires. Workers are shown the assessment for their position at orientation.",
    equipment: "The formal hazard assessment form in LeaseOS; access to the equipment manuals, SDSs and client requirements relevant to the work.",
    hazards: "The assessment itself considers physical, chemical, biological, ergonomic and psychosocial hazards, including those from mobile equipment, pressure, stored energy, confined spaces, working alone, driving, fatigue, weather, violence and harassment. " + HIERARCHY,
    steps: "1. List the tasks the job type or position performs.\n2. For each task, identify existing and potential hazards with the workers who do it.\n3. Rate each hazard for likelihood and severity.\n4. Assign controls following the hierarchy of controls, naming who is responsible for each.\n5. Rate the residual risk; any residual risk rated high is escalated to management before the task is performed.\n6. Record the assessment, date it, and have it approved.\n7. Communicate it to every worker in the position and link it to their training requirements.\n8. Review it at least annually, when a process or equipment changes, after an incident or near miss involving the task, and before work at a new type of site.",
    emergency: "Where an assessment identifies a hazard with emergency potential (a release, a fire, a rescue), the emergency response plan is checked for a matching procedure; where there is none, one is written before the task is performed.",
    training: "People who lead a formal hazard assessment are trained in hazard identification and risk assessment. Workers are trained on the assessment for their position before performing the tasks it covers.",
    records: "Formal hazard assessments, their approvals and their review history",
    references: "Alberta Occupational Health and Safety Code — hazard assessment, elimination and control. " + OHS_REFS,
  }),
  form("ohs.field_level_hazard_assessment_flha", "The on-site hazard assessment completed by the crew before and during the day's work.", {
    header: `Field Level Hazard Assessment. Completed by the crew ${FLHA_TRIGGER}. Records job number, client, location (legal land description or GPS), date, start time, supervisor and every crew member.`,
    fields: "Task steps for today's work. Hazards identified at this site today, checked against a prompt list (overhead lines, buried facilities, H2S or other atmospheres, pressure and stored energy, mobile equipment and traffic, line of fire, working at heights, confined space, weather and lighting, terrain and access, fatigue, working alone, wildlife, SIMOPS). Control for each hazard and who owns it. Permits in place (client work permit, ground disturbance, hot work, confined space). PPE required. Emergency information: muster point, nearest medical facility, communication method, who holds first aid. A 'changes' block for each reassessment during the shift, with the time and what changed.",
    signoff: "Every crew member signs before starting and again after each reassessment. The supervisor signs that controls are in place. A worker who joins mid-job reviews and signs before starting. Anyone may stop work and reopen the assessment.",
    retention: "The FLHA stays with the crew during the job and is filed at the end of the shift.",
  }),
  form("ohs.job_hazard_analysis_jha", "An analysis of the hazards of a specific job, used to build or check its procedure.", {
    header: "Job Hazard Analysis. Used for a job that is new, non-routine, high-risk or the subject of an incident. Records job title, location type, equipment involved, prepared by, reviewed with (workers), date.",
    fields: "The job described in one paragraph. Each hazard of the job, with its source, who is exposed and how. Likelihood and severity before controls. Controls by type (elimination, engineering, administrative, PPE). Residual likelihood and severity. Whether a safe job procedure or permit is required. Training or competency required to perform the job.",
    signoff: "Prepared by a competent person with workers who perform the job, reviewed by the supervisor, and approved by {{company.safetyManager}} when residual risk is rated medium or higher.",
    retention: "A JHA is kept for as long as the job is performed and for the retention period after, and is reviewed whenever the job or its equipment changes.",
  }),
  form("ohs.job_safety_analysis_jsa", "A step-by-step breakdown of a task with the hazards and controls for each step.", {
    header: "Job Safety Analysis. Used to break a task into its steps and train workers on it. Records task, equipment, prepared by, workers consulted, date.",
    fields: "A numbered list of the task's steps in the order they are performed. For each step: the hazards present and the control for each. Required PPE for the task. Tools and equipment. Permits. Stop points where the worker must check a condition before continuing.",
    signoff: "Prepared with workers who perform the task and approved by the supervisor. Each worker trained on it signs that they have reviewed it.",
    retention: "A JSA is kept with the safe job procedure it supports and reviewed with it.",
  }),
  program("ohs.safe_work_practice_system", "How safe work practices are written, approved, issued and kept current.", {
    purpose: "To ensure {{company.name}} has written safe work practices for the hazards its workers meet, and that they are current, known and followed.",
    scope: "All safe work practices in the program, for every hazard identified in the formal hazard assessments.",
    elements: "A safe work practice is general guidance on how to work safely with a hazard (for example, eye and face protection, housekeeping, heat stress). Each is a controlled document with a code, an owner, a version and a review date. Each is linked to the hazards in the formal hazard assessment that it controls, and to the positions that need it.",
    responsibilities: "{{company.safetyManager}} identifies where a practice is needed and assigns an owner. Owners draft with workers who face the hazard. Management approves. Supervisors ensure the practices are available at the work site and followed. Workers acknowledge the practices for their position.",
    implementation: "A hazard identified in a formal assessment without a controlling practice or procedure is a gap and becomes a corrective action. New practices are introduced in a safety meeting and acknowledged in LeaseOS. Practices are available on the worker's device and in the unit.",
    evaluation: "Each practice is reviewed on its review interval and after any incident or near miss that involves its hazard. Inspections check that practices are followed. The number of hazards without a practice and practices overdue for review are reported to management.",
    records: "The practice register, versions, acknowledgements and reviews",
    references: OHS_REFS,
  }),
  program("ohs.safe_job_procedure_system", "How step-by-step safe job procedures are written for critical and high-risk tasks.", {
    purpose: "To ensure every critical or high-risk task at {{company.name}} has a written, step-by-step safe job procedure that workers are trained on before performing it.",
    scope: "Tasks rated medium residual risk or higher in a formal hazard assessment or JHA, and any task a regulation, client or manufacturer requires a written procedure for.",
    elements: "A safe job procedure sets out, in order, how a specific task is performed safely: preparation, required equipment and PPE, each step with its controls, stop points, and emergency provisions. It is built from a JSA and is a controlled document.",
    responsibilities: "{{company.safetyManager}} maintains the list of tasks that require a procedure. Supervisors and experienced workers draft them. Management approves them. Workers are trained and assessed on them before performing the task.",
    implementation: "A task requiring a procedure is not assigned to a worker who has not been trained on it. Procedures are available at the work site. Where a client procedure applies, it is followed in addition to ours and conflicts are raised with {{company.safetyManager}}.",
    evaluation: "Procedures are reviewed on their review interval, after incidents involving the task, and when equipment or methods change. Observations check that procedures are followed as written; a procedure that is routinely not followed is reviewed for whether it is workable.",
    records: "The procedure register, versions, training records and reviews",
    references: OHS_REFS,
  }),
  procedure("ohs.worker_orientation", "What every new worker is told and shown before starting work.", {
    purpose: "To make sure every worker of {{company.name}} knows the hazards of their work, their rights and responsibilities, and what to do in an emergency before they start work.",
    scope: "Every new worker, a worker returning after an extended absence, a worker transferred to a new position or site, and every contractor worker before starting on a site we control.",
    definitions: "**Orientation**: the structured introduction given before a worker starts work. It is not a substitute for task training or competency assessment.",
    responsibilities: "Supervisors deliver or arrange orientation and confirm it before assigning work. {{company.safetyManager}} maintains the orientation content and checklist. Workers attend, ask questions and sign.",
    equipment: "The orientation checklist in LeaseOS; the health and safety policy; the formal hazard assessment for the worker's position; site maps and emergency information.",
    hazards: "The orientation covers the hazards of the worker's position and site, and the controls for each, from the formal hazard assessment.",
    steps: "Before starting work the worker is shown and acknowledges: 1. the health and safety policy and the worker's rights (to know, to participate, to refuse dangerous work) and responsibilities; 2. stop-work authority; 3. the hazards of their position and site, and the controls; 4. the safe work practices and procedures they will use; 5. required PPE, how to get it and how to care for it; 6. how to report hazards, incidents, near misses and injuries; 7. the emergency response plan, muster points, first aid and emergency contacts; 8. the working alone procedure if it applies; 9. the violence and harassment prevention plan; 10. who the committee members or representative are; 11. the fitness for duty and impairment policies; 12. where to find the program documents. Client orientations are completed in addition when the client requires them.",
    emergency: "No worker starts work before they know how to raise an alarm, where to muster, how to get first aid and how to call for help from the site.",
    training: "Orientation is followed by the task training and competency assessment set in the training matrix for the worker's position.",
    records: "Signed orientation checklists",
    references: "Alberta Occupational Health and Safety Act — obligations of employers to ensure workers are trained and informed. " + OHS_REFS,
  }),
  procedure("ohs.young_and_new_worker_orientation", "Extra steps for young workers and workers new to the industry.", {
    purpose: "To give young workers and workers new to the industry the additional orientation, supervision and protection they need while they gain experience.",
    scope: "Workers under 18, and any worker in their first six months in the trade or industry, regardless of age.",
    definitions: "**Young worker**: a worker under 18 years of age. **New worker**: a worker new to the job, the site or the industry. **Mentor**: an experienced worker assigned to support a new worker.",
    responsibilities: "Management confirms that the work offered to a young worker is permitted for their age under Alberta's employment standards and OHS legislation before hiring. Supervisors assign a mentor, check in daily for the first weeks, and do not assign high-risk tasks until competency is assessed. Mentors model safe work and answer questions. Young and new workers ask when unsure and never guess.",
    equipment: "The standard orientation checklist plus the young and new worker supplement in LeaseOS.",
    hazards: "Inexperience, reluctance to ask questions or refuse unsafe work, unfamiliarity with the site and equipment, and pressure to keep up. Controls: mentoring, closer supervision, restricted task list, explicit encouragement to ask and to stop work.",
    steps: "1. Complete the standard worker orientation.\n2. Confirm and record age-related restrictions on work and hours where the worker is under 18.\n3. Assign a named mentor.\n4. Walk the site with the worker and point out the hazards.\n5. Tell the worker, in plain words, that they can refuse dangerous work and stop unsafe work without penalty.\n6. Give the worker a list of tasks they may not perform until assessed competent.\n7. Supervisor check-ins daily in the first two weeks and weekly until the end of the probation period.\n8. Review the worker's progress at 30, 60 and 90 days and record it.",
    emergency: "Young and new workers are never the only person responsible for an emergency response role until trained and assessed.",
    training: "Task training and competency assessment for each restricted task before it is removed from the list.",
    records: "Young and new worker supplements, mentor assignments and progress reviews",
    references: "Alberta Occupational Health and Safety Act and Code; Alberta Employment Standards Code (young persons). " + OHS_REFS,
  }),
  procedure("ohs.competency_assessment", "How a worker is shown to be competent before working unsupervised.", {
    purpose: "To ensure that a worker at {{company.name}} is competent — adequately qualified, suitably trained and with sufficient experience to perform the work safely without supervision or with only minimal supervision — before being allowed to do so.",
    scope: "Every task and piece of equipment listed in the training matrix as requiring competency assessment, including hydrovac and vacuum-truck operation, commercial driving, and any task with a safe job procedure.",
    definitions: "**Competent**: adequately qualified, suitably trained and with sufficient experience to safely perform work without supervision or with only a minimal degree of supervision. **Assessor**: a competent person designated to assess others on a task. **Practical assessment**: observation of the worker performing the task.",
    responsibilities: "{{company.safetyManager}} designates assessors and maintains the assessment criteria. Assessors assess against the written criteria and record the result honestly. Supervisors do not assign unsupervised work before competency is recorded. Workers never self-assess.",
    equipment: "The competency assessment checklist for the task in LeaseOS; the equipment the task uses; the safe job procedure.",
    hazards: "An assessment is performed under the same controls as the task itself. An assessor stops the assessment if the worker creates an unsafe condition.",
    steps: "1. Confirm the worker holds the prerequisite certificates and training in the matrix.\n2. Knowledge check: the worker explains the hazards, controls and procedure.\n3. Practical: the assessor observes the worker perform the task from preparation to shutdown.\n4. Each criterion is marked met or not met, with notes.\n5. Result: competent, competent with conditions (recorded), or not yet competent with a plan for further training.\n6. The assessor signs; the worker signs that they received the result.\n7. The result is recorded in the worker's portfolio and the training matrix is recomputed.",
    emergency: "Where the task has an emergency procedure (for example, H2S release or a hydrovac line strike), the worker demonstrates or explains it as part of the assessment.",
    training: "Assessors are themselves competent on the task and trained in assessment. Reassessment occurs on the interval set in the matrix and after an incident involving the worker and the task.",
    records: "Competency assessment checklists and results",
    references: "Alberta Occupational Health and Safety Act and Code — definition of competent and employer duties to ensure workers are competent. " + OHS_REFS,
  }),
  policy("ohs.training_and_competency_policy", "Workers are trained and competent for every task they are assigned.", {
    purpose: "To ensure every worker of {{company.name}} holds the training, certificates and competency their position requires before performing the work.",
    scope: ALL_WORKERS,
    statement: "{{company.name}} identifies the training and competency each position requires, provides it, verifies it, and does not assign a task to a worker who does not hold it. External certificates are verified against the issuing body's record, not accepted on sight.",
    responsibilities: "Management funds training and provides time for it. {{company.safetyManager}} maintains the training matrix and verifies certificates. Supervisors check the matrix before assigning work. Dispatch does not dispatch a worker whose required certificate is missing, expired or unverified where the requirement is blocking. Workers keep their certificates current and upload renewals.",
    requirements: "The training matrix in LeaseOS lists, for every position, each required external certificate, company training, client orientation, policy acknowledgement and equipment competency, with its renewal interval and whether a gap blocks dispatch, requires review or is informational. The matrix is recomputed whenever a requirement, a worker or a certificate changes. Expiring certificates are flagged before they expire.",
    records: "Training records, verified certificates, competency assessments and matrix computations",
    references: OHS_REFS,
  }),
  policy("ohs.refresher_training_policy", "Training is repeated before it goes stale, and sooner when something changes.", {
    purpose: "To keep the knowledge and skills of workers at {{company.name}} current.",
    scope: ALL_WORKERS,
    statement: "Training is refreshed on the interval set for it in the training matrix, and earlier when a procedure or piece of equipment changes, when the law changes, after an incident involving the task, or when a worker has not performed the task for an extended period.",
    responsibilities: "{{company.safetyManager}} sets refresher intervals and schedules refresher training. Supervisors identify workers who need early refresher training. Workers attend and complete it.",
    requirements: "Externally certified training is refreshed on the certificate's validity. Company training is refreshed at least every three years unless the matrix sets a shorter interval. A worker who has not performed a high-risk task in twelve months is reassessed before performing it unsupervised.",
    records: "Refresher training records and reassessments",
    references: OHS_REFS,
  }),
  policy("ohs.ppe_policy", "Personal protective equipment: when it is required, who provides it, how it is cared for.", {
    purpose: "To ensure workers at {{company.name}} use the personal protective equipment their work requires, and that it fits, works and is maintained.",
    scope: ALL_WORKERS + " Visitors wear the PPE required by the area they are in.",
    statement: "PPE is the last line of defence and is used when the hazard assessment identifies a hazard that elimination, engineering and administrative controls do not adequately control. Where PPE is required, it is worn. PPE meets the applicable standard named in the OHS Code, fits the worker, and is inspected before use.",
    responsibilities: "{{company.name}} provides task-specific PPE and ensures it meets the required standard. Supervisors enforce its use and replace damaged PPE. Workers wear, inspect and care for their PPE and report defects. Where workers supply basic PPE (for example, safety footwear), the company sets the standard it must meet.",
    requirements: "Minimum site PPE: hard hat, safety glasses, high-visibility clothing, safety footwear, and flame-resistant clothing where the hazard assessment or the client requires it. Task PPE is set by the hazard assessment and safe job procedure: hearing protection, face shields, gloves, respiratory protection, fall protection, chemical protective clothing. Damaged or defective PPE is removed from service. Workers are trained in the use, care and limitations of PPE.",
    records: "PPE issue records, inspection records and training records",
    references: "Alberta Occupational Health and Safety Code — personal protective equipment. " + OHS_REFS,
  }),
  program("ohs.respiratory_protection", "Selection, fit testing, use and care of respiratory protective equipment.", {
    purpose: "To protect workers of {{company.name}} from airborne contaminants and oxygen-deficient atmospheres where other controls cannot reduce exposure enough.",
    scope: "Every task where the hazard assessment identifies an airborne contaminant above its exposure limit or a potentially oxygen-deficient or IDLH atmosphere, including H2S work, tank cleaning, confined space entry, abrasive and silica-generating work, and chemical transfer.",
    elements: "A written code of practice for respiratory protective equipment, as the OHS Code requires where such equipment is used. Hazard assessment and air monitoring to select equipment. Selection of approved equipment appropriate to the contaminant and concentration. Fit testing of tight-fitting respirators before first use and on the interval required, to the CSA standard named in the Code. Workers clean-shaven where a tight-fitting facepiece seals. Pre-use inspection, cleaning, storage and maintenance. Supplied-air and SCBA procedures, including air quality. Training on use, limitations and emergency procedures.",
    responsibilities: "{{company.safetyManager}} administers the program and the code of practice. Supervisors confirm fit tests are current before assigning work. Workers inspect and wear equipment as trained and report any problem with fit or function.",
    implementation: "No worker is assigned a task requiring a tight-fitting respirator without a current fit test for that make, model and size. Fit tests are recorded as training requirements in the matrix so an expired fit test surfaces before dispatch.",
    evaluation: "The program is reviewed annually, when a new contaminant or task is introduced, and after any exposure incident. Air monitoring results are compared with the equipment selected.",
    records: "The respiratory code of practice, fit test records, inspection and maintenance logs, and air monitoring results",
    references: "Alberta Occupational Health and Safety Code — personal protective equipment (respiratory protective equipment). " + OHS_REFS,
  }),
  program("ohs.hearing_conservation", "Noise measurement, control, hearing protection and audiometric testing.", {
    purpose: "To prevent noise-induced hearing loss among workers of {{company.name}}.",
    scope: "Every position or area where workers may be exposed to noise at or above the occupational exposure limit, including hydrovac and vacuum pumps, blowers, pressure washers, compressors and shop tools.",
    elements: "Noise assessment where exposure may exceed the 85 dBA eight-hour exposure limit. Engineering controls (mufflers, enclosures, maintenance) and administrative controls (limiting time in high-noise areas). Hearing protection selected for the exposure, with the areas and tasks where it is mandatory posted. Audiometric testing for exposed workers — a baseline and periodic tests on the schedule the OHS Code sets — by a qualified tester. Training on noise hazards and the use of hearing protection.",
    responsibilities: "{{company.safetyManager}} arranges noise assessment and audiometric testing. Supervisors enforce hearing protection. Workers wear it and attend tests.",
    implementation: "High-noise tasks carry hearing protection in their safe job procedure. Audiometric test due dates are training requirements in the matrix for exposed positions.",
    evaluation: "Noise assessments are repeated when equipment or processes change. Audiometric results showing a shift are followed up with the worker and trigger a review of controls.",
    records: "Noise assessments, audiometric test records (kept confidential) and training records",
    references: "Alberta Occupational Health and Safety Code — noise exposure. " + OHS_REFS,
  }),
  swp("ohs.eye_and_face_protection", "Protecting eyes and face from impact, splash, dust and radiation.", {
    purpose: "To prevent eye and face injuries at {{company.name}}.",
    scope: ALL_WORKERS,
    hazards: "Flying particles from grinding, cutting, high-pressure water and air; chemical and hot-fluid splash; dust and debris from excavation and vacuum work; welding and cutting radiation; sun glare.",
    controls: HIERARCHY + " Guards and shields on tools; splash guards on transfer points; limiting pressure where possible.",
    practice: "Safety glasses with side protection are worn at all times on work sites and in the shop. Goggles are worn where dust or splash is present. A face shield is worn over glasses or goggles for grinding, high-pressure washing, hydrovac digging and chemical transfer. Welding helmets with the correct shade are used for welding and cutting. Eye protection is inspected before use and replaced when scratched or damaged. Eyewash stations or portable eyewash are available where corrosive chemicals are handled, and workers know where they are.",
    ppe: "CSA-approved safety glasses, goggles, face shields and welding helmets as the task requires.",
    training: "Covered in orientation and in the safe job procedures that require specific protection.",
    references: "Alberta Occupational Health and Safety Code — eye and face protection. " + OHS_REFS,
  }),
  swp("ohs.hand_protection", "Choosing and wearing the right gloves for the task.", {
    purpose: "To prevent hand injuries, the most frequent injury in field and shop work.",
    scope: ALL_WORKERS,
    hazards: "Pinch and crush points in coupling, hose handling and rigging; cuts from sharp edges; chemical contact; hot and cold surfaces; vibration; high-pressure injection from hydraulic and water lines.",
    controls: HIERARCHY + " Keep hands out of the line of fire; use tools rather than hands to guide loads and hoses; bleed pressure before touching fittings.",
    practice: "Gloves are selected for the hazard: general work gloves for handling; cut-resistant gloves for sharp material; chemical-resistant gloves matched to the SDS; insulated gloves for hot or cold work; impact-resistant gloves for rigging and hose work. Gloves are not worn near rotating equipment where they could be caught. Rings are removed in the shop. A suspected high-pressure injection injury is treated as a medical emergency even if it looks minor.",
    ppe: "Gloves appropriate to the hazard as named in the hazard assessment and safe job procedure.",
    training: "Covered in orientation, in hose-handling and rigging training, and in WHMIS for chemical-resistant glove selection.",
    references: OHS_REFS,
  }),
  program("ohs.fall_protection", "Preventing falls from height, including the written fall protection plan and rescue.", {
    purpose: "To protect workers of {{company.name}} from falls from height.",
    scope: "Any work where a worker could fall 3 metres or more, or where there is an unusual possibility of injury from a lesser fall (for example, onto equipment, into an excavation or onto a sharp object), including work on tank and truck tops, trailers, loading racks and elevated platforms.",
    elements: "Hierarchy of fall protection: eliminate the need to work at height (ground-level gauging, extended tools); guardrails and fixed platforms; travel restraint; fall arrest. A written fall protection plan where a worker could fall 3 metres or more and is not protected by guardrails or another passive system, naming the hazards, the system, the anchors, the assembly and inspection, and the rescue procedure. Anchors rated for the purpose. Equipment meeting the standards named in the OHS Code, inspected before each use and by a competent person on schedule. A rescue plan that can reach a suspended worker promptly.",
    responsibilities: "{{company.safetyManager}} maintains the plans and equipment inspection records. Supervisors confirm a plan exists and equipment is inspected before work at height. Workers inspect and wear their equipment as trained and never work at height alone.",
    implementation: "Fall protection training and equipment inspection are training requirements for positions that work at height. Units with elevated work areas carry the fall protection equipment their plan names. Client fall protection requirements are followed in addition.",
    evaluation: "Plans are reviewed annually and when equipment, sites or tasks change. Any fall or arrested fall is an incident and triggers review.",
    records: "Fall protection plans, equipment inspection records, rescue drills and training records",
    references: "Alberta Occupational Health and Safety Code — fall protection. " + OHS_REFS,
  }),
  swp("ohs.working_at_heights", "Everyday precautions when working above ground on trucks, tanks and ladders.", {
    purpose: "To prevent falls during routine work above ground level.",
    scope: ALL_WORKERS,
    hazards: "Falls from truck decks, tank tops, trailers, ladders and platforms; slippery surfaces from ice, mud and product; dropped tools striking workers below.",
    controls: HIERARCHY + " Where the fall protection program applies (3 metres or more, or an unusual possibility of injury), its plan is followed.",
    practice: "Use installed ladders, steps and handholds, keeping three points of contact. Do not jump from equipment. Clear ice, mud and product from walking surfaces before climbing. Portable ladders are inspected, set on firm footing, secured, and extend above the landing. Tools are tethered or kept in a bag at height. Barricade the area below overhead work. Do not work at height in high wind or lightning.",
    ppe: "Slip-resistant footwear; fall protection as the fall protection plan requires.",
    training: "Orientation; ladder safety; fall protection training for positions that require it.",
    references: "Alberta Occupational Health and Safety Code — fall protection; ladders. " + OHS_REFS,
  }),
  procedure("ohs.working_alone", "Hazard assessment and effective communication for workers who work alone.", {
    purpose: "To ensure that a worker of {{company.name}} who works alone or in isolation has an effective means of communication and that help can reach them if they are injured or ill.",
    scope: "Any worker working alone or in isolation where assistance is not readily available if there is an emergency or the worker is injured or ill — including solo drivers, hydrovac and vacuum-truck operators on remote leases, and shop and yard staff after hours.",
    definitions: "**Working alone**: working alone or in isolation where assistance is not readily available in an emergency or if the worker is injured or ill. **Check-in**: a contact between the worker and a designated person at a set interval. **Escalation**: the steps taken when a check-in is missed.",
    responsibilities: "Management ensures a working-alone hazard assessment exists for each working-alone situation. Supervisors and dispatch set the check-in interval and act on missed check-ins. Workers carry and test their communication device and check in on time.",
    equipment: "An effective communication system appropriate to the location: cellular phone where coverage is confirmed; two-way radio; satellite communicator or satellite phone where there is no cell coverage; LeaseOS check-in with GPS where consented. A charged backup power source.",
    hazards: "Injury or illness with no one aware; vehicle breakdown or collision in a remote area; weather; wildlife; violence at isolated sites. The hazard assessment sets the check-in interval by hazard: the higher the hazard, the shorter the interval.",
    steps: "1. Complete the working-alone hazard assessment for the location and task.\n2. Confirm the communication method works at the location before the worker is left alone; where electronic communication is not practicable, arrange regular visits or contact at the interval set.\n3. Record the worker's route, destination and expected times in the journey plan.\n4. The worker checks in at the start, at each interval and at the end of the work.\n5. A missed check-in starts escalation: attempt contact immediately; after the interval set in the plan, send someone to the last known location or call emergency services; notify the supervisor.\n6. Record the outcome of every escalation.",
    emergency: "The escalation plan names who goes, how they get there, and when emergency services are called. Workers in no-coverage areas carry a device capable of an SOS signal.",
    training: "Workers who work alone are trained on this procedure, their device and the escalation plan. Dispatch and supervisors are trained on escalation.",
    records: "Working-alone hazard assessments, check-in logs and escalation records",
    references: "Alberta Occupational Health and Safety Code — working alone. " + OHS_REFS,
  }),
  program("ohs.fatigue_management", "Hours, rest and fitness controls for fatigue, for drivers and non-drivers.", {
    purpose: "To prevent fatigue-related incidents at {{company.name}}.",
    scope: ALL_WORKERS + " Commercial drivers are also bound by hours-of-service rules; this program adds to them and does not replace them.",
    elements: "Limits on consecutive shifts, shift length and minimum rest between shifts, set by {{company.name}} for non-driving work. Hours-of-service compliance for drivers. Journey planning that accounts for travel time to and from remote sites. Recognition of fatigue signs. A no-penalty process for a worker to report being too tired to work or drive safely. Scheduling that avoids long night-shift runs where practicable.",
    responsibilities: "Management sets hours and rest limits and does not reward exceeding them. Dispatch and supervisors schedule within the limits and act on fatigue reports. Workers arrive rested, report fatigue, and stop work or pull over when fatigued.",
    implementation: "Shift and duty records in LeaseOS are checked against the limits. A fatigue report is treated as a hazard report and the work is reassigned or delayed. Fatigue is a prompt on the FLHA.",
    evaluation: "Incidents and near misses are reviewed for fatigue as a factor. Hours worked against the limits are reported to management quarterly.",
    records: "Hours of work and duty records, fatigue reports and their outcomes",
    references: "Alberta Occupational Health and Safety Code — hazard assessment (fatigue as a hazard); hours-of-service regulations for drivers. " + OHS_REFS,
  }),
  policy("ohs.fitness_for_duty", "Workers arrive able to work safely, and say so when they are not.", {
    purpose: "To ensure that workers of {{company.name}} are physically and mentally able to perform their work safely.",
    scope: ALL_WORKERS,
    statement: "A worker who is unfit for duty — through fatigue, illness, injury, impairment, medication, emotional distress or any other cause — does not perform safety-sensitive work. Workers are expected to report when they are not fit, and are not penalized for doing so.",
    responsibilities: "Workers assess their own fitness at the start of each shift and report concerns. Supervisors watch for signs of unfitness, remove a worker from safety-sensitive work when they reasonably believe the worker is unfit, and follow this policy. Management provides reasonable accommodation to the point of undue hardship for disability-related limitations.",
    requirements: "A supervisor who removes a worker from work records the observations, arranges safe transportation home where needed, and follows up. Medical fitness requirements for commercial drivers are met and tracked in the training matrix. Return to work after an injury or illness follows a written plan. Personal information is kept confidential.",
    records: "Fitness-for-duty observations, removal and return-to-work records (kept confidential)",
    references: "Alberta Occupational Health and Safety Code — employer and worker obligations; Alberta Human Rights Act (accommodation). " + OHS_REFS,
  }),
  policy("ohs.alcohol_drug_and_impairment_policy", "No one works impaired, and help is available.", {
    purpose: "To prevent incidents caused by impairment from alcohol, cannabis, illicit drugs or medication at {{company.name}}.",
    scope: ALL_WORKERS + " Applies on duty, on call, in company vehicles and at client sites.",
    statement: "No worker reports for work or works while impaired by alcohol, cannabis, illicit drugs or medication. Possession, use or sale of alcohol, cannabis or illicit drugs on company or client premises or in company vehicles is prohibited. The legality of a substance does not make impairment at work acceptable. Workers who have a dependency are encouraged to seek help and are accommodated as the law requires.",
    responsibilities: "Workers report fit for duty, disclose medication that may affect their safe performance (the effect, not the diagnosis), and report a co-worker they believe is impaired. Supervisors act on reasonable cause, remove the worker from work, and follow the procedure. Management ensures any testing is done only where the law permits and under a separately approved testing procedure.",
    requirements: "Reasonable-cause and post-incident steps are set out in a written procedure approved by management. Safety-sensitive positions are identified. Any testing uses accredited collectors and laboratories. A worker with a dependency is referred to assistance and accommodated to the point of undue hardship. Client and site requirements that are stricter apply on their sites.",
    records: "Reasonable-cause documentation, referral records and any test records (kept confidential)",
    references: "Alberta Occupational Health and Safety Code — impairment; Alberta Human Rights Act; client site requirements. " + OHS_REFS,
    nonCompliance: "Working impaired, or refusing to cooperate with the procedure where it lawfully applies, is a serious breach under the Policy enforcement and disciplinary process. Self-disclosure of a dependency before an incident or a reasonable-cause event is treated as a request for help, not a breach.",
  }),
  swp("ohs.heat_stress", "Preventing heat illness during summer work and hot tasks.", {
    purpose: "To prevent heat-related illness among workers of {{company.name}}.",
    scope: ALL_WORKERS,
    hazards: "Heat exhaustion and heat stroke from high temperature and humidity, direct sun, heavy work, flame-resistant clothing and chemical suits, and hot equipment.",
    controls: HIERARCHY + " Schedule heavy work for cooler parts of the day; provide shade and cool rest areas; rotate workers; acclimatize new and returning workers over their first days.",
    practice: "Supervisors check the humidex or heat index before and during the shift and increase rest breaks as it rises. Cool drinking water is available at every site and workers drink regularly, not only when thirsty. Workers watch each other for symptoms: heavy sweating, dizziness, headache, nausea, confusion. A worker with symptoms stops work, rests in shade and is cooled. Confusion, loss of consciousness or hot dry skin is treated as heat stroke: call emergency services and cool the worker immediately.",
    ppe: "Light, breathable clothing where FR is not required; cooling vests where FR or chemical suits are worn; sun protection.",
    training: "Heat stress awareness before the summer season and for new workers.",
    references: "Alberta Occupational Health and Safety Code — hazard assessment (temperature extremes). " + OHS_REFS,
  }),
  swp("ohs.cold_stress", "Preventing cold injury in Alberta winters.", {
    purpose: "To prevent cold-related injury and illness among workers of {{company.name}}.",
    scope: ALL_WORKERS,
    hazards: "Frostbite, hypothermia, and trench foot from cold air, wind chill, wet clothing and contact with cold metal and fluids; reduced dexterity increasing other injuries; vehicle breakdown in the cold.",
    controls: HIERARCHY + " Heated shelters or vehicles for warm-up breaks; scheduling outdoor work to the warmer part of the day; windbreaks.",
    practice: "Supervisors check the wind chill before and during the shift and set warm-up breaks accordingly; at extreme wind chill, non-essential outdoor work is postponed. Workers dress in layers, keep spare dry clothing and gloves, and cover exposed skin. Workers watch each other for white or waxy skin, numbness, shivering, confusion. Units carry winter survival kits. Working alone in extreme cold uses a shorter check-in interval. A worker showing signs of hypothermia is moved to a warm place and medical help is called.",
    ppe: "Insulated, layered clothing; insulated boots; insulated gloves and liners; face protection; FR outer layers where required.",
    training: "Cold stress awareness before the winter season and for new workers.",
    references: "Alberta Occupational Health and Safety Code — hazard assessment (temperature extremes). " + OHS_REFS,
  }),
  swp("ohs.ergonomics_and_manual_handling", "Lifting, carrying, hose handling and repetitive work without injury.", {
    purpose: "To prevent musculoskeletal injuries at {{company.name}}.",
    scope: ALL_WORKERS,
    hazards: "Back, shoulder and knee injuries from lifting, pushing and pulling; handling heavy hoses, tubes and fittings; awkward postures in trucks and shops; vibration; long periods of driving.",
    controls: HIERARCHY + " Mechanical aids (hose reels, booms, carts, hoists); team lifts; job rotation; adjustable seating in units.",
    practice: "Assess the load before lifting: weight, shape, grip, path. Use mechanical aids where they are provided. Lift with the load close to the body, back straight, bending at the knees, without twisting. Get help for heavy or awkward loads. Handle vacuum and hydrovac hoses with the boom and reel where fitted rather than dragging by hand. Adjust the seat and mirrors before driving and take stretch breaks on long trips. Report discomfort early.",
    ppe: "Gloves suited to the grip needed; anti-vibration gloves where vibration is a hazard.",
    training: "Manual handling training at orientation; hose-handling training for vacuum and hydrovac positions.",
    references: "Alberta Occupational Health and Safety Code — ergonomics and manual handling. " + OHS_REFS,
  }),
  swp("ohs.housekeeping", "Keeping sites, units and shops clean, clear and orderly.", {
    purpose: "To prevent slips, trips, fires and struck-by injuries through good housekeeping.",
    scope: ALL_WORKERS,
    hazards: "Tripping on hoses, tools and debris; slipping on spilled fluids; fire from oily rags and combustibles; blocked exits and emergency equipment; falling objects from overloaded shelves.",
    controls: HIERARCHY + " Designated storage for tools, hoses and materials; spill kits; covered metal containers for oily rags.",
    practice: "Clean up as you go. Store hoses on reels or racks, not across walkways. Clean spills immediately using the spill kit. Keep exits, fire extinguishers, eyewash and electrical panels unobstructed. Put oily rags in covered metal containers. Keep truck decks and cabs free of loose objects. End every shift and job with a housekeeping check.",
    ppe: "Gloves for handling debris; eye protection when sweeping or using compressed air.",
    training: "Covered in orientation and reinforced in inspections.",
    references: OHS_REFS,
  }),
  swp("ohs.slips_trips_and_falls", "Preventing same-level falls on sites, yards and in the shop.", {
    purpose: "To prevent slips, trips and falls on the same level.",
    scope: ALL_WORKERS,
    hazards: "Ice and snow, mud, spilled fluids, uneven ground on leases, hoses and cables, poor lighting, getting in and out of vehicles.",
    controls: HIERARCHY + " Sand or ice melt on walkways; lighting; hose and cable management; mats at doorways.",
    practice: "Walk, do not run. Keep eyes on the path. Use three points of contact getting in and out of vehicles. Wear footwear suited to the surface and ice cleats in winter. Clear or mark hazards as soon as they are seen. Report poor lighting and damaged surfaces.",
    ppe: "Slip-resistant safety footwear; ice cleats in winter conditions.",
    training: "Orientation; winter safety briefing each season.",
    references: OHS_REFS,
  }),
  procedure("ohs.hazardous_energy_control_lockout_tagout", "Isolating and locking out energy before working on equipment.", {
    purpose: "To protect workers of {{company.name}} from the unexpected release of hazardous energy while servicing, maintaining, repairing or clearing equipment.",
    scope: "All work on or near machinery, vehicles, pumps, blowers, hydraulic systems, pressure systems, electrical equipment and any equipment with stored energy, in the shop and in the field.",
    definitions: "**Hazardous energy**: electrical, mechanical, hydraulic, pneumatic, chemical, thermal, gravitational or other energy that could harm a worker. **Isolation**: disconnecting or blocking energy so it cannot reach the equipment. **Personal lock**: a lock controlled by one worker, keyed individually. **Zero energy state**: the condition where all energy is isolated and stored energy is released or restrained.",
    responsibilities: "Supervisors ensure lockout procedures exist for equipment and are followed. Every worker working on isolated equipment applies their own personal lock. The shop lead maintains equipment-specific isolation procedures and the lock inventory.",
    equipment: "Personal locks and keys; lockout hasps and group lock boxes; tags identifying the worker; blocking and cribbing; pressure gauges and bleed valves; a voltage tester for electrical isolation.",
    hazards: "Unexpected start-up, stored pressure in hydraulic and vacuum systems, raised booms and bodies under gravity, residual heat, and electrical energy. " + HIERARCHY,
    steps: "1. Identify every energy source using the equipment's isolation procedure.\n2. Notify affected workers that the equipment will be locked out.\n3. Shut the equipment down by its normal controls.\n4. Isolate each energy source at its isolating device.\n5. Each worker applies their personal lock and tag to each isolating device (or to the group lock box when a group lockout is used).\n6. Release or restrain stored energy: bleed pressure, block raised components, allow to cool, discharge capacitors.\n7. Verify zero energy by attempting to start the equipment and testing, then return controls to off.\n8. Perform the work.\n9. On completion, check the area, confirm workers are clear, remove blocks, and each worker removes only their own lock.\n10. A lock left by an absent worker is removed only under a written procedure that confirms the worker is not in danger, is authorized by the supervisor, and is recorded.",
    emergency: "If energy is released unexpectedly, stop, make the area safe, give first aid, and report it as a serious incident.",
    training: "Every worker who works on equipment is trained on this procedure and on the isolation procedure for the equipment they work on, before doing so.",
    records: "Equipment isolation procedures, lock assignments, group lockout records and lock-removal records",
    references: "Alberta Occupational Health and Safety Code — controlling hazardous energy. " + OHS_REFS,
  }),
  swp("ohs.machine_guarding", "Keeping guards in place on rotating and moving equipment.", {
    purpose: "To prevent contact with moving parts of machinery at {{company.name}}.",
    scope: ALL_WORKERS,
    hazards: "Entanglement in rotating shafts, belts, PTOs and blowers; crushing and shearing between moving parts; flying parts from failure.",
    controls: HIERARCHY + " Fixed guards on drives, belts, PTOs and couplings; interlocked guards where access is needed; emergency stops.",
    practice: "Never operate equipment with a guard removed or bypassed. A guard is removed only under lockout for maintenance and is replaced before the equipment is returned to service. Loose clothing, long hair, jewelry and gloves are kept away from rotating parts. Report a missing or damaged guard and tag the equipment out of service.",
    ppe: "Close-fitting clothing; hair secured; eye protection.",
    training: "Orientation; equipment-specific training.",
    references: "Alberta Occupational Health and Safety Code — safeguards. " + OHS_REFS,
  }),
  swp("ohs.electrical_safety", "Working safely with electrical equipment and near power lines.", {
    purpose: "To prevent electrical shock, burns and electrocution at {{company.name}}.",
    scope: ALL_WORKERS + " Includes work near overhead and buried power lines by booms, cranes, dump bodies and hydrovac equipment.",
    hazards: "Contact with energized conductors; damaged cords and tools; wet conditions; overhead power lines contacted by booms and raised equipment; buried cables struck during excavation.",
    controls: HIERARCHY + " Ground-fault protection on portable tools; locating buried facilities before digging; maintaining the safe limits of approach to overhead lines.",
    practice: "Only qualified persons perform electrical work. Inspect cords and tools before use and remove damaged ones from service. Use GFCI protection outdoors and in wet areas. Before raising a boom, body or mast, identify overhead lines and keep every part of the equipment and load beyond the safe limit of approach the OHS Code sets for that voltage, confirmed with the utility; use a spotter where the distance may be approached. Never assume a line is de-energized. If equipment contacts a line, stay in the cab; if you must leave because of fire, jump clear without touching the equipment and ground at the same time, then shuffle away.",
    ppe: "Insulated gloves and tools for electrical work by qualified persons; standard PPE otherwise.",
    training: "Orientation; power-line awareness for operators of booms, cranes, dump bodies and hydrovac units.",
    references: "Alberta Occupational Health and Safety Code — electrical safety and overhead power lines. " + OHS_REFS,
  }),
  swp("ohs.fire_prevention", "Preventing fires and being ready to put out a small one.", {
    purpose: "To prevent fires at {{company.name}} work sites, yards, shops and vehicles.",
    scope: ALL_WORKERS,
    hazards: "Ignition of flammable fluids and vapours during fueling and transfer; hot work; electrical faults; smoking; oily rags; hot exhaust on dry grass; static discharge.",
    controls: HIERARCHY + " Bonding and grounding during transfers; no smoking near flammables; hot work permits; spark arrestors where required; approved containers for flammable liquids.",
    practice: "Keep ignition sources away from flammable liquids and vapours. Shut off engines when fueling. Bond and ground during flammable liquid transfers. Store flammables in approved containers and cabinets. Do not park hot vehicles over dry vegetation. Fire extinguishers are carried in every unit and located throughout the shop, inspected monthly and serviced annually, and workers know how to use them. A fire that cannot be controlled with one extinguisher is left to emergency services: raise the alarm and evacuate.",
    ppe: "Flame-resistant clothing where required by the hazard assessment or the client.",
    training: "Fire extinguisher training at orientation and on the interval set in the training matrix.",
    references: "Alberta Occupational Health and Safety Code; Alberta Fire Code. " + OHS_REFS,
  }),
  program("ohs.workplace_inspection_program", "Planned inspections of sites, units, shops and equipment, and what happens to the findings.", {
    purpose: "To find and correct hazards at {{company.name}} before they cause harm, and to confirm the program's controls are in place.",
    scope: "Yards, shops, offices, units, equipment and active work sites.",
    elements: "Planned inspections on a schedule: shop and yard monthly; units by pre-trip and post-trip inspection daily and a supervisor inspection quarterly; active work sites by the supervisor at least weekly and at each new site; management inspections at least quarterly. Checklists specific to the area. Worker and committee or representative participation. Findings rated by priority and assigned as corrective actions with a due date.",
    responsibilities: "{{company.safetyManager}} sets the schedule and checklists. Supervisors and managers perform inspections. The committee or representative participates. Workers report hazards between inspections.",
    implementation: "Inspections are recorded in LeaseOS. Every finding that is not corrected on the spot becomes a corrective action. A finding that presents imminent danger stops the work or removes the equipment from service immediately.",
    evaluation: "Completion of scheduled inspections and closure of findings are reported to management monthly and feed the COR readiness picture.",
    records: "Inspection checklists, findings and their corrective actions",
    references: OHS_REFS,
  }),
  program("ohs.corrective_action_system", "Every finding gets an owner, a due date and a second person's verification.", {
    purpose: "To make sure hazards, inspection findings, incident causes, audit findings and review outcomes at {{company.name}} are actually corrected.",
    scope: "Corrective actions from any source: inspections, incidents, near misses, hazard reports, audits, policy reviews, training gaps and client requirements.",
    elements: "Each corrective action records its source, a description, the root cause where known, a priority, one assigned owner and a due date. Actions move from open, to in progress, to completed (with a note of what was done and evidence where available), to verified by a person other than the one who completed it. Overdue is derived from the due date. Cancellation records the reason.",
    responsibilities: "The person who opens an action assigns it with a realistic due date. The owner completes it and records what was done. A supervisor, manager or {{company.safetyManager}} verifies it — never the person who completed it. Management reviews overdue actions.",
    implementation: "Corrective actions are managed in LeaseOS. Critical actions are due within 24 hours or the work stops. High within 7 days, medium within 30, low within 90, unless a different date is justified and recorded.",
    evaluation: "Overdue and completed-but-unverified actions are reported to management monthly and appear on the COR readiness dashboard. Repeated actions from the same cause trigger a review of the underlying practice or procedure.",
    records: "Corrective actions with their full history",
    references: OHS_REFS,
  }),
  procedure("ohs.safety_meetings_and_toolbox_talks", "Regular safety meetings and the pre-job tailgate meeting.", {
    purpose: "To give workers of {{company.name}} a regular place to learn, raise concerns and plan work safely together.",
    scope: "All crews, the shop and the office.",
    definitions: "**Tailgate or pre-job meeting**: a short meeting at the work site before work starts. **Toolbox talk**: a short focused talk on one safety topic. **Safety meeting**: a longer scheduled meeting reviewing performance, incidents and program changes.",
    responsibilities: "Supervisors hold a tailgate meeting before each job and a toolbox talk at least weekly with their crew. {{company.safetyManager}} provides topics and holds a company safety meeting at least monthly. Workers attend and participate.",
    equipment: "The meeting record in LeaseOS; the FLHA for the job; topic material.",
    hazards: "The meeting reviews the hazards of the day's work and any recent incidents or near misses.",
    steps: "Tailgate meeting: review the job scope, the FLHA, permits, roles, the emergency plan and communication for the site; ask every worker if they have concerns; confirm stop-work authority. Toolbox talk: one topic, relevant to current work or season, with discussion. Safety meeting: review incidents and near misses since the last meeting, corrective action status, inspection findings, program changes, and worker concerns, with minutes.",
    emergency: "Every tailgate meeting names the muster point, the first aider, and how to call for help from the site.",
    training: "Supervisors are trained to lead meetings and encourage participation.",
    records: "Meeting records with attendance, topics and concerns raised",
    references: OHS_REFS,
  }),
  policy("ohs.right_to_refuse_dangerous_work", "How a refusal of dangerous work is made, investigated and resolved, without reprisal.", {
    purpose: "To set out how a worker of {{company.name}} exercises the right to refuse dangerous work, and how the refusal is handled.",
    scope: ALL_WORKERS,
    statement: "A worker may refuse to carry out any work, or to operate any tool, appliance or equipment, when they believe on reasonable grounds that there is a dangerous condition at the work site or that the work constitutes a danger to their health and safety or that of another person. The worker is not subject to reprisal for refusing, and continues to be paid while the refusal is investigated.",
    responsibilities: "The worker reports the refusal and the reasons to the supervisor promptly. The supervisor investigates immediately, with the worker and, where there is one, a committee member or the representative, and takes action to eliminate the danger. Management ensures a written report is prepared and given to the worker. {{company.safetyManager}} tracks every refusal.",
    requirements: "While the refusal is investigated, the worker may be assigned temporarily to other work that is safe. Another worker may be assigned to the refused work only after being told in writing of the refusal, the reasons, and why the employer believes the work is safe. Where the refusal is not resolved at the work site, the worker or employer may contact Alberta OHS, and an officer may investigate. The written report records the refusal, the investigation, and the action taken.",
    records: "Refusal reports, investigations and actions taken",
    references: "Alberta Occupational Health and Safety Act — right to refuse dangerous work and protection from discriminatory action. " + OHS_REFS,
    nonCompliance: "Reprisal against a worker for a refusal made in good faith is a serious breach, dealt with under the Policy enforcement and disciplinary process, and may also be an offence under the Act.",
  }),
  procedure("ohs.safety_observations_and_near_miss_reporting", "Reporting hazards, unsafe acts and near misses so they are fixed before someone is hurt.", {
    purpose: "To make it easy and safe for anyone at {{company.name}} to report a hazard, an unsafe act or condition, or a near miss, and to ensure every report is acted on.",
    scope: ALL_WORKERS + " Clients and the public may also report through the office.",
    definitions: "**Near miss**: an event that did not cause injury or damage but could have. **Safety observation**: a recorded observation of a safe or unsafe act or condition. **Hazard report**: a report of a condition that could cause harm.",
    responsibilities: "Everyone reports what they see. Supervisors act on reports immediately where there is danger, and within the shift otherwise. {{company.safetyManager}} reviews all reports weekly, looks for trends and shares lessons. Management recognizes good reporting.",
    equipment: "The LeaseOS near-miss and observation report, available on the worker's device, including voice entry; paper cards in units where devices are not available.",
    hazards: "Unreported hazards and near misses are the incidents of the future. Fear of blame is the main reason they are not reported; this procedure removes it.",
    steps: "1. Make the situation safe if you can do so safely.\n2. Report it: what happened or what you saw, where, when, and what could have happened.\n3. The supervisor reviews, takes immediate action and records it.\n4. Anything not corrected on the spot becomes a corrective action with an owner and due date.\n5. Near misses with serious potential are investigated like incidents.\n6. The reporter is told what was done.\n7. Lessons are shared at safety meetings without naming the reporter unless they agree.",
    emergency: "A near miss that reveals an ongoing danger stops the work until it is controlled.",
    training: "Orientation covers how to report and the no-blame commitment.",
    records: "Near-miss reports, safety observations and their corrective actions",
    references: OHS_REFS,
  }),
  program("ohs.health_and_safety_program_20_or_more_workers", "The written health and safety program Alberta requires of employers with 20 or more regularly employed workers.", {
    purpose: "To establish and maintain the written health and safety program that {{company.name}} must have as an Alberta employer with 20 or more regularly employed workers, and to show where each required element lives in this safety management system.",
    scope: "All operations of {{company.name}} in Alberta. Where the workforce is below 20 regularly employed workers, the program is still maintained as good practice.",
    elements: "The program consists of, and this document maps to: the Health and Safety Policy; hazard assessment and control (hazard assessment policy, formal assessment, FLHA, JHA, JSA); the emergency response plan; a statement of the responsibilities of the employer, supervisors and workers (the responsibilities policies); the schedule and procedures for work site inspections (workplace inspection program); procedures to be followed when another employer or a self-employed person is at the work site (contractor responsibilities and contractor management); health and safety orientation and training (worker orientation, training and competency policy, training matrix); procedures for investigating incidents, injuries and refusals to work (incident management module, right to refuse dangerous work); procedures for worker participation in the program, including in inspections and investigations (committee or representative procedure, safety meetings); and procedures for reviewing and revising the program (document control and revision policy).",
    responsibilities: "The President is accountable for the program. {{company.safetyManager}} maintains it. The committee or representative participates in its development and review.",
    implementation: "The program is assembled in LeaseOS from the packs selected for {{company.name}}. Each element is a controlled document with an owner, an approver and a review date. The program's operation is evidenced by the records each element generates.",
    evaluation: "The program is reviewed at least on the interval the Act requires, and in any case annually by {{company.name}}, when work site conditions change, and after serious incidents, in consultation with the committee or representative. COR readiness is reviewed quarterly.",
    records: "The program map, its elements and their review records",
    references: "Alberta Occupational Health and Safety Act — health and safety programs. " + OHS_REFS,
  }),
  procedure("ohs.health_and_safety_committee_or_representative", "Establishing and supporting the joint committee or the health and safety representative.", {
    purpose: "To establish worker participation in health and safety at {{company.name}} through a joint work site health and safety committee or a health and safety representative, as the workforce size requires.",
    scope: "{{company.name}} where it regularly employs 20 or more workers (joint committee) or 5 to 19 workers (representative), confirmed against the Act as consolidated.",
    definitions: "**Joint work site health and safety committee**: a committee of worker and employer members that participates in the health and safety program. **Health and safety representative**: a worker designated to perform the committee's functions where a committee is not required. **Co-chairs**: one worker member and one employer member who chair the committee together.",
    responsibilities: "Management establishes the committee or representative and gives members the time, training and information they need. Worker members are selected by the workers, not appointed by management. The committee or representative meets, inspects, participates in investigations, and makes recommendations; the employer responds to recommendations in writing within the time the Act sets.",
    equipment: "Meeting minutes and recommendation records in LeaseOS; access to inspection and incident records.",
    hazards: "Not applicable as a task; the committee or representative participates in the identification and control of hazards across the program.",
    steps: "1. Determine the workforce size and whether a committee or a representative is required.\n2. For a committee: at least half the members are workers who do not exercise managerial functions, selected by the workers; employer members are appointed by management; two co-chairs are chosen, one from each side.\n3. For a representative: the workers select the representative.\n4. Members and the representative receive the training the Act requires.\n5. The committee meets at least quarterly, with minutes posted where workers can see them.\n6. The committee or representative takes part in inspections and in the investigation of serious incidents and refusals.\n7. Recommendations are recorded; the employer responds in writing and the response is tracked.\n8. Names and contact details of members or the representative are posted and covered in orientation.",
    emergency: "The committee or representative is informed promptly of any serious incident and of any refusal of dangerous work.",
    training: "Committee members and representatives complete the training required for the role.",
    records: "Committee terms of reference, member lists, minutes, recommendations and responses",
    references: "Alberta Occupational Health and Safety Act — joint work site health and safety committees and health and safety representatives. " + OHS_REFS,
  }),
];
