/**
 * Alberta Commercial / Oilfield Safety Template Pack — category 4: Oilfield and industrial operations.
 *
 * Thirty-six templates, loaded as drafts: twenty-six in the oilfield pack and ten in the hydrovac / vacuum
 * truck pack. The pack rules hold: merge fields only, no section numbers. Figures stated — the 19.5 per cent
 * oxygen floor, the 100 ppm H2S level at which the sense of smell is lost and which is commonly treated as
 * immediately dangerous to life or health, the 10 ppm and 15 ppm H2S exposure limits — are for the reviewer
 * to confirm against the OHS Code as consolidated. Where an industry or client figure varies by site
 * (alarm set points, LEL limits for hot work, spacing from wellheads, hydrovac pressure and temperature near
 * buried facilities), the text names who sets it instead of inventing one.
 */
import type { ContentTemplate } from "../safetyProgramContentTypes";
import { form, plan, policy, procedure } from "./shared";

const FIELD = "Every worker, supervisor and contractor of {{company.name}} working on an oil and gas lease, facility, pipeline right-of-way or industrial client site.";
const UNITS = "Every hydrovac, vacuum-truck and combination unit of {{company.name}}, its operators and swampers, at every site where it works.";
const REFS = "Alberta Occupational Health and Safety Act, Regulation and Code; the client's site rules and permits as recorded in the client overlay; recognized industry practice where the client adopts it — as cited by the reference keys linked to this document in LeaseOS.";
const H2S_FACTS = "Hydrogen sulphide (H2S) is a colourless, toxic, flammable gas, heavier than air, that collects in low areas, tanks, pits and excavations. It smells of rotten eggs at low concentrations, but at around 100 ppm it deadens the sense of smell, so smell is never a warning. At high concentrations it causes immediate collapse and death. It is found in sour gas, sour crude, produced water, sewage, tank bottoms and sludge.";
const DETECTOR = "a personal gas monitor bump-tested before each day's use and calibrated on the manufacturer's schedule, with alarm set points configured by {{company.safetyManager}} at or below the occupational exposure limits";
const EMERGENCY = "Stop work, make the area safe if it can be done without risk, raise the alarm, muster upwind or crosswind, account for every person, and follow the site and company emergency response plans. Nobody attempts a rescue they are not trained and equipped for.";

export const OILFIELD_INDUSTRIAL: readonly ContentTemplate[] = [
  procedure("oilfield_industrial.general_oilfield_orientation", "What every worker learns before their first oilfield site.", {
    purpose: "To give every worker of {{company.name}} the oilfield-specific knowledge they need before working on a lease or facility.",
    scope: FIELD,
    definitions: "**Lease**: the surface area of a well site or facility. **Sour**: containing H2S. **Prime contractor**: the party responsible for coordinating health and safety on a work site with more than one employer. **Client orientation**: the site- or company-specific orientation a client requires.",
    responsibilities: "{{company.safetyManager}} maintains the orientation and confirms completion. Supervisors confirm each worker holds the industry and client orientations the site requires before dispatch. Workers complete and keep them current.",
    equipment: "Orientation material; the client's site rules from the client overlay.",
    hazards: "H2S and other toxic gases; flammable atmospheres; pressure and stored energy; mobile equipment; overhead lines and buried facilities; line of fire; remote locations; weather.",
    steps: "Before the first oilfield site the worker completes: 1. the company worker orientation; 2. this oilfield orientation covering site entry, permits, H2S, gas detection, ignition control, line of fire, mobile equipment, spotters, and the emergency muster; 3. H2S training to the standard the client requires; 4. any industry orientation the client requires; 5. the client's own orientation where required. Each is recorded in the training matrix.",
    emergency: "The worker can explain the site's muster point, alarm signals, wind direction indicator, and how to call for help.",
    training: "As listed in the procedure; refreshed on the matrix interval.",
    records: "Orientation records and certificates",
    references: REFS,
  }),
  procedure("oilfield_industrial.lease_and_site_entry_procedures", "Arriving at, entering and leaving a lease or facility.", {
    purpose: "To ensure {{company.name}} workers enter and leave client sites safely and in accordance with site rules.",
    scope: FIELD,
    definitions: "**Site entry**: the point at which a worker passes the lease boundary or gate. **Sign-in**: the record of who is on site.",
    responsibilities: "Drivers and crews follow site entry rules. Supervisors confirm permits and orientations. Dispatch provides the site information and any access instructions recorded in LeaseOS.",
    equipment: "Personal gas monitor; site PPE; radio or phone; the site's access instructions from LeaseOS.",
    hazards: "Sour gas releases; traffic and congestion on the lease; unknown site conditions; other contractors' work; weather.",
    steps: "1. Before arrival, check the access route and any radio-controlled roads.\n2. Stop at the lease entrance; read posted signs, the wind sock and any warning.\n3. Turn on and check the personal gas monitor before entering.\n4. Contact the site supervisor or client representative and sign in.\n5. Confirm the work permit, the site hazards, other work in progress and the muster point.\n6. Park facing out, upwind where practicable, at the location the site directs, away from wellheads and process equipment.\n7. Complete the FLHA with the crew.\n8. On leaving, close permits, sign out and report any change in site conditions.",
    emergency: "If an alarm sounds or a monitor alarms on entry, do not enter: retreat upwind and report.",
    training: "Oilfield orientation and client orientation.",
    records: "Sign-in records, permits and FLHAs",
    references: REFS,
  }),
  policy("oilfield_industrial.prime_contractor_responsibilities", "What the company does when it is, or works under, the prime contractor.", {
    purpose: "To set out how {{company.name}} meets its obligations where a work site has more than one employer, whether {{company.name}} is the prime contractor or works under one.",
    scope: "Every work site where two or more employers or self-employed persons are involved in work at the same time.",
    statement: "Every such work site has a prime contractor. The owner of the work site is the prime contractor unless it designates another party in writing. Where {{company.name}} is the prime contractor, it establishes a system or process to ensure compliance with the OHS legislation by every employer and worker on the site, and coordinates their health and safety. Where another party is the prime contractor, {{company.name}} complies with its system and cooperates with it.",
    responsibilities: "Management agrees in writing when {{company.name}} accepts prime contractor status. As prime contractor, {{company.safetyManager}} sets up site coordination (orientation, hazard assessment sharing, permits, emergency response, meetings) and the site supervisor runs it. Under another prime contractor, supervisors follow its system and report hazards to it.",
    requirements: "The prime contractor's identity is recorded for each site in LeaseOS. As prime contractor: orient every employer's workers to site hazards and rules; share hazard assessments; coordinate permits and SIMOPS; run one emergency response plan; hold coordination meetings; record and follow up non-compliance. Under another prime contractor: obtain its rules and emergency plan before starting; attend its meetings; report incidents to it as well as internally.",
    records: "Prime contractor designations, site coordination records and non-compliance follow-up",
    references: "Alberta Occupational Health and Safety Act — prime contractors. " + REFS,
  }),
  form("oilfield_industrial.permit_to_work", "The company permit used where the client does not issue one, or in addition to the client's.", {
    header: "Safe Work Permit. Issued before non-routine or hazardous work begins. Records permit number, site, work location, issuer, receiver, date, valid from and to (one shift unless renewed).",
    fields: "Description of the work. Hazard assessment reference. Associated permits (hot work, confined space entry, ground disturbance, lifting). Isolations and lockouts in place. Atmospheric test results with time, instrument and tester (O2, LEL, H2S, other). Required PPE and equipment. Fire and emergency equipment. Communication method. Other work in the area (SIMOPS). Special precautions. Conditions under which the permit is suspended.",
    signoff: "The issuer signs that the conditions are in place. The receiver signs that they understand them, and briefs the crew, who sign. The permit is closed by the issuer and receiver when the work is complete and the area is safe. A change in conditions suspends the permit until it is reassessed.",
    retention: "The permit is displayed at the work location while open and filed when closed.",
  }),
  procedure("oilfield_industrial.simops_simultaneous_operations", "Coordinating two or more operations that could affect each other.", {
    purpose: "To control the added hazards when {{company.name}} work runs at the same time and place as other operations.",
    scope: FIELD,
    definitions: "**SIMOPS**: two or more operations in close proximity whose hazards could interact. **Person in charge**: the single person with authority to coordinate SIMOPS and stop any operation.",
    responsibilities: "The prime contractor or client names the person in charge. {{company.name}} supervisors identify SIMOPS on arrival, take part in coordination, and stop work when the interaction is not controlled.",
    equipment: "Common radio channel; SIMOPS plan or matrix; permits for each operation.",
    hazards: "Ignition sources near another crew's flammable release; mobile equipment conflicts; lifts over other work; pressure testing near other crews; blocked emergency routes.",
    steps: "1. Identify every operation in the area and its hazards.\n2. Agree which combinations are allowed, restricted, or prohibited.\n3. Agree one person in charge, one muster point and one alarm.\n4. Use a common communication channel.\n5. Reassess when an operation starts, stops or changes.\n6. Any worker may stop work when an interaction is not controlled.",
    emergency: "One emergency response plan covers all operations on the site.",
    training: "Supervisors are trained in SIMOPS coordination.",
    records: "SIMOPS plans and coordination meeting records",
    references: REFS,
  }),
  policy("oilfield_industrial.line_of_fire_policy", "Never put your body where energy or a load can reach it.", {
    purpose: "To prevent struck-by and caught-between injuries at {{company.name}}.",
    scope: FIELD + " Applies equally in the shop and yard.",
    statement: "No worker places any part of their body in the line of fire: the path of a moving object, a released energy, a load or a vehicle. Work is planned so that the line of fire is identified and kept clear.",
    responsibilities: "Workers identify the line of fire on every task and position themselves outside it. Supervisors plan tasks to keep people out of it and correct anyone in it. Everyone uses stop-work authority when they see someone in the line of fire.",
    requirements: "The FLHA names the line of fire for each task. Typical lines of fire: pressurized hoses and connections, suspended loads, backing vehicles, rotating equipment, tensioned chains and binders, and falling material. Hose restraints and whip checks are used on pressurized connections. Tag lines are used on loads.",
    records: "FLHAs and line-of-fire observations",
    references: REFS,
  }),
  policy("oilfield_industrial.pinch_and_crush_point_policy", "Keeping hands and bodies out of pinch and crush points.", {
    purpose: "To prevent hand and body injuries from pinch and crush points at {{company.name}}.",
    scope: FIELD,
    statement: "Hands and bodies are kept out of pinch and crush points. Tools, push sticks and tag lines are used instead of hands to guide equipment, hoses and loads.",
    responsibilities: "Workers identify pinch and crush points before each task. Supervisors provide the tools to avoid them. Mechanics keep guards in place.",
    requirements: "Pinch and crush points are identified on the FLHA. Coupling, hose connection, tank lid and boom work use tools to keep hands clear. Communication between operator and worker is agreed before moving equipment near a worker.",
    records: "FLHAs and incident records",
    references: REFS,
  }),
  procedure("oilfield_industrial.h2s_procedure", "Working where H2S is or may be present.", {
    purpose: "To protect {{company.name}} workers from exposure to hydrogen sulphide.",
    scope: FIELD + " Applies wherever H2S is or may be present, including sour sites, produced water, tank bottoms, sludge and sewage.",
    definitions: "**H2S**: hydrogen sulphide. **OEL**: occupational exposure limit. **SCBA**: self-contained breathing apparatus. **SABA**: supplied-air breathing apparatus.",
    responsibilities: "Supervisors identify H2S sites and ensure monitors, breathing apparatus and trained workers are present. Workers wear and watch their monitor and evacuate on alarm. {{company.safetyManager}} maintains monitor and breathing apparatus programs.",
    equipment: DETECTOR.charAt(0).toUpperCase() + DETECTOR.slice(1) + ". SCBA or SABA where the hazard assessment requires it, with workers fit-tested. Wind direction indicator. Communication device.",
    hazards: H2S_FACTS + " The OHS Code sets an eight-hour exposure limit (10 ppm) and a ceiling (15 ppm), which the reviewer confirms against the Code as consolidated.",
    steps: "1. Before work, determine from the client and site information whether H2S may be present and at what concentration.\n2. Wear a personal monitor at all times on site.\n3. Position units and workers upwind, and identify two escape routes.\n4. Where concentrations may exceed the exposure limit, work on supplied air under a client permit with a standby person.\n5. Never put your head into a hatch, tank or opening that may contain H2S without the protection the permit requires.\n6. On a monitor alarm: stop, hold your breath, move upwind or crosswind to the muster point, and report.\n7. Do not re-enter until the area is tested and cleared.",
    emergency: "A person down where H2S may be present is a gas rescue: do not enter without SCBA and a trained partner. Raise the alarm and follow the H2S emergency response plan.",
    training: "H2S training (H2S Alive or the equivalent the client requires) and breathing apparatus training, in the training matrix.",
    records: "Monitor bump-test and calibration records, training records, H2S alarms and exposures",
    references: REFS,
  }),
  procedure("oilfield_industrial.gas_detection", "Personal and area gas monitoring: selection, bump testing, calibration and response.", {
    purpose: "To ensure {{company.name}} workers can detect hazardous atmospheres before they are harmed.",
    scope: FIELD + " Includes shop and yard work with tanks and vacuum units.",
    definitions: "**Bump test**: exposing a monitor to a known gas to confirm it alarms. **Calibration**: adjusting a monitor's readings against a reference gas. **Four-gas monitor**: oxygen, LEL (flammability), H2S and carbon monoxide.",
    responsibilities: "Workers bump-test their monitor before each day's use and wear it in the breathing zone. {{company.safetyManager}} manages calibration and alarm settings. Supervisors ensure monitors are present and working.",
    equipment: "Four-gas personal monitors; area monitors and sampling pumps where required; calibration gas; a docking station or calibration records.",
    hazards: "Oxygen deficiency or enrichment; flammable atmospheres; H2S; carbon monoxide; other contaminants the hazard assessment identifies.",
    steps: "1. Bump-test before each day's use; a failed bump test takes the monitor out of service.\n2. Calibrate on the manufacturer's schedule and after a failed bump test.\n3. Wear the monitor in the breathing zone, turned on, for the whole time on site.\n4. Test atmospheres before entry or hot work, from outside, at top, middle and bottom.\n5. Treat a low-oxygen reading as an alarm: the OHS Code treats an atmosphere below 19.5 per cent oxygen as unsafe to breathe.\n6. On any alarm, leave the area upwind and report.\n7. Record alarms in LeaseOS.",
    emergency: "A monitor alarm is an evacuation, not an inconvenience. Never silence and continue.",
    training: "Gas detection training before first use.",
    records: "Bump-test logs, calibration records and alarm reports",
    references: REFS,
  }),
  plan("oilfield_industrial.h2s_emergency_response", "What happens when H2S is released or a worker is down.", {
    purpose: "To protect life when H2S is released or a worker may have been overcome on a {{company.name}} job.",
    scope: FIELD + " Works together with the client's emergency response plan, which governs on the client's site.",
    roles: "Site supervisor: incident commander until the client or prime contractor takes command. Trained rescuers: two, with SCBA, for any rescue. First aider. Dispatch: calls emergency services and the client, and records times. {{company.safetyManager}}: notification and investigation. Emergency numbers, the client's emergency contact and the nearest medical facility are recorded for the site in LeaseOS.",
    activation: "Activated by a gas monitor alarm with a worker who cannot be accounted for, a visible or reported release, a worker down in an area where H2S may be present, or the client's alarm.",
    actions: "1. Raise the alarm.\n2. Everyone not involved in rescue evacuates upwind or crosswind to the muster point.\n3. Account for all workers.\n4. Rescue only by trained workers wearing SCBA, working in pairs, with a standby.\n5. Remove the casualty to fresh air upwind.\n6. Give first aid; provide oxygen where trained; begin CPR if needed.\n7. Call emergency services; give the location and that H2S is involved.\n8. Isolate the source if it can be done safely.\n9. Keep everyone out until the area is tested and cleared.",
    communication: "Dispatch notifies emergency services, the client and {{company.safetyManager}}. The regulator is notified where the law requires. Only the designated person speaks to media.",
    recovery: "The incident is investigated. Exposed workers are medically assessed. Monitors are downloaded for the record. The plan is reviewed for lessons.",
    drills: "H2S rescue drills are held at least annually with each crew that works on sour sites, and recorded.",
    records: "Emergency activations, drill records and investigation reports",
    references: REFS,
  }),
  procedure("oilfield_industrial.ignition_source_control", "Keeping ignition sources away from flammable atmospheres.", {
    purpose: "To prevent fires and explosions from ignition sources brought onto {{company.name}} work sites.",
    scope: FIELD,
    definitions: "**Ignition source**: anything that can ignite a flammable atmosphere — flame, spark, hot surface, static, electrical equipment, engines. **Hazardous area**: an area where a flammable atmosphere may be present.",
    responsibilities: "Supervisors identify hazardous areas and the controls. Workers keep ignition sources out of them.",
    equipment: "Gas monitor; intrinsically safe or rated equipment for hazardous areas; bonding and grounding cables.",
    hazards: "Vehicle engines, exhaust and catalytic converters; mobile phones and electronics; smoking; static from fluid transfer; hot work.",
    steps: "1. Identify hazardous areas from the client and the hazard assessment.\n2. Park and position engines at the distance the client's site rules set from wellheads, tanks and vents, and upwind.\n3. Test the atmosphere before starting engines or pumps near a possible release.\n4. Use only equipment rated for the hazardous area inside it.\n5. Bond and ground during flammable fluid transfers.\n6. No smoking except in designated areas.\n7. Hot work only under a hot work permit.",
    emergency: "Flammable alarm: shut down engines where safe to do so, evacuate upwind, report.",
    training: "Oilfield orientation.",
    records: "Permits and atmospheric test records",
    references: REFS,
  }),
  procedure("oilfield_industrial.flammable_and_combustible_atmosphere", "Recognizing and working in or near flammable atmospheres.", {
    purpose: "To protect workers from fire and explosion where flammable or combustible gases, vapours or dusts may be present.",
    scope: FIELD,
    definitions: "**LEL**: lower explosive limit, the lowest concentration at which a gas or vapour can ignite. **Flammable liquid / combustible liquid**: liquids that give off vapour that can ignite, at lower and higher temperatures respectively.",
    responsibilities: "Supervisors confirm testing and controls. Workers test, monitor and leave on alarm.",
    equipment: "Four-gas monitor; ventilation equipment; rated equipment; fire extinguisher.",
    hazards: "Vapour from tanks, vacuum exhaust, spills and open hatches; ignition by static, sparks or engines.",
    steps: "1. Test the atmosphere before work and continuously during it.\n2. Ventilate or purge to bring the atmosphere below the LEL limit the OHS Code and the client's permit set for the work.\n3. Control ignition sources.\n4. Vent vacuum exhaust away from people and ignition sources, downwind.\n5. Stop work and leave if the LEL alarm sounds.",
    emergency: "Fire or explosion: evacuate, raise the alarm, follow the emergency response plan.",
    training: "Gas detection and oilfield orientation.",
    records: "Atmospheric test records",
    references: REFS,
  }),
  procedure("oilfield_industrial.grounding_and_bonding", "Preventing static discharge during fluid transfer.", {
    purpose: "To prevent ignition from static electricity during the transfer of flammable or combustible fluids by {{company.name}}.",
    scope: UNITS + " Also applies to fueling from bulk tanks and transfers in the yard.",
    definitions: "**Bonding**: connecting containers so they are at the same electrical potential. **Grounding**: connecting a container to earth.",
    responsibilities: "Operators bond and ground before every transfer. Mechanics inspect cables and clamps.",
    equipment: "Bonding and grounding cables with clamps that bite through paint; conductive hoses where required; a ground rod or verified ground.",
    hazards: "Static build-up from flow through hoses, splash filling, and fluid movement in tanks; discharge igniting vapour.",
    steps: "1. Before connecting hoses, attach the bonding cable between the unit and the tank or container.\n2. Ground the unit where the site or client requires.\n3. Confirm clamps make metal-to-metal contact.\n4. Start flow slowly; avoid splash filling.\n5. Keep the bond in place until hoses are disconnected and vapours have dissipated.\n6. Remove the bond last.",
    emergency: "Fire at the transfer point: stop the pump at the emergency stop if safe, evacuate, raise the alarm.",
    training: "Vacuum-truck and fluid transfer training.",
    records: "Cable inspection records",
    references: REFS,
  }),
  procedure("oilfield_industrial.hot_work", "Welding, cutting, grinding and other spark-producing work.", {
    purpose: "To prevent fires and explosions from hot work by or near {{company.name}} workers.",
    scope: FIELD + " Applies in the shop and yard where flammables are present.",
    definitions: "**Hot work**: work that produces flame, sparks or heat able to ignite a flammable material, including welding, cutting, grinding and heating. **Fire watch**: a trained person who watches for fire during and after hot work.",
    responsibilities: "The client or {{company.name}} issues a hot work permit. The worker follows its conditions. The fire watch remains for the period the permit sets after work ends.",
    equipment: "Hot work permit; gas monitor; fire extinguisher; fire blankets and shields.",
    hazards: "Ignition of vapours, residues in vessels and lines, and combustibles; burns; fumes.",
    steps: "1. Obtain a hot work permit.\n2. Test the atmosphere; work proceeds only within the limits the permit sets and with continuous monitoring.\n3. Isolate, drain, purge and clean any vessel or line worked on.\n4. Remove or cover combustibles.\n5. Post a fire watch with an extinguisher.\n6. Stop if the monitor alarms.\n7. The fire watch stays after work ends for the time the permit sets.\n8. Close the permit.",
    emergency: "Fire: use the extinguisher if small and safe; otherwise evacuate and raise the alarm.",
    training: "Hot work and fire watch training.",
    records: "Hot work permits and atmospheric test records",
    references: REFS,
  }),
  procedure("oilfield_industrial.confined_space", "Entering confined spaces under a permit, with testing, a safety watch and a rescue plan.", {
    purpose: "To protect {{company.name}} workers who enter confined spaces.",
    scope: FIELD + " Includes tanks, vessels, vaults, pits and excavations meeting the definition.",
    definitions: "**Confined space**: a restricted space which may become hazardous to a worker entering it because of an atmosphere that is or may be hazardous, or its design, construction, location or contents, or the work activity in it. **Entry permit**: written authorization for entry. **Safety watch (attendant)**: a trained person outside who monitors the entrant and summons rescue.",
    responsibilities: "{{company.name}} maintains a code of practice for confined space entry as the OHS Code requires. A competent person assesses each space and issues the entry permit. The safety watch never enters to rescue. Entrants follow the permit.",
    equipment: "Entry permit; gas monitor; ventilation; isolation and lockout equipment; communication; retrieval system where practicable; breathing apparatus where required; rescue equipment.",
    hazards: "Toxic, flammable or oxygen-deficient atmospheres; engulfment; energy; temperature; restricted egress.",
    steps: "1. Prefer methods that do not require entry.\n2. Assess the space and write the entry permit.\n3. Isolate and lock out all energy and lines.\n4. Ventilate and test the atmosphere at top, middle and bottom before entry and continuously during it.\n5. Post a trained safety watch in constant communication with the entrant.\n6. Confirm the rescue plan and rescuers are ready before entry.\n7. Enter only within the permit's conditions; leave on any alarm or change.\n8. Close the permit when all entrants are out.",
    emergency: "The safety watch raises the alarm and starts non-entry rescue. Entry rescue only by trained rescuers with the equipment the rescue plan names.",
    training: "Confined space training for entrants, safety watches and rescuers.",
    records: "Entry permits, atmospheric tests and the confined space code of practice",
    references: "Alberta Occupational Health and Safety Code — confined spaces. " + REFS,
  }),
  procedure("oilfield_industrial.tank_entry", "Entering tanks and vessels, in addition to the confined space procedure.", {
    purpose: "To add tank-specific controls to the confined space procedure for {{company.name}} work inside tanks and vessels.",
    scope: FIELD,
    definitions: "As in the confined space procedure. **Tank bottoms / sludge**: residues that can release H2S and hydrocarbons when disturbed.",
    responsibilities: "As in the confined space procedure. The client provides tank history and contents.",
    equipment: "As in the confined space procedure, plus non-sparking tools and rated lighting.",
    hazards: "H2S and hydrocarbons released from sludge as it is disturbed; NORM in scale; engulfment; slippery surfaces; heat.",
    steps: "1. Obtain the tank's contents history from the client.\n2. Drain, vacuum and wash the tank before entry where possible.\n3. Blind or disconnect every line; do not rely on closed valves.\n4. Follow the confined space procedure in full.\n5. Expect the atmosphere to change as sludge is disturbed; monitor continuously.\n6. Test scale for NORM where the client identifies it.",
    emergency: "As in the confined space procedure.",
    training: "Confined space training and H2S training.",
    records: "Entry permits and tank history",
    references: REFS,
  }),
  procedure("oilfield_industrial.pressure_hazards", "Recognizing and controlling pressure in vessels, lines and hoses.", {
    purpose: "To prevent injuries from the release of pressure at {{company.name}} work sites.",
    scope: FIELD,
    definitions: "**Trapped pressure**: pressure remaining in a line or vessel after isolation. **Pressure rating**: the maximum pressure a component may safely contain.",
    responsibilities: "Workers verify zero pressure before opening anything. Supervisors confirm equipment ratings.",
    equipment: "Pressure gauges; bleed valves; rated hoses and fittings; whip checks.",
    hazards: "Sudden release, projectiles, hose whip, fluid injection, and freezing in lines.",
    steps: "1. Identify every pressure source and component rating.\n2. Never exceed a component's rating.\n3. Isolate, then bleed and verify zero pressure before opening.\n4. Expect trapped pressure behind plugs, including ice plugs.\n5. Stand out of the line of fire when opening.",
    emergency: "Uncontrolled release: get clear, raise the alarm, isolate from a safe position.",
    training: "Pressure awareness training.",
    records: "Equipment rating records",
    references: REFS,
  }),
  procedure("oilfield_industrial.stored_energy_hazards", "Recognizing and releasing stored energy before work.", {
    purpose: "To prevent injuries from stored mechanical, hydraulic, pneumatic, gravitational and thermal energy.",
    scope: FIELD,
    definitions: "**Stored energy**: energy remaining in a system after it has been shut down.",
    responsibilities: "As in the lockout procedure.",
    equipment: "Blocks, cribbing and pins; bleed valves.",
    hazards: "Raised booms and bodies; compressed springs; charged accumulators; tensioned chains and cables; hot surfaces.",
    steps: "1. Identify stored energy on the equipment.\n2. Lower, block or pin raised components.\n3. Bleed hydraulic and pneumatic systems.\n4. Release tension.\n5. Allow to cool.\n6. Verify before starting work, as in the lockout procedure.",
    emergency: "As in the lockout procedure.",
    training: "Lockout training.",
    records: "Lockout records",
    references: REFS,
  }),
  procedure("oilfield_industrial.high_pressure_lines", "Working near and with high-pressure lines and temporary piping.", {
    purpose: "To protect workers near high-pressure lines, including temporary flow lines and pressure testing.",
    scope: FIELD,
    definitions: "**Restraint**: anchoring of a line to prevent movement if it fails. **Exclusion zone**: an area kept clear during pressurization.",
    responsibilities: "The line owner controls pressurization. {{company.name}} workers stay outside exclusion zones and never work on a pressurized line.",
    equipment: "Restraints and whip checks; barricades; rated components.",
    hazards: "Line failure, whip, projectiles and fluid release.",
    steps: "1. Confirm line ratings and restraints before pressurization.\n2. Establish and barricade an exclusion zone.\n3. No hammering, tightening or striking connections under pressure.\n4. Bleed down and verify before any work on the line.",
    emergency: "Line failure: stay clear, raise the alarm, isolate remotely.",
    training: "Pressure awareness training.",
    records: "Pressure test records",
    references: REFS,
  }),
  procedure("oilfield_industrial.rig_movement", "Moving rigs and large equipment between sites.", {
    purpose: "To move rigs and large equipment safely.",
    scope: "Any move of a rig or large equipment in which {{company.name}} units or workers take part.",
    definitions: "**Move plan**: the route, permits, pilots, sequence and communication for the move.",
    responsibilities: "The move coordinator plans and leads. Drivers follow the plan and pilot instructions. Spotters guide.",
    equipment: "Permits; pilot vehicles; radios; signage.",
    hazards: "Overhead power lines; bridges and road limits; soft ground; multiple heavy units moving together; spotter struck-by.",
    steps: "1. Survey the route for power lines, bridges and ground conditions.\n2. Obtain over-dimension and over-weight permits.\n3. Hold a pre-move meeting covering sequence, signals and communication.\n4. Use pilots and spotters as the permit and plan require.\n5. Stop when anyone loses communication or sight.",
    emergency: "Contact with a power line: follow the electrical safety practice. Collision: follow collision reporting.",
    training: "Move coordinators and spotters are trained.",
    records: "Move plans and permits",
    references: REFS,
  }),
  procedure("oilfield_industrial.spotter_and_signaller_procedures", "Guiding equipment and lifts with one designated signaller.", {
    purpose: "To ensure moving equipment and lifts at {{company.name}} are guided safely by a competent spotter or signaller.",
    scope: FIELD,
    definitions: "**Spotter**: a worker who guides a moving vehicle. **Signaller**: a worker who directs a lift or equipment movement using standard signals.",
    responsibilities: "Only one designated signaller directs at a time; any person may give the stop signal. Operators follow only the designated signaller, except for stop.",
    equipment: "High-visibility clothing; radio for blind lifts; standard hand signal chart.",
    hazards: "Spotters struck by the equipment they guide; miscommunication.",
    steps: "1. Agree signals before movement.\n2. The spotter stands where the operator can see them and outside the path.\n3. If the operator loses sight of the spotter, stop.\n4. Use radio where line of sight is not possible.\n5. Stop on any stop signal from anyone.",
    emergency: "Stop signal from anyone stops all movement.",
    training: "Spotter and signaller training.",
    records: "Training records",
    references: REFS,
  }),
  procedure("oilfield_industrial.heavy_equipment_interaction", "Working on foot around heavy equipment.", {
    purpose: "To prevent workers on foot being struck by heavy equipment.",
    scope: FIELD,
    definitions: "**Blind spot**: an area around equipment the operator cannot see.",
    responsibilities: "Operators know their blind spots and stop when a worker enters the work zone. Workers on foot make eye contact before approaching.",
    equipment: "High-visibility clothing; radios; barricades.",
    hazards: "Struck-by, run-over, swing radius, falling material.",
    steps: "1. Stay out of the swing radius and travel path.\n2. Make eye contact and get acknowledgement before approaching.\n3. Approach from the operator's view side.\n4. Operators lower attachments and stop before workers approach.",
    emergency: "As in the emergency response plan.",
    training: "Orientation; site rules.",
    records: "Incident and observation records",
    references: REFS,
  }),
  procedure("oilfield_industrial.mobile_equipment_exclusion_zones", "Barricading and controlling access around mobile equipment.", {
    purpose: "To keep workers out of areas where mobile equipment is operating.",
    scope: FIELD,
    definitions: "**Exclusion zone**: a defined area where entry is restricted while equipment operates.",
    responsibilities: "Supervisors set and mark zones. Operators stop when a zone is breached.",
    equipment: "Cones, barricades, signs.",
    hazards: "Struck-by and crushing.",
    steps: "1. Mark the exclusion zone.\n2. Control entry by permission of the operator.\n3. Stop operations if the zone is breached.",
    emergency: "As in the emergency response plan.",
    training: "Orientation.",
    records: "FLHAs",
    references: REFS,
  }),
  procedure("oilfield_industrial.crane_and_lifting_procedures", "Planning and performing lifts.", {
    purpose: "To ensure lifts by or near {{company.name}} are planned, within capacity, and performed by competent people.",
    scope: "Lifts by cranes, picker trucks, booms and hoisting equipment operated by or for {{company.name}}.",
    definitions: "**Load chart**: the manufacturer's capacity chart. **Critical lift**: a lift above the threshold {{company.name}} sets in its lift plan requirement, or over people, process equipment or another crew.",
    responsibilities: "Operators are certified and competent for the equipment. The lift supervisor approves critical lift plans. The designated signaller directs.",
    equipment: "Load chart; rigging rated for the load; tag lines; outrigger pads.",
    hazards: "Overload, tip-over, contact with power lines, dropped loads, struck-by.",
    steps: "1. Determine the load weight and rigging weight.\n2. Check the load chart for radius and configuration.\n3. Set outriggers on firm ground and pads.\n4. Check for overhead lines and keep the safe limit of approach.\n5. Prepare a written lift plan for critical lifts.\n6. Use tag lines; never stand under a suspended load.\n7. Stop in high wind or poor visibility.",
    emergency: "Tip-over or dropped load: clear the area, raise the alarm.",
    training: "Operator certification and competency; rigger training.",
    records: "Lift plans and inspection records",
    references: "Alberta Occupational Health and Safety Code — cranes, hoists and lifting devices; rigging. " + REFS,
  }),
  procedure("oilfield_industrial.rigging", "Selecting, inspecting and using rigging.", {
    purpose: "To ensure rigging used by {{company.name}} is suitable, inspected and used within its working load limit.",
    scope: "All slings, shackles, hooks and below-the-hook devices.",
    definitions: "**Working load limit**: the maximum load rigging may carry. **Sling angle**: the angle between a sling leg and horizontal; lower angles increase sling tension.",
    responsibilities: "Riggers inspect before use. Damaged rigging is removed from service and destroyed or tagged.",
    equipment: "Rated, tagged rigging; softeners.",
    hazards: "Rigging failure; dropped loads.",
    steps: "1. Select rigging rated for the load including the effect of sling angle.\n2. Inspect before each use against the rejection criteria; remove from service if tag is missing or damage is found.\n3. Protect slings from sharp edges.\n4. Never exceed the working load limit.",
    emergency: "As in the lifting procedure.",
    training: "Rigger training.",
    records: "Rigging inspection records",
    references: "Alberta Occupational Health and Safety Code — rigging. " + REFS,
  }),
  procedure("oilfield_industrial.suspended_loads", "Never under, always controlled.", {
    purpose: "To prevent workers being struck by suspended loads.",
    scope: FIELD,
    definitions: "**Suspended load**: any load lifted off the ground by a crane, boom or hoist.",
    responsibilities: "Everyone stays out from under suspended loads. Signallers keep the path clear.",
    equipment: "Tag lines.",
    hazards: "Dropped loads; swinging loads.",
    steps: "1. Never stand or walk under a suspended load.\n2. Control loads with tag lines.\n3. Clear the path before the lift.\n4. Do not ride loads or hooks.",
    emergency: "As in the lifting procedure.",
    training: "Orientation and rigging training.",
    records: "Observation records",
    references: REFS,
  }),
  procedure("oilfield_industrial.hydrovac_procedures", "Hydrovac excavation: locating, daylighting and digging near buried facilities.", {
    purpose: "To ensure hydrovac excavation by {{company.name}} is performed safely and without damage to buried facilities.",
    scope: UNITS + " Applies to every hydrovac excavation, including daylighting buried facilities.",
    definitions: "**Hydrovac excavation**: excavation using pressurized water to break soil and vacuum to remove it. **Daylighting**: exposing a buried facility. **Ground disturbance**: any work that disturbs the ground below the depth the applicable rules define.",
    responsibilities: "The operator follows the ground disturbance permit and this procedure. Supervisors confirm locates and permits before digging. The swamper assists and acts as spotter.",
    equipment: "Hydrovac unit; wand with dead-man control; locate information; ground disturbance permit; gas monitor; PPE including face shield.",
    hazards: "Striking buried facilities; injection injury from the wand; boom contact with overhead lines; hose whip; noise; slippery ground; excavation collapse; H2S or gas from a struck facility.",
    steps: "1. Confirm locates, the ground disturbance permit and owner notifications are in place.\n2. Verify marks on site.\n3. Position the unit upwind, clear of overhead lines and outside the hand-exposure zone footprint where possible.\n4. Keep water pressure and temperature within the limits the facility owner or permit sets for digging near buried facilities.\n5. Keep the wand moving; never point it at a person.\n6. Expose facilities carefully and record their location.\n7. Barricade open excavations.\n8. Dump the debris only at an approved location.",
    emergency: "Facility strike: stop, shut down, evacuate upwind, call the facility owner and emergency services, and follow the damage response procedure.",
    training: "Hydrovac competency and ground disturbance training.",
    records: "Permits, locates and excavation records",
    references: REFS,
  }),
  procedure("oilfield_industrial.vacuum_truck_procedures", "Operating vacuum trucks safely with flammable and sour fluids.", {
    purpose: "To ensure vacuum-truck operations by {{company.name}} are safe from fire, toxic gas and pressure hazards.",
    scope: UNITS,
    definitions: "**Vacuum truck**: a unit that loads fluids or solids by vacuum. **Exhaust**: air and vapour discharged from the vacuum pump.",
    responsibilities: "Operators follow this procedure and the client's site rules. Supervisors confirm controls.",
    equipment: "Gas monitor; bonding and grounding cables; rated hoses with whip checks; exhaust hose to vent vapours downwind.",
    hazards: "H2S and flammable vapour in exhaust; static ignition; hose failure; overfill; pressure in the tank.",
    steps: "1. Identify the fluid and its hazards.\n2. Position upwind, at the distance from wellheads and tanks the client's site rules set.\n3. Bond and ground.\n4. Route the exhaust downwind, away from people and ignition sources.\n5. Monitor the atmosphere.\n6. Never exceed the tank's capacity or pressure rating.\n7. Close valves and secure hoses before moving.",
    emergency: "Release or alarm: shut down, evacuate upwind, raise the alarm.",
    training: "Vacuum-truck competency and H2S training.",
    records: "Loads, manifests and atmospheric test records",
    references: REFS,
  }),
  procedure("oilfield_industrial.tank_cleaning", "Cleaning tanks without entry where possible.", {
    purpose: "To clean tanks safely, preferring methods that do not require entry.",
    scope: UNITS,
    definitions: "As in the tank entry procedure.",
    responsibilities: "Supervisors choose the method and permits.",
    equipment: "Vacuum unit; wash equipment; gas monitor.",
    hazards: "As in tank entry and vacuum-truck procedures.",
    steps: "1. Prefer non-entry methods.\n2. Isolate the tank.\n3. Vacuum fluids and sludge, monitoring the atmosphere.\n4. If entry is required, follow the confined space and tank entry procedures.",
    emergency: "As in the confined space procedure.",
    training: "As for vacuum trucks and confined space.",
    records: "Permits and manifests",
    references: REFS,
  }),
  procedure("oilfield_industrial.pressure_washing", "High-pressure washing of equipment and tanks.", {
    purpose: "To prevent injection injuries and other hazards during pressure washing.",
    scope: UNITS,
    definitions: "**Injection injury**: fluid forced through the skin by high pressure.",
    responsibilities: "Operators use equipment within its ratings.",
    equipment: "Gun with dead-man trigger; rated hoses; face shield; waterproof PPE.",
    hazards: "Injection injury; hose whip; slippery surfaces; flying debris.",
    steps: "1. Inspect equipment.\n2. Never point the gun at anyone.\n3. Release the trigger before moving.\n4. Treat any suspected injection as a medical emergency.",
    emergency: "Injection injury: go to hospital immediately even if it looks minor.",
    training: "Pressure washing training.",
    records: "Inspection records",
    references: REFS,
  }),
  procedure("oilfield_industrial.fluid_transfer", "Transferring fluids between tanks, units and facilities.", {
    purpose: "To prevent spills, fires and exposures during fluid transfer by {{company.name}}.",
    scope: UNITS,
    definitions: "**Transfer point**: where hoses connect between containers.",
    responsibilities: "Operators stay at the transfer point.",
    equipment: "Rated hoses; bonding cables; spill kit; drip trays.",
    hazards: "Spills; overfill; static; hose failure.",
    steps: "1. Confirm fluid, volume and receiving capacity.\n2. Bond and ground.\n3. Use drip trays at connections.\n4. Stay with the transfer.\n5. Stop before full; check levels.",
    emergency: "Spill: stop, contain, report.",
    training: "Vacuum-truck competency.",
    records: "Manifests and spill reports",
    references: REFS,
  }),
  procedure("oilfield_industrial.chemical_transfer", "Transferring chemicals with the SDS in hand.", {
    purpose: "To transfer chemicals safely.",
    scope: UNITS,
    definitions: "**SDS**: safety data sheet.",
    responsibilities: "Operators read the SDS before transfer.",
    equipment: "Chemical-resistant PPE as the SDS requires; eyewash; spill kit.",
    hazards: "Chemical exposure; incompatibility reactions.",
    steps: "1. Read the SDS.\n2. Confirm compatibility with the receiving container and residues.\n3. Wear the PPE the SDS requires.\n4. Transfer as in the fluid transfer procedure.",
    emergency: "Exposure: follow the SDS first aid; spill: contain and report.",
    training: "WHMIS and chemical handling.",
    records: "Transfer records",
    references: REFS,
  }),
  procedure("oilfield_industrial.loading_and_unloading", "Loading and unloading fluids at sites and facilities.", {
    purpose: "To load and unload safely at sites and receiving facilities.",
    scope: UNITS,
    definitions: "**Receiving facility**: a licensed facility that accepts the load.",
    responsibilities: "Operators follow the facility's rules.",
    equipment: "As for fluid transfer.",
    hazards: "As for fluid transfer; traffic at facilities; hatch work at height.",
    steps: "1. Follow facility instructions.\n2. Chock wheels and bond.\n3. Use fall protection for hatch work where required.\n4. Record volumes.",
    emergency: "As for fluid transfer.",
    training: "Vacuum-truck competency.",
    records: "Tickets and manifests",
    references: REFS,
  }),
  procedure("oilfield_industrial.produced_water_handling", "Handling produced water and its hidden hazards.", {
    purpose: "To handle produced water safely and in compliance with its disposal requirements.",
    scope: UNITS,
    definitions: "**Produced water**: water produced with oil and gas, which may contain hydrocarbons, salts, H2S and NORM.",
    responsibilities: "Operators treat produced water as potentially sour.",
    equipment: "Gas monitor; PPE.",
    hazards: "H2S; hydrocarbons; NORM; corrosive salts.",
    steps: "1. Assume H2S may be present.\n2. Follow vacuum-truck procedures.\n3. Dispose only at a facility licensed to receive it, with the manifest.",
    emergency: "As in the H2S procedure.",
    training: "H2S and vacuum-truck training.",
    records: "Manifests",
    references: REFS + " Alberta Energy Regulator requirements for oilfield waste.",
  }),
  procedure("oilfield_industrial.sewage_and_septic_handling", "Hauling sewage and septic waste.", {
    purpose: "To protect workers from biological and gas hazards when handling sewage and septic waste.",
    scope: UNITS,
    definitions: "**Septage**: waste from septic tanks.",
    responsibilities: "Operators follow hygiene practices.",
    equipment: "Gloves; face protection; gas monitor; hand-washing supplies.",
    hazards: "Pathogens; H2S and methane; splashes.",
    steps: "1. Wear gloves and face protection.\n2. Monitor the atmosphere at tank openings.\n3. Wash hands before eating.\n4. Dispose only at an approved receiving facility.",
    emergency: "Exposure: wash and seek medical advice.",
    training: "Biological hazard awareness.",
    records: "Disposal tickets",
    references: REFS,
  }),
  procedure("oilfield_industrial.waste_and_disposal_site_procedures", "Delivering waste to approved facilities with complete paperwork.", {
    purpose: "To ensure every load of waste hauled by {{company.name}} goes only to a facility approved to receive it, with complete records.",
    scope: UNITS,
    definitions: "**Manifest**: the document that tracks waste from generator to receiver.",
    responsibilities: "Dispatch verifies the receiving facility. Operators carry the manifest and obtain the receipt.",
    equipment: "Manifest; LeaseOS disposal record.",
    hazards: "As for fluid transfer; facility traffic.",
    steps: "1. Verify the facility can accept the waste type before dispatch.\n2. Carry the manifest.\n3. Follow facility rules.\n4. Obtain the disposal ticket and record it in LeaseOS.",
    emergency: "As for fluid transfer.",
    training: "Waste handling training.",
    records: "Manifests and disposal tickets",
    references: REFS,
  }),
];
