#!/usr/bin/env bash
# Generates LEASEOS_CURRENT_STATE.md from the source of truth — the source.
# Every count here is READ from the code; none is written by hand. The CI
# gate regenerates it and fails if the committed copy differs.
set -euo pipefail
cd "$(dirname "$0")/.."
RELEASE="${1:-$(ls LEASEOS_B2*_*.md | sort -V | tail -1 | sed -E 's/.*_V?([0-9]+_[0-9]+(_[0-9]+)?)_.*/\1/; s/_/./g')}"
TABLES=$(grep -c 'mysqlTable(' drizzle/schema.ts)
MIGRATIONS=$(ls drizzle/*.sql | wc -l | tr -d ' ')
ROUTERS=$(ls server/*Router*.ts server/routers.ts server/recordsRouter.ts 2>/dev/null | sort -u)
PROCS=$(cat $ROUTERS | grep -c 'roleProcedure(' || true)
EXT_PROCS=$(grep -c 'externalProcedure(' server/portalRouter.ts 2>/dev/null || echo 0)
INB_PROCS=$(grep -c 'integrationProcedure(' server/integrationRouter.ts || true)
BARE=$(cat $ROUTERS | grep -cE 'protectedProcedure\s*$|protectedProcedure\.' || true)
PERMS=$(node -e '
const fs=require("fs");const s=fs.readFileSync("server/_core/recordsAuthorization.ts","utf8");
const u=s.slice(s.indexOf("export type Permission ="), s.indexOf("/** The read categories"));
const perms=new Set([...u.matchAll(/"([a-z_.]+)"/g)].map(m=>m[1]));
// Count string literals on non-comment lines only: a name quoted inside a comment is not a permission.
const arr=(name)=>{const m=s.match(new RegExp("export const "+name+"[^=]*= \\[([\\s\\S]*?)\\](?: as const)?;"));return [...m[1].split("\n").map(l=>l.replace(/\/\/.*$/,"")).join("\n").matchAll(/"([^"]+)"/g)].length;};
const sensN=arr("SENSITIVE_PERMISSIONS"), uniN=arr("UNIVERSAL_PERMISSIONS");
console.log(perms.size+" "+sensN+" "+uniN);')
set -- $PERMS; PERM_COUNT=$1; SENS_COUNT=$2; UNI_COUNT=$3
TEST_FILES=$(ls server/*.test.ts server/_core/*.test.ts 2>/dev/null | wc -l | tr -d ' ')
TEST_CASES=$(cat server/*.test.ts server/_core/*.test.ts | grep -cE '^\s*it\(' || true)
NATIVE=$(grep -o 'NotOnDeviceError(' client/src/runtime/adapters/capacitor.ts | wc -l | tr -d ' ')
cat > LEASEOS_CURRENT_STATE.md <<MD
# LeaseOS — Current State (generated; do not edit by hand)

Generated by \`scripts/current-state.sh\` from the source. The CI gate
regenerates this file and fails if the committed copy differs, so no count
here can be added rather than read.

| Measure | Value | Read from |
|---|---|---|
| Release | **$RELEASE** | latest checkpoint filename |
| Tables | **$TABLES** | \`mysqlTable(\` declarations in \`drizzle/schema.ts\` |
| Migrations | **$MIGRATIONS** | \`drizzle/*.sql\` (slots 0016/0017 reserved and absent) |
| Role-authorized procedures | **$PROCS** | \`roleProcedure(\` call sites across all routers |
| Externally-gated procedures (portal) | **$EXT_PROCS** | \`externalProcedure(\` call sites in \`server/portalRouter.ts\` |
| Integration-gated procedures (machines) | **$INB_PROCS** | \`integrationProcedure(\` call sites in \`server/integrationRouter.ts\` |
| Bare \`protectedProcedure\` | **$BARE** | must be 0 |
| Permissions | **$PERM_COUNT** | the \`Permission\` union |
| Sensitive (fail-closed) permissions | **$SENS_COUNT** | \`SENSITIVE_PERMISSIONS\` |
| Universal (self-scoped) permissions | **$UNI_COUNT** | \`UNIVERSAL_PERMISSIONS\` |
| Test files / cases | **$TEST_FILES / $TEST_CASES** | \`it(\` blocks under \`server/\` |
| Native-only runtime bindings | **$NATIVE throw \`NotOnDeviceError\`** | \`client/src/runtime/adapters/capacitor.ts\` |

## Implemented on the server (each with schema, authorization, audit, tests)

Records vault · roles and server-side authorization · payroll, finance, tax
rules (unverified) · geospatial source registry (8 verified licences, 3
blocked) · AI Secretary typed commits, OCR forms, fingerprinting · secure
field runtime protocol (server half) · fuel ledger, bulk fuel, card
statements, anomalies · roadside, purchasing, AP · compliance registry,
requirement engine, packs, calibration · insurance and risk · universal
surfaces (exceptions, inbox, my day, search, timeline) · dispatch gate with
enforcement setting · IFTA · GST/HST · period close · bank reconciliation ·
accounts receivable, credits, collections, write-offs · customer identity ·
commercial core (terms, POs and AFEs, customer rate cards, billing check) ·
external identities and the customer / vendor / facility portal · the site
sign-off chain (clocks, frozen revisions, signature authority, post-site
supplement, delay and road-hazard evidence, three closes) · portal
hardening (invitations, TOTP MFA, token rotation, lockout, external access
log) · client discretionary adjustments (hour-equivalent, never worked time)
· deterministic PDF rendering from frozen revisions · weather and
road-hazard observations · customer live view (operational state, readiness
projection, templated notices) · customer transaction (alerts on the
existing queue, chain of custody, approval queue, timeline, completion
package, vendor and facility shells) · fleet shop (parts ledger with cores
and counts, tires by serial and axle position, warranty policies and
two-person claims, serialized tools, recalls held unverified, work-order
and unit cost that names what it cannot know) · capital assets (one
identity per unit, two-person capital review, CCA class as a verified
candidate, pool arithmetic with the claim UNKNOWN until the rate is
verified, year-end schedule reviewed by a second person, the asset twin) ·
commercial projects (quotes priced from the card and frozen at issue,
hash-accepted under signatory authority, change orders recorded within or
above authority, RFIs, budgets by cost code, honest forecasts) ·
integration gateway (machine clients with hashed keys and scopes,
idempotent inbound events that become proposals, signed webhooks with
scheduled retries and a dead letter) · telematics and video safety
(telemetry with odometer reconciliation, fault codes a mechanic makes
defects, driving events reviewed once with no driver score, video as a
hashed pointer under its own logged permission) · workforce lifecycle
(evidenced screenings, hires refused while a screening is pending,
onboarding credentials entering the registry on a second person's
verification, supervisor-signed competency, two-person probation,
offboarding that revokes every door) · audit packages (vehicle, driver, job,
customer, incident, tax, COR, insurance — hashed manifests, listed
redactions, named gaps, two-person release) · spatial foundation (LSD/UWI
validation, theoretical grid positions labelled as such, coordinates
verified from ATS or a field fix, vehicle profiles, road restrictions as
verified-or-not rule rows, four-axis segment evaluation, route requests
answered UNKNOWN with no routing source) · contract terms (approved by a
second person, deciding standby, holds, disposal time and return travel
with a cited clause, grace minutes and a minimum that raises what is billed
and says so; the drain worker dispatches webhooks and sweeps retries) ·
money precision (vendor bills, their lines and fuel transactions hold money
only as integers; thirty grandfathered double money columns remain, pinned
by test,
every one with an integer shadow — cents for amounts, thousandths for
per-unit rates — backfilled, dual-written where the application writes,
trigger-guaranteed for everything else, and reconciled every run; the
GST/HST return reads the shadows) · operational truth boundary (legacy
creates refuse trust-bearing input at the schema and write honest states;
identity and trip binding resolved from the session; demonstration pages
quarantined under /showcase behind a write-refusing link; production paths
on authoritative surfaces) · commercial setup & rate resolution (charge
definitions for every pricing method and four rate kinds, proposed by one
person and approved by another, deterministic precedence with conflicts,
unknowns, conversion and measurement review named, immutable pricing
decisions, margin guardrails as policy, PO exposure, go-live readiness; the mapping foundation — ATS legal subdivisions and
Alberta access roads imported from the province's own services under the
Open Government Licence, each row carrying its source, layer, run and
retrieval time, an LSD locator that separates the parcel's centroid from the
truck's access point, and lease coordinates verified from the imported grid
as ats_v41; a GPS fix read back as legal land, entrances proposed from the
grid and confirmed by a second person with confidence counted from the
passages that actually reached them, and imported roads evaluated on the
four axes where every limit the province does not state reads UNKNOWN,
restrictions applied only inside their effective window with the most
restrictive governing, structures whose posted limits are limits and whose
rated capacities are not, and route approvals that go stale by fingerprint
when the unit, load, permits, restrictions, structures or road data change; a
routing graph built from the imported road fabric that computes a real path
and hands it to the evaluator rather than treating it as a permission;
ticket and vendor-bill lines that name a service are
priced as they are recorded and carry their decision, with vendor rate
variances listed) · the invoice path (drafted from a signed ticket's
accepted lines and their decisions, the billing book opened and its entries
written, finalized by a second permission into a hashed snapshot — refused
without a treatment, refused taxable on an unverified rate; rendered from
the snapshot, sent with the account's terms and an alert, listed, viewed
and accepted in the customer portal; supplemental drafts for lines released
by a resolved dispute or a void; disputes resolved upheld, credited or
partial with the credit approved by a second person in AR; voids recorded,
never deleted, refused where money is applied).

## Implemented on the client (logic proven in Node; platform bindings named)

Field runtime: contracts, envelope crypto, durable outbox, sync engine,
browser fallback. Internal portal: shell, switcher, My Day, exceptions,
inbox, timeline, search, sync indicator, quick capture, view-models.
Customer portal at \`/customer\`: invitation acceptance, job board,
pre-clearance, signing screen, chain of custody, adjustments, line disputes,
approval queue, timeline, alerts and preferences, documents with download,
notices, daily report. Vendor and facility portal at \`/vendor\` and
\`/facility\`: statements and submissions. First-run setup wizard in the
office portals: company, services, guardrails, rates with approval,
readiness — every step the server's answer.

## Not implemented — and not claimed

Native shell (Capacitor), encrypted SQLite, hardware keystore, native file
vault, camera, GPS, biometric signing, local notifications. Browser/mobile
end-to-end tests. Routing services (a native graph built from imported Alberta road data routes within built areas; no provincial routing source — P0 outside them; PostGIS/Valhalla/Martin/MapLibre not deployed; ATS v4.1 importable per township and imported where a person has run it — coordinates are verified one at a time with evidence). Fluids as measured inventory (parts ledger only). Contracts and MSAs as
records; WBS below cost code; earned-value schedules. AI extraction of rate sheets from
uploaded documents (a proposal path exists; the document reader that fills
it does not); formula pricing is recorded, not evaluated. inbound
vendor bills and facility tickets by machine (portal only). GPS on the
board and route-derived segments (P0). Email/SMS delivery of customer alerts
(queued in-app only). Video clips in the vault (pointers and hashes only); posted speed limits
from a verified source (feed-supplied, marked unverified). Payroll final-pay computation on offboarding (proposed only). Package bundles as archives (manifest and cover only).

## Blocked on things only a person can do

**P9** — no regulatory, tax or rate rule is verified; every determination on
the seeds is UNKNOWN and the loading paths are controller-only.
**AER ST37 / ST102 / Alberta 511** — inspection-only pending written permission.
**P0/P5** — no routing source; the original spatial branch was never supplied.

## Historical documents

\`LEASEOS_BUILD_PLAN*.md\`, \`LEASEOS_BUILD_SPEC*.md\`,
\`LEASEOS_MASTER_PROGRAMMING_MANIFEST_V*.md\`, \`LEASEOS_TAXONOMY_ROUTING*.md\`
and \`LEASEOS_BILLING_RECORDS_CHAIN*.md\` describe v2–v7-era plans. They carry
a HISTORICAL banner and must not be read as implementation state. The
per-release checkpoints (\`LEASEOS_B2*_*.md\`) are the record of what was
built and when; this file is the record of what is.
MD
echo "generated LEASEOS_CURRENT_STATE.md for $RELEASE"
