#!/usr/bin/env bash
# Merge the base branch and settle the one conflict that is not a decision.
#
# WHY THIS EXISTS. `LEASEOS_CURRENT_STATE.md` is generated by
# `scripts/current-state.sh` from the tree, and gate 8 fails if the committed
# copy has drifted. So every branch regenerates it, and every branch therefore
# conflicts with every other branch on it. Measured on 2026-09-25: of nine open
# pull requests that could not merge into `main`, six conflicted on this file
# and nothing else.
#
# PICKING A SIDE IS WRONG, not merely lazy. The counts describe the tree, and
# the merged tree is neither parent. Reconciling one such branch by hand gave:
#
#     ours    365 / 5035        theirs  365 / 5035 + its own edits
#     merged  366 / 5047        <- what the file must say, and what neither side said
#
# `git checkout --ours` or `--theirs` therefore commits a number that is false
# about the merge. Gate 8 does catch it, but a CI cycle later, which is the
# expensive way to learn it.
#
# WHY NOT A GIT MERGE DRIVER. A driver declared in `.gitattributes` would run
# mid-merge, when git has not necessarily written the rest of the tree yet, and
# `current-state.sh` reads the tree — `drizzle/schema.ts`, the routers,
# `recordsAuthorization.ts`, every `*.test.ts`. Worse, if any other file is also
# conflicted, the generator reads conflict markers and produces counts that are
# confidently wrong. Regenerating AFTER the merge has settled, and only once
# nothing else is in conflict, is the version that cannot lie. (A driver would
# also not help GitHub's own merge, which runs server-side and never sees it.)
#
# WHAT THIS REFUSES TO DO. Any conflict other than the generated file is a
# decision about behaviour, and this script stops and hands it back rather than
# resolving it. It also stops on a dirty tree, and it never commits: the merge is
# left staged so the result is read before it is recorded.
set -euo pipefail
cd "$(dirname "$0")/.."

BASE="${1:-origin/main}"
GENERATED="LEASEOS_CURRENT_STATE.md"

die() { echo "reconcile-main: $*" >&2; exit 1; }

git rev-parse --verify -q "$BASE^{commit}" >/dev/null || die "no such base: $BASE"

# A dirty tree would be merged over, and the generator would then read whatever
# was half-finished. Stop before touching anything.
[ -z "$(git status --porcelain --untracked-files=no)" ] || die "working tree has uncommitted changes; commit or stash them first"
# `git rev-parse --git-path`, not `.git/MERGE_HEAD`: inside a linked worktree
# `.git` is a file and the real git directory lives elsewhere, so the literal
# path never exists and this guard would silently never fire. Found by running
# this script in a worktree, which is how the branches here are reconciled.
[ ! -e "$(git rev-parse --git-path MERGE_HEAD)" ] || die "a merge is already in progress; finish or abort it first"

if git merge-base --is-ancestor "$BASE" HEAD; then
  echo "reconcile-main: already contains $BASE; nothing to do"
  exit 0
fi

echo "reconcile-main: merging $BASE ($(git rev-parse --short "$BASE"))"
# A conflicting merge exits non-zero, which is the case this script exists for.
git merge --no-commit --no-ff "$BASE" >/dev/null 2>&1 || true

conflicts="$(git diff --name-only --diff-filter=U)"

if [ -n "$conflicts" ]; then
  others="$(printf '%s\n' "$conflicts" | grep -vFx "$GENERATED" || true)"
  if [ -n "$others" ]; then
    echo "reconcile-main: conflicts that are decisions, not bookkeeping — resolve them yourself:" >&2
    printf '  %s\n' $others >&2
    echo "reconcile-main: the merge is left in progress. Re-run this script after resolving, or 'git merge --abort'." >&2
    exit 1
  fi
fi

# Regenerate rather than resolve. The generator overwrites the file wholesale and
# never reads its previous contents, so conflict markers in it are irrelevant —
# but everything it DOES read is now merged and marker-free, which is what the
# check above guarantees.
echo "reconcile-main: regenerating $GENERATED from the merged tree"
bash scripts/current-state.sh >/dev/null

# The generator is deterministic; if it is not, the counts are not a function of
# the tree and nothing downstream of them can be trusted.
before="$(git hash-object "$GENERATED")"
bash scripts/current-state.sh >/dev/null
[ "$before" = "$(git hash-object "$GENERATED")" ] || die "$GENERATED is not reproducible: two runs of current-state.sh disagreed"

git add "$GENERATED"

# Nothing anywhere may still carry markers — including files git auto-merged and
# files the generator wrote.
if git grep -nI -e '^<<<<<<< ' -e '^>>>>>>> ' -- . >/dev/null 2>&1; then
  echo "reconcile-main: conflict markers remain in the tree:" >&2
  git grep -nI -e '^<<<<<<< ' -e '^>>>>>>> ' -- . >&2
  exit 1
fi

echo
echo "reconcile-main: merged and staged, NOT committed. Read it, then:"
echo "    git diff --cached --stat"
echo "    git commit"
