/**
 * Analytics Checkpoint B — the metric registry.
 *
 * Pure data. The one place a metric is defined, so two screens cannot compute the same number two
 * ways. `docs/analytics/CHECKPOINT_A_SURVEY.md` §7 is the design; this is the subset whose inputs the
 * tree actually has, plus the metrics the proposal asked for that the tree cannot support, registered
 * so they answer with the reason instead of being absent.
 *
 * Changing a formula changes what a number means. `METRIC_REGISTRY_VERSION` is recorded on every
 * answer and is pinned by `server/_core/analytics/metricRegistry.test.ts` against the formula texts,
 * so a formula cannot change without the version changing with it.
 *
 * Deliberately absent (see the survey, §4): fleet utilization and downtime hours need new arithmetic
 * over records nothing links today, which the SPINE moratorium reserves to the owner — they are
 * registered `not_evaluated` naming that decision. No metric here is a score, a rank or a
 * percentage, and none sums anything per driver out of telematics driving events.
 */
import type { MetricDefinition } from "./metricContract";

export const METRIC_REGISTRY_VERSION = "b.1";

const IN_PROGRESS = "status is loading, in_transit or unloading";

export const METRICS: readonly MetricDefinition[] = [
  /* ---------------------------------------------------------------- operations */
  {
    id: "ops.trips.in_progress",
    name: "Trips in progress",
    family: "operations",
    description: "Trips on the road or at a stop right now.",
    formula: `Count of trips in scope whose ${IN_PROGRESS}.`,
    sources: ["trips"],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: ["unitId", "operatorId", "jobId"],
    requiredPermission: "trip.read", selfScoped: true, breakdownBy: "status",
    freshnessSeconds: 60,
    incompleteness: "None: status is required on every trip. The status is whatever was last recorded; trips carry no state machine.",
  },
  {
    id: "ops.trips.completed",
    name: "Trips completed",
    family: "operations",
    description: "Trips completed within the range.",
    formula: "Count of trips in scope with status complete and completedAt in [from, to).",
    sources: ["trips"],
    unit: "count", aggregation: { kind: "count" }, temporal: "range",
    filters: ["unitId", "operatorId", "jobId"],
    requiredPermission: "trip.read", selfScoped: true,
    freshnessSeconds: 300,
    incompleteness: "A trip marked complete with no completedAt cannot be placed in any range; it is named in unknowns and the answer is partial.",
  },
  {
    id: "ops.jobs.with_trip_in_progress",
    name: "Jobs with a trip in progress",
    family: "operations",
    description: "Jobs that have at least one trip in progress. jobs.status is not used: it is set once at creation and never updated.",
    formula: `Count of distinct jobs in scope referenced by a trip in scope whose ${IN_PROGRESS}.`,
    sources: ["trips", "jobs"],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: ["unitId", "operatorId"],
    requiredPermission: "job.read", selfScoped: false,
    freshnessSeconds: 60,
    incompleteness: "A trip in progress with no job cannot be attributed to one; it is named in unknowns and the answer is partial.",
  },
  {
    id: "ops.drivers.on_trip",
    name: "Drivers on a trip",
    family: "operations",
    description: "Drivers named on a trip in progress.",
    formula: `Count of distinct trips.operatorId over trips in scope whose ${IN_PROGRESS}.`,
    sources: ["trips", "operators"],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: ["unitId", "jobId"],
    requiredPermission: "trip.read", selfScoped: false,
    freshnessSeconds: 60,
    incompleteness: "A trip in progress that names no driver is named in unknowns and the answer is partial.",
  },
  {
    id: "ops.units.on_trip",
    name: "Units on a trip",
    family: "operations",
    description: "Units named on a trip in progress.",
    formula: `Count of distinct trips.unitId over trips in scope whose ${IN_PROGRESS}.`,
    sources: ["trips", "units"],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: ["operatorId", "jobId"],
    requiredPermission: "trip.read", selfScoped: false,
    freshnessSeconds: 60,
    incompleteness: "A trip in progress that names no unit is named in unknowns and the answer is partial.",
  },

  /* ---------------------------------------------------------------- fleet */
  {
    id: "fleet.units.registered",
    name: "Units registered",
    family: "fleet",
    description: "Units on the fleet list. Trailers and equipment are units whose vehicle type says so; the type is free text, so the breakdown groups by the text as written.",
    formula: "Count of units in scope.",
    sources: ["units"],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: [],
    requiredPermission: "fleet.read", selfScoped: false, breakdownBy: "vehicleType",
    freshnessSeconds: 3600,
    incompleteness: "None. Units carry no in-service status, so this is a list size, not an availability count.",
  },
  {
    id: "fleet.inspections.completed",
    name: "Inspections completed",
    family: "fleet",
    description: "Pre-trip, post-trip and training inspections observed within the range.",
    formula: "Count of inspections on units in scope with observedAt in [from, to).",
    sources: ["inspections"],
    unit: "count", aggregation: { kind: "count" }, temporal: "range",
    filters: ["unitId", "operatorId"],
    requiredPermission: "inspection.read", selfScoped: true, breakdownBy: "type",
    freshnessSeconds: 300,
    incompleteness: "None: observedAt is required. The operator filter matches authenticatedOperatorId, which is empty on inspections nobody authenticated.",
  },
  {
    id: "fleet.inspections.failed",
    name: "Inspections failed",
    family: "fleet",
    description: "Inspections that found a problem within the range.",
    formula: "Count of inspections on units in scope with observedAt in [from, to) and status fail or needs_maintenance.",
    sources: ["inspections"],
    unit: "count", aggregation: { kind: "count" }, temporal: "range",
    filters: ["unitId", "operatorId"],
    requiredPermission: "inspection.read", selfScoped: true, breakdownBy: "status",
    freshnessSeconds: 300,
    incompleteness: "None: status and observedAt are required.",
  },

  /* ---------------------------------------------------------------- maintenance */
  {
    id: "maintenance.defects.open",
    name: "Open defects",
    family: "maintenance",
    description: "Defects not yet resolved.",
    formula: "Count of maintenance defects on units in scope with status open or in_progress.",
    sources: ["maintenanceDefects"],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: ["unitId"],
    requiredPermission: "maintenance.read_defect", selfScoped: false, breakdownBy: "severity",
    freshnessSeconds: 120,
    incompleteness: "None: status is required.",
  },
  {
    id: "maintenance.defects.critical_open",
    name: "Open critical defects",
    family: "maintenance",
    description: "Critical defects not yet resolved. A critical defect stops dispatch of its unit until a standing release names it.",
    formula: "Count of maintenance defects on units in scope with severity critical and status open or in_progress.",
    sources: ["maintenanceDefects"],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: ["unitId"],
    requiredPermission: "maintenance.read_defect", selfScoped: false,
    freshnessSeconds: 120,
    incompleteness: "None: severity and status are required.",
  },
  {
    id: "maintenance.defects.reported",
    name: "Defects reported",
    family: "maintenance",
    description: "Defects reported within the range, whatever their status now.",
    formula: "Count of maintenance defects on units in scope with reportedAt in [from, to).",
    sources: ["maintenanceDefects"],
    unit: "count", aggregation: { kind: "count" }, temporal: "range",
    filters: ["unitId"],
    requiredPermission: "maintenance.read_defect", selfScoped: false, breakdownBy: "severity",
    freshnessSeconds: 300,
    incompleteness: "None: reportedAt is required.",
  },
  {
    id: "maintenance.work_orders.open",
    name: "Open work orders",
    family: "maintenance",
    description: "Work orders that are open, in progress, waiting on parts or ready for service. Drafts are not open work.",
    formula: "Count of work orders on units in scope with status open, in_progress, waiting_parts or ready_for_service.",
    sources: ["workOrders"],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: ["unitId"],
    requiredPermission: "maintenance.read_defect", selfScoped: false, breakdownBy: "status",
    freshnessSeconds: 120,
    incompleteness: "None: status is required.",
  },
  {
    id: "maintenance.work_orders.repair_hours_avg",
    name: "Average repair time",
    family: "maintenance",
    description: "Mean time from opening to completion over work orders closed within the range.",
    formula: "Mean of (completedAt − openedAt) in hours over work orders on units in scope with status closed and completedAt in [from, to).",
    sources: ["workOrders"],
    unit: "hours", aggregation: { kind: "mean", field: "repairHours" }, temporal: "range",
    filters: ["unitId"],
    requiredPermission: "maintenance.read_defect", selfScoped: false,
    freshnessSeconds: 900,
    incompleteness: "A closed work order with no completedAt — every one closed through shop.workOrderAdvance, which sets no timestamps — cannot be placed in any range; it is named in unknowns and the answer is partial. With no work order closed in the range the answer is not_applicable, not zero.",
  },
  {
    id: "maintenance.work_orders.overdue",
    name: "Overdue work orders",
    family: "maintenance",
    description: "Work orders past their due date.",
    formula: "Not computed.",
    sources: [],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: [],
    requiredPermission: "maintenance.read_defect", selfScoped: false,
    freshnessSeconds: 3600,
    incompleteness: "See the reason.",
    unavailable: { determination: "not_derivable", reason: "Work orders carry no due date, so none can be overdue by the record" },
  },
  {
    id: "maintenance.downtime.scheduled_split",
    name: "Scheduled vs unscheduled downtime",
    family: "maintenance",
    description: "Downtime split by whether the work was planned.",
    formula: "Not computed.",
    sources: [],
    unit: "hours", aggregation: { kind: "count" }, temporal: "range",
    filters: [],
    requiredPermission: "maintenance.read_defect", selfScoped: false,
    freshnessSeconds: 3600,
    incompleteness: "See the reason.",
    unavailable: { determination: "not_derivable", reason: "No preventive-maintenance schedule or work-order type exists, so planned and unplanned work cannot be told apart" },
  },
  {
    id: "maintenance.downtime.hours",
    name: "Downtime hours",
    family: "maintenance",
    description: "Hours units were unavailable, from work orders, out-of-service orders, roadside breakdowns and critical defects.",
    formula: "Not computed.",
    sources: [],
    unit: "hours", aggregation: { kind: "count" }, temporal: "range",
    filters: [],
    requiredPermission: "maintenance.read_defect", selfScoped: false,
    freshnessSeconds: 3600,
    incompleteness: "See the reason.",
    unavailable: { determination: "not_evaluated", reason: "There is no downtime record; the interval union across four sources is new arithmetic the SPINE moratorium reserves to an owner decision (Checkpoint A survey, C12)" },
  },
  {
    id: "fleet.utilization",
    name: "Fleet utilization",
    family: "fleet",
    description: "Dispatched hours as a share of available hours.",
    formula: "Not computed.",
    sources: [],
    unit: "hours", aggregation: { kind: "count" }, temporal: "range",
    filters: [],
    requiredPermission: "fleet.read", selfScoped: false,
    freshnessSeconds: 3600,
    incompleteness: "See the reason.",
    unavailable: { determination: "not_evaluated", reason: "Available hours need downtime hours, which wait on the same owner decision (Checkpoint A survey, C12)" },
  },

  /* ---------------------------------------------------------------- compliance */
  {
    id: "compliance.documents.expiring",
    name: "Documents expiring",
    family: "compliance",
    description: "Verified documents that expire within 30 days, per subject and document type, as the document validity engine decides it.",
    formula: "Per subject (ownerType, ownerId) in scope and document type, complianceDocumentValidity at now with 30 days' notice; count of verdicts in state expiring.",
    sources: ["complianceDocuments"],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: ["unitId", "operatorId"],
    requiredPermission: "compliance.read", selfScoped: true, breakdownBy: "docType",
    freshnessSeconds: 3600,
    incompleteness: "Only verified versions count, as the engine rules; an unverified upload is counted by compliance.documents.unverified instead. A private document is counted with its type withheld.",
  },
  {
    id: "compliance.documents.expired",
    name: "Documents expired",
    family: "compliance",
    description: "Document types whose verified version in force has expired.",
    formula: "Per subject in scope and document type, complianceDocumentValidity at now; count of verdicts in state expired.",
    sources: ["complianceDocuments"],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: ["unitId", "operatorId"],
    requiredPermission: "compliance.read", selfScoped: true, breakdownBy: "docType",
    freshnessSeconds: 3600,
    incompleteness: "As compliance.documents.expiring.",
  },
  {
    id: "compliance.documents.unverified",
    name: "Documents awaiting verification",
    family: "compliance",
    description: "Document types on file with no verified version: a full folder, not a current one.",
    formula: "Per subject in scope and document type, complianceDocumentValidity at now; count of verdicts in state unverified.",
    sources: ["complianceDocuments"],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: ["unitId", "operatorId"],
    requiredPermission: "compliance.read", selfScoped: true, breakdownBy: "docType",
    freshnessSeconds: 3600,
    incompleteness: "As compliance.documents.expiring.",
  },
  {
    id: "compliance.readiness.checks_blocked",
    name: "Dispatch checks blocked",
    family: "compliance",
    description: "Dispatch readiness checks that returned blocked within the range. The stored verdict is the one the check made at the time.",
    formula: "Count of dispatchEligibilityChecks in scope with verdict blocked and evaluatedAt in [from, to).",
    sources: ["dispatchEligibilityChecks"],
    unit: "count", aggregation: { kind: "count" }, temporal: "range",
    filters: ["unitId", "operatorId", "jobId"],
    requiredPermission: "dispatch.read", selfScoped: true,
    freshnessSeconds: 300,
    incompleteness: "None: verdict and evaluatedAt are required. Checks made before 0174 carry no organization and are the historical single tenant's.",
  },
  {
    id: "compliance.readiness.checks_unknown",
    name: "Dispatch checks that could not decide",
    family: "compliance",
    description: "Dispatch readiness checks that returned unknown within the range — a check that could not say yes is not a pass.",
    formula: "Count of dispatchEligibilityChecks in scope with verdict unknown and evaluatedAt in [from, to).",
    sources: ["dispatchEligibilityChecks"],
    unit: "count", aggregation: { kind: "count" }, temporal: "range",
    filters: ["unitId", "operatorId", "jobId"],
    requiredPermission: "dispatch.read", selfScoped: true,
    freshnessSeconds: 300,
    incompleteness: "As compliance.readiness.checks_blocked.",
  },

  /* ---------------------------------------------------------------- safety */
  {
    id: "safety.incidents.reported",
    name: "Incidents",
    family: "safety",
    description: "Incident reports for events that occurred within the range. Counts only; no statement, person or investigation detail.",
    formula: "Count of incidentReports in scope with occurredAt in [from, to).",
    sources: ["incidentReports"],
    unit: "count", aggregation: { kind: "count" }, temporal: "range",
    filters: ["unitId", "operatorId", "jobId"],
    requiredPermission: "incident.read_summary", selfScoped: false, breakdownBy: "severity",
    freshnessSeconds: 900,
    incompleteness: "None: occurredAt is required.",
  },
  {
    id: "safety.near_misses.reported",
    name: "Near misses",
    family: "safety",
    description: "Near-miss reports for events that occurred within the range. Counts only.",
    formula: "Count of nearMissReports in scope with occurredAt in [from, to).",
    sources: ["nearMissReports"],
    unit: "count", aggregation: { kind: "count" }, temporal: "range",
    filters: ["unitId", "operatorId", "jobId"],
    requiredPermission: "incident.read_summary", selfScoped: false, breakdownBy: "status",
    freshnessSeconds: 900,
    incompleteness: "None: occurredAt is required.",
  },
  {
    id: "safety.corrective_actions.outstanding",
    name: "Corrective actions outstanding",
    family: "safety",
    description: "Corrective actions from incidents not yet completed.",
    formula: "Not computed.",
    sources: [],
    unit: "count", aggregation: { kind: "count" }, temporal: "current",
    filters: [],
    requiredPermission: "incident.read_summary", selfScoped: false,
    freshnessSeconds: 3600,
    incompleteness: "See the reason.",
    unavailable: { determination: "not_derivable", reason: "incidentActions has no writer and incidents never reach corrective_action, so no corrective action is on record" },
  },

  /* ---------------------------------------------------------------- hours of service */
  {
    id: "hos.driving_minutes_elapsed",
    name: "Driving time recorded",
    family: "hours_of_service",
    description: "Minutes logged as driving within the range. Elapsed time from duty records; it states no limit and no legal answer.",
    formula: "Sum over duty records of operators in scope with dutyStatus driving of the minutes of [startedAt, endedAt) inside [from, min(to, now)); an open record runs to now.",
    sources: ["dutyRecords"],
    unit: "minutes", aggregation: { kind: "sum", field: "minutes" }, temporal: "range",
    filters: ["operatorId"],
    requiredPermission: "hos.read", selfScoped: true,
    freshnessSeconds: 60,
    incompleteness: "A record that ends before it starts is named in unknowns and the answer is partial. Gaps between records are neither duty nor rest, as in the HOS engine.",
  },
  {
    id: "hos.on_duty_minutes_elapsed",
    name: "On-duty time recorded",
    family: "hours_of_service",
    description: "Minutes logged as driving or on duty within the range. Elapsed time only.",
    formula: "As hos.driving_minutes_elapsed, over duty records with dutyStatus driving or on_duty.",
    sources: ["dutyRecords"],
    unit: "minutes", aggregation: { kind: "sum", field: "minutes" }, temporal: "range",
    filters: ["operatorId"],
    requiredPermission: "hos.read", selfScoped: true, breakdownBy: "dutyStatus",
    freshnessSeconds: 60,
    incompleteness: "As hos.driving_minutes_elapsed.",
  },
  {
    id: "hos.limit_position",
    name: "HOS limit position",
    family: "hours_of_service",
    description: "Where a driver stands against an hours-of-service limit.",
    formula: "Not computed.",
    sources: [],
    unit: "minutes", aggregation: { kind: "count" }, temporal: "current",
    filters: [],
    requiredPermission: "hos.read", selfScoped: false,
    freshnessSeconds: 60,
    incompleteness: "See the reason.",
    unavailable: { determination: "unknown", reason: "Every HOS limit figure is unverified (P9), so the engine withholds any limit answer; only elapsed time is stated" },
  },

  /* ---------------------------------------------------------------- workforce */
  {
    id: "workforce.overtime",
    name: "Overtime",
    family: "workforce",
    description: "Hours worked beyond the pay rule's threshold.",
    formula: "Not computed.",
    sources: [],
    unit: "hours", aggregation: { kind: "count" }, temporal: "range",
    filters: [],
    requiredPermission: "personnel.read", selfScoped: false,
    freshnessSeconds: 3600,
    incompleteness: "See the reason.",
    unavailable: { determination: "not_derivable", reason: "No overtime rule is modelled anywhere in LeaseOS" },
  },
];

export function metricById(id: string): MetricDefinition | null {
  return METRICS.find(m => m.id === id) ?? null;
}
